
// Generated by Cadence Genus(TM) Synthesis Solution 22.10-p001_1
// Generated on: Mar 12 2025 23:42:25 +07 (Mar 12 2025 16:42:25 UTC)

// Verification Directory fv/USARTn 

module USART_Clk_SYNC_RST0(nrst, clk, bsel, change_cfg, rxen, txen,
     clr_tx_cnt, rx_clk_en_o, tx_clk_en_o);
  input nrst, clk, change_cfg, rxen, txen, clr_tx_cnt;
  input [11:0] bsel;
  output rx_clk_en_o, tx_clk_en_o;
  wire nrst, clk, change_cfg, rxen, txen, clr_tx_cnt;
  wire [11:0] bsel;
  wire rx_clk_en_o, tx_clk_en_o;
  wire [11:0] rx_prsc_cnt;
  wire [11:0] tx_prsc_cnt;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_95, n_96;
  INHDV1 g1336(.I (nrst), .ZN (n_72));
  INOR2HDV2 g1510__2398(.A1 (rxen), .B1 (n_74), .ZN (rx_clk_en_o));
  INOR2HDV2 g1511__5107(.A1 (txen), .B1 (n_73), .ZN (tx_clk_en_o));
  INAND3HDV2 g1512__6260(.A1 (n_96), .B1 (n_71), .B2 (n_68), .ZN
       (n_74));
  INAND3HDV2 g1513__4319(.A1 (n_95), .B1 (n_69), .B2 (n_70), .ZN
       (n_73));
  NOR4HDV1 g1514__8428(.A1 (rx_prsc_cnt[1]), .A2 (rx_prsc_cnt[11]), .A3
       (rx_prsc_cnt[0]), .A4 (rx_prsc_cnt[2]), .ZN (n_71));
  NOR4HDV1 g1515__5526(.A1 (tx_prsc_cnt[11]), .A2 (tx_prsc_cnt[10]),
       .A3 (tx_prsc_cnt[0]), .A4 (tx_prsc_cnt[1]), .ZN (n_70));
  OR4HDV2 g1516__6783(.A1 (rx_prsc_cnt[6]), .A2 (rx_prsc_cnt[7]), .A3
       (rx_prsc_cnt[4]), .A4 (rx_prsc_cnt[5]), .Z (n_96));
  NOR4HDV1 g1517__3680(.A1 (tx_prsc_cnt[3]), .A2 (tx_prsc_cnt[2]), .A3
       (tx_prsc_cnt[9]), .A4 (tx_prsc_cnt[8]), .ZN (n_69));
  NOR4HDV1 g1518__1617(.A1 (rx_prsc_cnt[10]), .A2 (rx_prsc_cnt[9]), .A3
       (rx_prsc_cnt[8]), .A4 (rx_prsc_cnt[3]), .ZN (n_68));
  OR4HDV2 g1519__2802(.A1 (tx_prsc_cnt[4]), .A2 (tx_prsc_cnt[5]), .A3
       (tx_prsc_cnt[6]), .A4 (tx_prsc_cnt[7]), .Z (n_95));
  DRQHDV2 \rx_prsc_cnt_reg[0] (.RD (n_72), .CK (clk), .D (n_6), .Q
       (rx_prsc_cnt[0]));
  DRQHDV2 \rx_prsc_cnt_reg[1] (.RD (n_72), .CK (clk), .D (n_10), .Q
       (rx_prsc_cnt[1]));
  DRQHDV2 \rx_prsc_cnt_reg[2] (.RD (n_72), .CK (clk), .D (n_17), .Q
       (rx_prsc_cnt[2]));
  DRQHDV2 \rx_prsc_cnt_reg[3] (.RD (n_72), .CK (clk), .D (n_27), .Q
       (rx_prsc_cnt[3]));
  DRQHDV2 \rx_prsc_cnt_reg[4] (.RD (n_72), .CK (clk), .D (n_34), .Q
       (rx_prsc_cnt[4]));
  DRQHDV2 \rx_prsc_cnt_reg[5] (.RD (n_72), .CK (clk), .D (n_47), .Q
       (rx_prsc_cnt[5]));
  DRQHDV2 \rx_prsc_cnt_reg[6] (.RD (n_72), .CK (clk), .D (n_59), .Q
       (rx_prsc_cnt[6]));
  DRQHDV2 \rx_prsc_cnt_reg[7] (.RD (n_72), .CK (clk), .D (n_64), .Q
       (rx_prsc_cnt[7]));
  DRQHDV2 \rx_prsc_cnt_reg[8] (.RD (n_72), .CK (clk), .D (n_41), .Q
       (rx_prsc_cnt[8]));
  DRQHDV2 \rx_prsc_cnt_reg[9] (.RD (n_72), .CK (clk), .D (n_52), .Q
       (rx_prsc_cnt[9]));
  DRQHDV2 \rx_prsc_cnt_reg[10] (.RD (n_72), .CK (clk), .D (n_62), .Q
       (rx_prsc_cnt[10]));
  DRQHDV2 \rx_prsc_cnt_reg[11] (.RD (n_72), .CK (clk), .D (n_67), .Q
       (rx_prsc_cnt[11]));
  DRQHDV2 \tx_prsc_cnt_reg[0] (.RD (n_72), .CK (clk), .D (n_9), .Q
       (tx_prsc_cnt[0]));
  DRQHDV2 \tx_prsc_cnt_reg[1] (.RD (n_72), .CK (clk), .D (n_13), .Q
       (tx_prsc_cnt[1]));
  DRQHDV2 \tx_prsc_cnt_reg[2] (.RD (n_72), .CK (clk), .D (n_16), .Q
       (tx_prsc_cnt[2]));
  DRQHDV2 \tx_prsc_cnt_reg[3] (.RD (n_72), .CK (clk), .D (n_26), .Q
       (tx_prsc_cnt[3]));
  DRQHDV2 \tx_prsc_cnt_reg[4] (.RD (n_72), .CK (clk), .D (n_35), .Q
       (tx_prsc_cnt[4]));
  DRQHDV2 \tx_prsc_cnt_reg[5] (.RD (n_72), .CK (clk), .D (n_49), .Q
       (tx_prsc_cnt[5]));
  DRQHDV2 \tx_prsc_cnt_reg[6] (.RD (n_72), .CK (clk), .D (n_58), .Q
       (tx_prsc_cnt[6]));
  DRQHDV2 \tx_prsc_cnt_reg[7] (.RD (n_72), .CK (clk), .D (n_65), .Q
       (tx_prsc_cnt[7]));
  DRQHDV2 \tx_prsc_cnt_reg[8] (.RD (n_72), .CK (clk), .D (n_42), .Q
       (tx_prsc_cnt[8]));
  DRQHDV2 \tx_prsc_cnt_reg[9] (.RD (n_72), .CK (clk), .D (n_53), .Q
       (tx_prsc_cnt[9]));
  DRQHDV2 \tx_prsc_cnt_reg[10] (.RD (n_72), .CK (clk), .D (n_63), .Q
       (tx_prsc_cnt[10]));
  DRQHDV2 \tx_prsc_cnt_reg[11] (.RD (n_72), .CK (clk), .D (n_66), .Q
       (tx_prsc_cnt[11]));
  IOA22HDV0 g2228__1705(.A1 (n_3), .A2 (bsel[11]), .B1 (n_3), .B2
       (n_61), .ZN (n_67));
  IOA22HDV0 g2229__5122(.A1 (n_5), .A2 (bsel[11]), .B1 (n_5), .B2
       (n_60), .ZN (n_66));
  IOA22HDV0 g2232__8246(.A1 (n_5), .A2 (bsel[7]), .B1 (n_5), .B2
       (n_57), .ZN (n_65));
  IOA22HDV0 g2233__7098(.A1 (n_3), .A2 (bsel[7]), .B1 (n_3), .B2
       (n_56), .ZN (n_64));
  IOA22HDV0 g2234__6131(.A1 (n_5), .A2 (bsel[10]), .B1 (n_5), .B2
       (n_55), .ZN (n_63));
  IOA22HDV0 g2237__1881(.A1 (n_3), .A2 (bsel[10]), .B1 (n_3), .B2
       (n_54), .ZN (n_62));
  XNOR2CHDV2 g2238__5115(.A1 (n_51), .A2 (rx_prsc_cnt[11]), .ZN (n_61));
  XNOR2CHDV2 g2239__7482(.A1 (n_50), .A2 (tx_prsc_cnt[11]), .ZN (n_60));
  IOA22HDV0 g2240__4733(.A1 (n_3), .A2 (bsel[6]), .B1 (n_3), .B2
       (n_46), .ZN (n_59));
  IOA22HDV0 g2241__6161(.A1 (n_5), .A2 (bsel[6]), .B1 (n_5), .B2
       (n_48), .ZN (n_58));
  XNOR2CHDV2 g2242__9315(.A1 (n_45), .A2 (tx_prsc_cnt[7]), .ZN (n_57));
  XNOR2CHDV2 g2243__9945(.A1 (n_44), .A2 (rx_prsc_cnt[7]), .ZN (n_56));
  AOI21HDV2 g2246__2883(.A1 (n_39), .A2 (tx_prsc_cnt[10]), .B (n_50),
       .ZN (n_55));
  AOI21HDV2 g2249__2346(.A1 (n_38), .A2 (rx_prsc_cnt[10]), .B (n_51),
       .ZN (n_54));
  IOA22HDV0 g2250__1666(.A1 (n_5), .A2 (bsel[9]), .B1 (n_5), .B2
       (n_43), .ZN (n_53));
  IOA22HDV0 g2251__7410(.A1 (n_3), .A2 (bsel[9]), .B1 (n_3), .B2
       (n_40), .ZN (n_52));
  IOA22HDV0 g2252__6417(.A1 (n_5), .A2 (bsel[5]), .B1 (n_5), .B2
       (n_36), .ZN (n_49));
  NOR2HDV2 g2253__5477(.A1 (n_38), .A2 (rx_prsc_cnt[10]), .ZN (n_51));
  NOR2HDV2 g2254__2398(.A1 (n_39), .A2 (tx_prsc_cnt[10]), .ZN (n_50));
  AOI21HDV2 g2255__5107(.A1 (n_33), .A2 (tx_prsc_cnt[6]), .B (n_45),
       .ZN (n_48));
  IOA22HDV0 g2256__6260(.A1 (n_3), .A2 (bsel[5]), .B1 (n_3), .B2
       (n_37), .ZN (n_47));
  AOI21HDV2 g2257__4319(.A1 (n_32), .A2 (rx_prsc_cnt[6]), .B (n_44),
       .ZN (n_46));
  NOR2HDV2 g2260__8428(.A1 (n_33), .A2 (tx_prsc_cnt[6]), .ZN (n_45));
  NOR2HDV2 g2261__5526(.A1 (n_32), .A2 (rx_prsc_cnt[6]), .ZN (n_44));
  AOI21BHDVL g2262__6783(.A (n_39), .B1 (n_28), .B2 (tx_prsc_cnt[9]),
       .ZN (n_43));
  IOA22HDV0 g2265__3680(.A1 (n_5), .A2 (bsel[8]), .B1 (n_5), .B2
       (n_31), .ZN (n_42));
  IOA22HDV0 g2266__1617(.A1 (n_3), .A2 (bsel[8]), .B1 (n_3), .B2
       (n_30), .ZN (n_41));
  AOI21BHDVL g2267__2802(.A (n_38), .B1 (n_29), .B2 (rx_prsc_cnt[9]),
       .ZN (n_40));
  AOI21BHDVL g2268__1705(.A (n_32), .B1 (n_20), .B2 (rx_prsc_cnt[5]),
       .ZN (n_37));
  OR2HDV2RD g2269__5122(.A1 (n_28), .A2 (tx_prsc_cnt[9]), .Z (n_39));
  OR2HDV2RD g2270__8246(.A1 (n_29), .A2 (rx_prsc_cnt[9]), .Z (n_38));
  AOI21BHDVL g2271__7098(.A (n_33), .B1 (n_22), .B2 (tx_prsc_cnt[5]),
       .ZN (n_36));
  IOA22HDV0 g2272__6131(.A1 (n_5), .A2 (bsel[4]), .B1 (n_5), .B2
       (n_24), .ZN (n_35));
  IOA22HDV0 g2273__1881(.A1 (n_3), .A2 (bsel[4]), .B1 (n_3), .B2
       (n_25), .ZN (n_34));
  OR2HDV2RD g2274__5115(.A1 (n_22), .A2 (tx_prsc_cnt[5]), .Z (n_33));
  OR2HDV2RD g2275__7482(.A1 (n_20), .A2 (rx_prsc_cnt[5]), .Z (n_32));
  AOI21BHDVL g2278__4733(.A (n_28), .B1 (n_23), .B2 (tx_prsc_cnt[8]),
       .ZN (n_31));
  AOI21BHDVL g2279__6161(.A (n_29), .B1 (n_21), .B2 (rx_prsc_cnt[8]),
       .ZN (n_30));
  IOA22HDV0 g2280__9315(.A1 (n_3), .A2 (bsel[3]), .B1 (n_3), .B2
       (n_19), .ZN (n_27));
  OR2HDV2RD g2281__9945(.A1 (n_21), .A2 (rx_prsc_cnt[8]), .Z (n_29));
  OR2HDV2RD g2282__2883(.A1 (n_23), .A2 (tx_prsc_cnt[8]), .Z (n_28));
  IOA22HDV0 g2283__2346(.A1 (n_5), .A2 (bsel[3]), .B1 (n_5), .B2
       (n_18), .ZN (n_26));
  AOI21BHDVL g2284__1666(.A (n_20), .B1 (n_15), .B2 (rx_prsc_cnt[4]),
       .ZN (n_25));
  AOI21BHDVL g2285__7410(.A (n_22), .B1 (n_14), .B2 (tx_prsc_cnt[4]),
       .ZN (n_24));
  OR2HDV2RD g2286__6417(.A1 (n_14), .A2 (n_95), .Z (n_23));
  OR2HDV2RD g2287__5477(.A1 (n_14), .A2 (tx_prsc_cnt[4]), .Z (n_22));
  OR2HDV2RD g2288__2398(.A1 (n_15), .A2 (n_96), .Z (n_21));
  OR2HDV2RD g2289__5107(.A1 (n_15), .A2 (rx_prsc_cnt[4]), .Z (n_20));
  AOI21BHDVL g2292__6260(.A (n_15), .B1 (n_8), .B2 (rx_prsc_cnt[3]),
       .ZN (n_19));
  AOI21BHDVL g2293__4319(.A (n_14), .B1 (n_7), .B2 (tx_prsc_cnt[3]),
       .ZN (n_18));
  IOA22HDV0 g2294__8428(.A1 (n_3), .A2 (bsel[2]), .B1 (n_3), .B2
       (n_12), .ZN (n_17));
  IOA22HDV0 g2295__5526(.A1 (n_5), .A2 (bsel[2]), .B1 (n_5), .B2
       (n_11), .ZN (n_16));
  OR2HDV2RD g2296__6783(.A1 (n_8), .A2 (rx_prsc_cnt[3]), .Z (n_15));
  OR2HDV2RD g2297__3680(.A1 (n_7), .A2 (tx_prsc_cnt[3]), .Z (n_14));
  IOA22HDV0 g2301__1617(.A1 (n_5), .A2 (bsel[1]), .B1 (n_5), .B2 (n_4),
       .ZN (n_13));
  AOI21BHDVL g2302__2802(.A (n_8), .B1 (n_0), .B2 (rx_prsc_cnt[2]), .ZN
       (n_12));
  AOI21BHDVL g2304__1705(.A (n_7), .B1 (n_1), .B2 (tx_prsc_cnt[2]), .ZN
       (n_11));
  IOA22HDV0 g2305__5122(.A1 (n_3), .A2 (bsel[1]), .B1 (n_3), .B2 (n_2),
       .ZN (n_10));
  IOA22HDV0 g2306__8246(.A1 (n_5), .A2 (bsel[0]), .B1 (n_5), .B2
       (tx_prsc_cnt[0]), .ZN (n_9));
  OR2HDV2RD g2307__7098(.A1 (n_0), .A2 (rx_prsc_cnt[2]), .Z (n_8));
  IOA22HDV0 g2308__6131(.A1 (n_3), .A2 (bsel[0]), .B1 (n_3), .B2
       (rx_prsc_cnt[0]), .ZN (n_6));
  OR2HDV2RD g2309__1881(.A1 (n_1), .A2 (tx_prsc_cnt[2]), .Z (n_7));
  I2NAND4HDV2 g2310__5115(.A1 (change_cfg), .A2 (clr_tx_cnt), .B1
       (n_73), .B2 (txen), .ZN (n_5));
  AOI21BHDVL g2311__7482(.A (n_1), .B1 (tx_prsc_cnt[0]), .B2
       (tx_prsc_cnt[1]), .ZN (n_4));
  AOI21BHDVL g2312__4733(.A (n_0), .B1 (rx_prsc_cnt[0]), .B2
       (rx_prsc_cnt[1]), .ZN (n_2));
  INAND3HDV2 g2313__6161(.A1 (change_cfg), .B1 (n_74), .B2 (rxen), .ZN
       (n_3));
  OR2HDV2RD g2314__9315(.A1 (tx_prsc_cnt[1]), .A2 (tx_prsc_cnt[0]), .Z
       (n_1));
  OR2HDV2RD g2315__9945(.A1 (rx_prsc_cnt[1]), .A2 (rx_prsc_cnt[0]), .Z
       (n_0));
endmodule

module USARTn(ireset, cp2, ram_Addr, ramre, ramwe, out_en, dbus_in,
     dbus_out, DDR_XCKn, UMSEL, XCKn_i, XCKn_o, RxDn_i, TxDn_o, RXENn,
     TXENn, TxcIRQ, RxcIRQ, UdreIRQ, UStBIRQ, irqack_addr, irqack);
  input ireset, cp2, ramre, ramwe, DDR_XCKn, XCKn_i, RxDn_i, irqack;
  input [11:0] ram_Addr;
  input [7:0] dbus_in;
  input [5:0] irqack_addr;
  output out_en, UMSEL, XCKn_o, TxDn_o, RXENn, TXENn, TxcIRQ, RxcIRQ,
       UdreIRQ, UStBIRQ;
  output [7:0] dbus_out;
  wire ireset, cp2, ramre, ramwe, DDR_XCKn, XCKn_i, RxDn_i, irqack;
  wire [11:0] ram_Addr;
  wire [7:0] dbus_in;
  wire [5:0] irqack_addr;
  wire out_en, UMSEL, XCKn_o, TxDn_o, RXENn, TXENn, TxcIRQ, RxcIRQ,
       UdreIRQ, UStBIRQ;
  wire [7:0] dbus_out;
  wire [11:0] UBRRn;
  wire [9:0] FIFO_tx_inst_fifo_buf;
  wire [9:0] FIFO_tx_inst_dout_sync;
  wire [2:0] rx_sync;
  wire [10:0] \FIFO_rx_inst_fifo_mem[0] ;
  wire [7:0] UCSRnB;
  wire [7:0] UCSRnA;
  wire [10:0] \FIFO_rx_inst_fifo_mem[1] ;
  wire [7:0] UCSRnC;
  wire [3:0] tx_baud_cnt;
  wire [1:0] FIFO_rx_inst_r_pnt;
  wire [1:0] FIFO_rx_inst_w_pnt;
  wire [10:0] tx_sh_reg;
  wire [1:0] FIFO_tx_inst_r_pnt;
  wire [1:0] FIFO_tx_inst_w_pnt;
  wire [3:0] Temp;
  wire [1:0] rc_state;
  wire [3:0] rx_baud_cnt;
  wire [3:0] rx_bitcnt;
  wire [10:0] rx_sh_reg;
  wire [3:0] tx_bitcnt;
  wire FIFO_rx_inst_n_194, XCK_int, n_0, n_1, n_15, n_16, n_17, n_18;
  wire n_22, n_26, n_28, n_29, n_36, n_40, n_42, n_61;
  wire n_83, n_96, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_145, n_146, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_222, n_223, n_224, n_225, n_226, n_227, n_228, n_229;
  wire n_230, n_231, n_232, n_233, n_234, n_235, n_236, n_237;
  wire n_238, n_239, n_240, n_241, n_242, n_243, n_244, n_245;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, n_301, n_302;
  wire n_303, n_304, n_305, n_306, n_307, n_308, n_309, n_310;
  wire n_311, n_312, n_314, n_315, n_316, n_317, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_334, n_335, n_336, n_337;
  wire n_338, n_339, n_340, n_341, n_342, n_343, n_344, n_345;
  wire n_346, n_347, n_348, n_349, n_350, n_351, n_352, n_353;
  wire n_354, n_355, n_356, n_357, n_358, n_359, n_360, n_361;
  wire n_362, n_363, n_364, n_365, n_366, n_367, n_368, n_369;
  wire n_370, n_371, n_372, n_373, n_374, n_375, n_376, n_377;
  wire n_378, n_379, n_380, n_381, n_382, n_383, n_384, n_385;
  wire n_386, n_387, n_388, n_389, n_390, n_391, n_392, n_393;
  wire n_394, n_395, n_396, n_397, n_398, n_399, n_400, n_401;
  wire n_402, n_403, n_404, n_405, n_406, n_407, n_408, n_410;
  wire n_411, n_412, n_413, n_414, n_415, n_416, n_417, n_419;
  wire n_420, n_421, n_422, n_423, n_424, n_425, n_426, n_427;
  wire n_428, n_430, n_431, n_432, n_433, n_434, n_435, n_436;
  wire n_437, n_438, n_439, n_442, n_443, n_444, n_446, n_447;
  wire n_448, n_449, n_450, n_455, n_457, n_458, n_459, n_460;
  wire n_461, n_462, n_463, n_464, n_465, n_466, n_467, n_468;
  wire n_469, n_471, n_472, n_473, n_474, n_475, n_476, n_477;
  wire n_479, n_480, n_481, n_482, n_484, n_485, n_486, n_487;
  wire n_488, n_489, n_490, n_491, n_492, n_493, n_494, n_496;
  wire n_498, n_499, n_500, n_501, n_502, n_503, n_504, n_505;
  wire n_506, n_507, n_508, n_509, n_510, n_511, n_512, n_513;
  wire n_514, n_515, n_516, n_517, n_518, n_519, n_520, n_521;
  wire n_522, n_548, n_565, n_575, n_576, n_577, n_578, n_579;
  wire n_580, n_581, n_582, n_583, n_584, n_585, rc_done, rst_status;
  wire rx_clk_en, tr_done, tr_state, tx_clk_en, tx_fifo_empty,
       tx_fifo_full, tx_samp, tx_samp_delay;
  assign UStBIRQ = 1'b0;
  USART_Clk_SYNC_RST0 USART_Clk_inst(.nrst (ireset), .clk (cp2), .bsel
       (UBRRn), .change_cfg (n_565), .rxen (RXENn), .txen (n_548),
       .clr_tx_cnt (n_83), .rx_clk_en_o (rx_clk_en), .tx_clk_en_o
       (tx_clk_en));
  AO211HDV2 g12616__2883(.A1 (RXENn), .A2 (UMSEL), .B (tr_state), .C
       (TXENn), .Z (n_548));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[0] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[0]), .Q (FIFO_tx_inst_dout_sync[0]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[1] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[1]), .Q (FIFO_tx_inst_dout_sync[1]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[2] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[2]), .Q (FIFO_tx_inst_dout_sync[2]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[3] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[3]), .Q (FIFO_tx_inst_dout_sync[3]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[4] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[4]), .Q (FIFO_tx_inst_dout_sync[4]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[5] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[5]), .Q (FIFO_tx_inst_dout_sync[5]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[6] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[6]), .Q (FIFO_tx_inst_dout_sync[6]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[7] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[7]), .Q (FIFO_tx_inst_dout_sync[7]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[8] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[8]), .Q (FIFO_tx_inst_dout_sync[8]));
  DRQHDV0 \FIFO_tx_inst_dout_sync_reg[9] (.RD (n_0), .CK (cp2), .D
       (FIFO_tx_inst_fifo_buf[9]), .Q (FIFO_tx_inst_dout_sync[9]));
  DQNHDV2 XCK_int_reg(.CK (cp2), .D (XCKn_i), .QN (XCK_int));
  DSNQHDV0 \rx_sync_reg[2] (.SDN (ireset), .CK (cp2), .D (RxDn_i), .Q
       (rx_sync[2]));
  DQHDV0 tx_samp_delay_reg(.CK (cp2), .D (tx_samp), .Q (tx_samp_delay));
  AO221HDV0 g14034__2346(.A1 (n_484), .A2 (UBRRn[3]), .B1 (n_485), .B2
       (UBRRn[11]), .C (n_511), .Z (dbus_out[3]));
  AO221HDV0 g14035__1666(.A1 (n_582), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [0]), .B1 (n_485), .B2 (UBRRn[8]), .C (n_510), .Z (dbus_out[0]));
  CLKNAND2HDV2 g14036__7410(.A1 (n_509), .A2 (n_491), .ZN
       (dbus_out[7]));
  OAI211HDV2 g14037__6417(.A1 (n_487), .A2 (n_0), .B (n_506), .C
       (n_492), .ZN (dbus_out[4]));
  INAND4HDV2 g14038__5477(.A1 (n_580), .B1 (n_502), .B2 (n_494), .B3
       (n_493), .ZN (dbus_out[2]));
  NAND3HDV2 g14039__2398(.A1 (n_504), .A2 (n_499), .A3 (n_486), .ZN
       (dbus_out[1]));
  AO221HDV0 g14040__5107(.A1 (n_582), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [5]), .B1 (n_583), .B2 (UCSRnB[5]), .C (n_508), .Z
       (dbus_out[5]));
  AO221HDV0 g14041__6260(.A1 (n_479), .A2 (UCSRnA[3]), .B1 (n_583), .B2
       (TXENn), .C (n_507), .Z (n_511));
  AO221HDV0 g14042__4319(.A1 (n_479), .A2 (UCSRnA[0]), .B1 (n_484), .B2
       (UBRRn[0]), .C (n_505), .Z (n_510));
  AOI221HDVL g14043__8428(.A1 (n_484), .A2 (UBRRn[7]), .B1 (n_582), .B2
       (\FIFO_rx_inst_fifo_mem[0] [7]), .C (n_500), .ZN (n_509));
  NAND2HDV2 g14044__5526(.A1 (n_501), .A2 (n_488), .ZN (n_508));
  AO221HDV0 g14045__6783(.A1 (n_496), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [6]), .B1 (n_479), .B2 (UCSRnA[6]), .C (n_503), .Z
       (dbus_out[6]));
  AO222HDV1 g14046__3680(.A1 (n_582), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [3]), .B1 (n_496), .B2 (\FIFO_rx_inst_fifo_mem[1] [3]), .C1
       (n_477), .C2 (UCSRnC[3]), .Z (n_507));
  AOI222HDV2 g14047__1617(.A1 (n_582), .A2
       (\FIFO_rx_inst_fifo_mem[0] [4]), .B1 (n_496), .B2
       (\FIFO_rx_inst_fifo_mem[1] [4]), .C1 (n_484), .C2 (UBRRn[4]),
       .ZN (n_506));
  AO22HDV0 g14048__2802(.A1 (tx_samp), .A2 (tr_state), .B1 (UCSRnC[0]),
       .B2 (n_83), .Z (XCKn_o));
  AO222HDV1 g14049__1705(.A1 (n_583), .A2 (UCSRnB[0]), .B1 (n_496), .B2
       (\FIFO_rx_inst_fifo_mem[1] [0]), .C1 (n_477), .C2 (UCSRnC[0]),
       .Z (n_505));
  AOI221HDVL g14050__5122(.A1 (n_484), .A2 (UBRRn[1]), .B1 (n_496), .B2
       (\FIFO_rx_inst_fifo_mem[1] [1]), .C (n_490), .ZN (n_504));
  IOA21HDV1 g14052__8246(.A1 (n_582), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [6]), .B (n_498), .ZN (n_503));
  AOI22HDV1 g14053__7098(.A1 (n_582), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [2]), .B1 (n_496), .B2 (\FIFO_rx_inst_fifo_mem[1] [2]), .ZN
       (n_502));
  AOI22HDV1 g14054__6131(.A1 (n_496), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [5]), .B1 (n_477), .B2 (UCSRnC[5]), .ZN (n_501));
  AO32HDV2 g14055__1881(.A1 (n_479), .A2 (n_517), .A3 (ireset), .B1
       (n_496), .B2 (\FIFO_rx_inst_fifo_mem[1] [7]), .Z (n_500));
  NAND2HDV2 g14056__5115(.A1 (n_582), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [1]), .ZN (n_499));
  AOI222HDV2 g14057__7482(.A1 (n_484), .A2 (UBRRn[6]), .B1 (n_583), .B2
       (UCSRnB[6]), .C1 (n_477), .C2 (UMSEL), .ZN (n_498));
  OAI21HDV2 g14058__4733(.A1 (n_465), .A2 (n_513), .B (n_489), .ZN
       (tx_samp));
  AOI22HDV1 g14060__9315(.A1 (n_484), .A2 (UBRRn[2]), .B1 (n_485), .B2
       (UBRRn[10]), .ZN (n_494));
  AOI22HDV1 g14061__9945(.A1 (n_583), .A2 (UCSRnB[2]), .B1 (n_477), .B2
       (UCSRnC[2]), .ZN (n_493));
  NOR3HDV2 g14063__2346(.A1 (n_519), .A2 (n_468), .A3 (n_0), .ZN
       (n_496));
  AOI22HDV1 g14064__1666(.A1 (n_583), .A2 (RXENn), .B1 (n_477), .B2
       (UCSRnC[4]), .ZN (n_492));
  AOI22HDV1 g14065__7410(.A1 (n_583), .A2 (UCSRnB[7]), .B1 (n_477), .B2
       (UCSRnC[7]), .ZN (n_491));
  IOA22HDV0 g14066__6417(.A1 (n_485), .A2 (UBRRn[9]), .B1 (n_482), .B2
       (n_476), .ZN (n_490));
  IAO22HDV2 g14067__5477(.A1 (n_522), .A2 (XCK_int), .B1 (DDR_XCKn),
       .B2 (n_481), .ZN (n_489));
  AOI22HDV1 g14068__2398(.A1 (n_479), .A2 (n_461), .B1 (n_484), .B2
       (UBRRn[5]), .ZN (n_488));
  AND2HDV2RD g14069__5107(.A1 (n_484), .A2 (ramwe), .Z (n_565));
  NAND3BBHDV2 g14070__6260(.A1 (n_474), .A2 (rst_status), .B (n_479),
       .ZN (n_487));
  AOI22HDV1 g14071__4319(.A1 (n_479), .A2 (UCSRnA[1]), .B1 (n_477), .B2
       (UCSRnC[1]), .ZN (n_486));
  OAOI211HDV1 g14072__8428(.A1 (n_467), .A2 (ram_Addr[0]), .B (n_473),
       .C (n_455), .ZN (out_en));
  INOR2HDV2 g14073__5526(.A1 (ram_Addr[0]), .B1 (n_480), .ZN (n_485));
  NOR2HDV2 g14074__6783(.A1 (n_480), .A2 (ram_Addr[0]), .ZN (n_484));
  CLKINHDV1 g14075(.I (n_583), .ZN (n_482));
  AO32HDV2 g14076__3680(.A1 (n_466), .A2 (UMSEL), .A3 (UCSRnC[7]), .B1
       (n_462), .B2 (tx_baud_cnt[0]), .Z (n_481));
  NAND3BBHDV2 g14077__1617(.A1 (n_472), .A2 (ram_Addr[0]), .B
       (ram_Addr[2]), .ZN (n_519));
  INAND2HDV2 g14080__1705(.A1 (n_473), .B1 (ramwe), .ZN (n_521));
  INAND2HDV2 g14081__5122(.A1 (n_473), .B1 (ram_Addr[2]), .ZN (n_480));
  NOR2HDV2 g14082__8246(.A1 (n_473), .A2 (n_514), .ZN (n_479));
  AOI22HDV1 g14084__7098(.A1 (n_471), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [8]), .B1 (n_469), .B2 (\FIFO_rx_inst_fifo_mem[1] [8]), .ZN
       (n_476));
  AOI22HDV1 g14085__6131(.A1 (n_471), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [9]), .B1 (n_469), .B2 (\FIFO_rx_inst_fifo_mem[1] [9]), .ZN
       (n_475));
  AOI22HDV1 g14086__1881(.A1 (n_471), .A2
       (\FIFO_rx_inst_fifo_mem[0] [10]), .B1 (n_469), .B2
       (\FIFO_rx_inst_fifo_mem[1] [10]), .ZN (n_474));
  NOR2HDV2 g14087__5115(.A1 (n_472), .A2 (n_514), .ZN (n_477));
  OR2HDV2RD g14088__7482(.A1 (n_467), .A2 (ram_Addr[1]), .Z (n_473));
  AND3HDV2 g14089__4733(.A1 (n_517), .A2 (UCSRnB[7]), .A3 (ireset), .Z
       (RxcIRQ));
  INAND2HDV2 g14090__6161(.A1 (n_467), .B1 (ram_Addr[1]), .ZN (n_472));
  INHDV1 g14092(.I (n_468), .ZN (n_469));
  AOI21HDV2 g14093__9315(.A1 (FIFO_rx_inst_n_194), .A2 (n_457), .B
       (FIFO_rx_inst_r_pnt[0]), .ZN (n_471));
  IOA21HDV1 g14094__9945(.A1 (FIFO_rx_inst_n_194), .A2
       (FIFO_rx_inst_w_pnt[0]), .B (FIFO_rx_inst_r_pnt[0]), .ZN
       (n_468));
  IOA22HDV0 g14095__2883(.A1 (n_463), .A2 (UCSRnC[1]), .B1 (n_463), .B2
       (UCSRnC[1]), .ZN (n_466));
  NAND4HDV2 g14096__2346(.A1 (n_464), .A2 (n_459), .A3 (ram_Addr[7]),
       .A4 (ram_Addr[6]), .ZN (n_467));
  NAND2HDV2 g14097__1666(.A1 (n_520), .A2 (FIFO_rx_inst_n_194), .ZN
       (n_517));
  OAI211HDV2 g14098__7410(.A1 (UCSRnA[1]), .A2 (tx_baud_cnt[3]), .B
       (tx_clk_en), .C (n_460), .ZN (n_465));
  INOR4HDV2 g14099__6417(.A1 (n_458), .B1 (ram_Addr[3]), .B2
       (ram_Addr[4]), .B3 (ram_Addr[5]), .ZN (n_464));
  AND2HDV1RD g14100__5477(.A1 (UCSRnB[5]), .A2 (n_461), .Z (UdreIRQ));
  IOA21HDV0 g14101__2398(.A1 (tr_state), .A2 (tx_sh_reg[0]), .B
       (n_512), .ZN (TxDn_o));
  INAND2HDV2 g14102__5107(.A1 (n_516), .B1 (tx_baud_cnt[2]), .ZN
       (n_513));
  IOA22HDV0 g14103__6260(.A1 (FIFO_rx_inst_r_pnt[0]), .A2
       (FIFO_rx_inst_w_pnt[0]), .B1 (FIFO_rx_inst_r_pnt[0]), .B2
       (FIFO_rx_inst_w_pnt[0]), .ZN (n_520));
  IOA22HDV0 g14104__4319(.A1 (UCSRnC[0]), .A2 (tx_baud_cnt[0]), .B1
       (UCSRnC[0]), .B2 (tx_baud_cnt[0]), .ZN (n_463));
  IOA22HDV0 g14105__8428(.A1 (FIFO_rx_inst_r_pnt[1]), .A2
       (FIFO_rx_inst_w_pnt[1]), .B1 (FIFO_rx_inst_w_pnt[1]), .B2
       (FIFO_rx_inst_r_pnt[1]), .ZN (FIFO_rx_inst_n_194));
  INHDV1 g14117(.I (n_462), .ZN (n_515));
  INHDV2 g14118(.I (n_460), .ZN (n_518));
  NOR2HDV2 g14119__5526(.A1 (ram_Addr[9]), .A2 (ram_Addr[8]), .ZN
       (n_459));
  NOR2HDV2 g14120__6783(.A1 (ram_Addr[11]), .A2 (ram_Addr[10]), .ZN
       (n_458));
  AND2HDV1RD g14121__3680(.A1 (UCSRnB[6]), .A2 (UCSRnA[6]), .Z
       (TxcIRQ));
  INOR2HDV2 g14123__1617(.A1 (UMSEL), .B1 (UCSRnC[7]), .ZN (n_462));
  NAND2HDV2 g14124__2802(.A1 (tx_fifo_full), .A2 (ireset), .ZN (n_461));
  NAND2HDV2 g14125__1705(.A1 (tx_baud_cnt[0]), .A2 (tx_baud_cnt[1]),
       .ZN (n_516));
  INAND2HDV2 g14126__5122(.A1 (DDR_XCKn), .B1 (UMSEL), .ZN (n_522));
  NAND2HDV1 g14127__8246(.A1 (TXENn), .A2 (n_83), .ZN (n_512));
  NOR2HDV2 g14128__7098(.A1 (UMSEL), .A2 (UCSRnC[7]), .ZN (n_460));
  OR2HDV2RD g14129__6131(.A1 (ram_Addr[2]), .A2 (ram_Addr[0]), .Z
       (n_514));
  CLKINHDV1 g14130(.I (FIFO_rx_inst_w_pnt[0]), .ZN (n_457));
  INHDV2 g14133(.I (ramre), .ZN (n_455));
  INHDV2 g14134(.I (ireset), .ZN (n_0));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][0] (.RD (n_0), .CK (cp2), .D
       (n_376), .Q (\FIFO_rx_inst_fifo_mem[0] [0]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][1] (.RD (n_0), .CK (cp2), .D
       (n_375), .Q (\FIFO_rx_inst_fifo_mem[0] [1]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][2] (.RD (n_0), .CK (cp2), .D
       (n_374), .Q (\FIFO_rx_inst_fifo_mem[0] [2]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][3] (.RD (n_0), .CK (cp2), .D
       (n_407), .Q (\FIFO_rx_inst_fifo_mem[0] [3]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][4] (.RD (n_0), .CK (cp2), .D
       (n_373), .Q (\FIFO_rx_inst_fifo_mem[0] [4]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][5] (.RD (n_0), .CK (cp2), .D
       (n_350), .Q (\FIFO_rx_inst_fifo_mem[0] [5]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][6] (.RD (n_0), .CK (cp2), .D
       (n_347), .Q (\FIFO_rx_inst_fifo_mem[0] [6]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][7] (.RD (n_0), .CK (cp2), .D
       (n_346), .Q (\FIFO_rx_inst_fifo_mem[0] [7]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][8] (.RD (n_0), .CK (cp2), .D
       (n_345), .Q (\FIFO_rx_inst_fifo_mem[0] [8]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][9] (.RD (n_0), .CK (cp2), .D
       (n_432), .Q (\FIFO_rx_inst_fifo_mem[0] [9]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[0][10] (.RD (n_0), .CK (cp2), .D
       (n_383), .Q (\FIFO_rx_inst_fifo_mem[0] [10]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][0] (.RD (n_0), .CK (cp2), .D
       (n_372), .Q (\FIFO_rx_inst_fifo_mem[1] [0]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][1] (.RD (n_0), .CK (cp2), .D
       (n_377), .Q (\FIFO_rx_inst_fifo_mem[1] [1]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][2] (.RD (n_0), .CK (cp2), .D
       (n_380), .Q (\FIFO_rx_inst_fifo_mem[1] [2]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][3] (.RD (n_0), .CK (cp2), .D
       (n_408), .Q (\FIFO_rx_inst_fifo_mem[1] [3]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][4] (.RD (n_0), .CK (cp2), .D
       (n_386), .Q (\FIFO_rx_inst_fifo_mem[1] [4]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][5] (.RD (n_0), .CK (cp2), .D
       (n_351), .Q (\FIFO_rx_inst_fifo_mem[1] [5]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][6] (.RD (n_0), .CK (cp2), .D
       (n_348), .Q (\FIFO_rx_inst_fifo_mem[1] [6]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][7] (.RD (n_0), .CK (cp2), .D
       (n_357), .Q (\FIFO_rx_inst_fifo_mem[1] [7]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][8] (.RD (n_0), .CK (cp2), .D
       (n_349), .Q (\FIFO_rx_inst_fifo_mem[1] [8]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][9] (.RD (n_0), .CK (cp2), .D
       (n_433), .Q (\FIFO_rx_inst_fifo_mem[1] [9]));
  DRQHDV2 \FIFO_rx_inst_fifo_mem_reg[1][10] (.RD (n_0), .CK (cp2), .D
       (n_381), .Q (\FIFO_rx_inst_fifo_mem[1] [10]));
  DRQHDV2 \FIFO_rx_inst_r_pnt_reg[0] (.RD (n_0), .CK (cp2), .D (n_278),
       .Q (FIFO_rx_inst_r_pnt[0]));
  DRQHDV2 \FIFO_rx_inst_r_pnt_reg[1] (.RD (n_0), .CK (cp2), .D (n_277),
       .Q (FIFO_rx_inst_r_pnt[1]));
  DRQHDV2 \FIFO_rx_inst_w_pnt_reg[0] (.RD (n_0), .CK (cp2), .D (n_316),
       .Q (FIFO_rx_inst_w_pnt[0]));
  DRQHDV2 \FIFO_rx_inst_w_pnt_reg[1] (.RD (n_0), .CK (cp2), .D (n_305),
       .Q (FIFO_rx_inst_w_pnt[1]));
  DSNQHDV2 FIFO_tx_inst_empty_int_sync_reg(.SDN (ireset), .CK (cp2), .D
       (n_189), .Q (tx_fifo_empty));
  DRQHDV2 \FIFO_tx_inst_fifo_buf_reg[0] (.RD (n_0), .CK (cp2), .D
       (n_286), .Q (FIFO_tx_inst_fifo_buf[0]));
  DRQHDV2 \FIFO_tx_inst_fifo_buf_reg[1] (.RD (n_0), .CK (cp2), .D
       (n_285), .Q (FIFO_tx_inst_fifo_buf[1]));
  EDRNQHDV0 \FIFO_tx_inst_fifo_buf_reg[2] (.RDN (ireset), .CK (cp2), .D
       (n_252), .E (n_217), .Q (FIFO_tx_inst_fifo_buf[2]));
  DRQHDV2 \FIFO_tx_inst_fifo_buf_reg[3] (.RD (n_0), .CK (cp2), .D
       (n_284), .Q (FIFO_tx_inst_fifo_buf[3]));
  DRQHDV2 \FIFO_tx_inst_fifo_buf_reg[4] (.RD (n_0), .CK (cp2), .D
       (n_294), .Q (FIFO_tx_inst_fifo_buf[4]));
  EDRNQHDV0 \FIFO_tx_inst_fifo_buf_reg[5] (.RDN (ireset), .CK (cp2), .D
       (n_425), .E (n_217), .Q (FIFO_tx_inst_fifo_buf[5]));
  EDRNQHDV0 \FIFO_tx_inst_fifo_buf_reg[6] (.RDN (ireset), .CK (cp2), .D
       (n_437), .E (n_217), .Q (FIFO_tx_inst_fifo_buf[6]));
  EDRNQHDV0 \FIFO_tx_inst_fifo_buf_reg[7] (.RDN (ireset), .CK (cp2), .D
       (n_444), .E (n_217), .Q (FIFO_tx_inst_fifo_buf[7]));
  EDRNQHDV0 \FIFO_tx_inst_fifo_buf_reg[8] (.RDN (ireset), .CK (cp2), .D
       (n_448), .E (n_217), .Q (FIFO_tx_inst_fifo_buf[8]));
  EDRNQHDV0 \FIFO_tx_inst_fifo_buf_reg[9] (.RDN (ireset), .CK (cp2), .D
       (n_450), .E (n_217), .Q (FIFO_tx_inst_fifo_buf[9]));
  DRQHDV2 FIFO_tx_inst_full_int_sync_reg(.RD (n_0), .CK (cp2), .D
       (n_188), .Q (tx_fifo_full));
  DRQNHDV2 \FIFO_tx_inst_r_pnt_reg[0] (.RD (n_0), .CK (cp2), .D
       (n_270), .QN (FIFO_tx_inst_r_pnt[0]));
  DRQNHDV2 \FIFO_tx_inst_r_pnt_reg[1] (.RD (n_0), .CK (cp2), .D
       (n_269), .QN (FIFO_tx_inst_r_pnt[1]));
  DRQNHDV2 \FIFO_tx_inst_w_pnt_reg[0] (.RD (n_0), .CK (cp2), .D
       (n_265), .QN (FIFO_tx_inst_w_pnt[0]));
  DRQNHDV2 \FIFO_tx_inst_w_pnt_reg[1] (.RD (n_0), .CK (cp2), .D
       (n_262), .QN (FIFO_tx_inst_w_pnt[1]));
  EDRNQHDV0 \Temp_reg[0] (.RDN (ireset), .CK (cp2), .D (dbus_in[0]), .E
       (n_167), .Q (Temp[0]));
  EDRNQHDV0 \Temp_reg[1] (.RDN (ireset), .CK (cp2), .D (dbus_in[1]), .E
       (n_167), .Q (Temp[1]));
  EDRNQHDV0 \Temp_reg[2] (.RDN (ireset), .CK (cp2), .D (dbus_in[2]), .E
       (n_167), .Q (Temp[2]));
  EDRNQHDV0 \Temp_reg[3] (.RDN (ireset), .CK (cp2), .D (dbus_in[3]), .E
       (n_167), .Q (Temp[3]));
  EDRNQHDV0 \UBRRn_reg[0] (.RDN (ireset), .CK (cp2), .D (dbus_in[0]),
       .E (n_565), .Q (UBRRn[0]));
  EDRNQHDV0 \UBRRn_reg[1] (.RDN (ireset), .CK (cp2), .D (dbus_in[1]),
       .E (n_565), .Q (UBRRn[1]));
  EDRNQHDV0 \UBRRn_reg[2] (.RDN (ireset), .CK (cp2), .D (dbus_in[2]),
       .E (n_565), .Q (UBRRn[2]));
  EDRNQHDV0 \UBRRn_reg[3] (.RDN (ireset), .CK (cp2), .D (dbus_in[3]),
       .E (n_565), .Q (UBRRn[3]));
  EDRNQHDV0 \UBRRn_reg[4] (.RDN (ireset), .CK (cp2), .D (dbus_in[4]),
       .E (n_565), .Q (UBRRn[4]));
  EDRNQHDV0 \UBRRn_reg[5] (.RDN (ireset), .CK (cp2), .D (dbus_in[5]),
       .E (n_565), .Q (UBRRn[5]));
  EDRNQHDV0 \UBRRn_reg[6] (.RDN (ireset), .CK (cp2), .D (dbus_in[6]),
       .E (n_565), .Q (UBRRn[6]));
  EDRNQHDV0 \UBRRn_reg[7] (.RDN (ireset), .CK (cp2), .D (dbus_in[7]),
       .E (n_565), .Q (UBRRn[7]));
  EDRNQHDV0 \UBRRn_reg[8] (.RDN (ireset), .CK (cp2), .D (Temp[0]), .E
       (n_565), .Q (UBRRn[8]));
  EDRNQHDV0 \UBRRn_reg[9] (.RDN (ireset), .CK (cp2), .D (Temp[1]), .E
       (n_565), .Q (UBRRn[9]));
  EDRNQHDV0 \UBRRn_reg[10] (.RDN (ireset), .CK (cp2), .D (Temp[2]), .E
       (n_565), .Q (UBRRn[10]));
  EDRNQHDV0 \UBRRn_reg[11] (.RDN (ireset), .CK (cp2), .D (Temp[3]), .E
       (n_565), .Q (UBRRn[11]));
  EDRNQHDV0 \UCSRnA_reg[0] (.RDN (ireset), .CK (cp2), .D (dbus_in[0]),
       .E (n_132), .Q (UCSRnA[0]));
  EDRNQHDV0 \UCSRnA_reg[1] (.RDN (ireset), .CK (cp2), .D (dbus_in[1]),
       .E (n_132), .Q (UCSRnA[1]));
  DRQHDV2 \UCSRnA_reg[3] (.RD (n_0), .CK (cp2), .D (n_379), .Q
       (UCSRnA[3]));
  DRQHDV2 \UCSRnA_reg[6] (.RD (n_0), .CK (cp2), .D (n_399), .Q
       (UCSRnA[6]));
  EDRNQHDV0 \UCSRnB_reg[0] (.RDN (ireset), .CK (cp2), .D (dbus_in[0]),
       .E (n_162), .Q (UCSRnB[0]));
  DRQHDV2 \UCSRnB_reg[2] (.RD (n_0), .CK (cp2), .D (n_212), .Q
       (UCSRnB[2]));
  EDRNQHDV0 \UCSRnB_reg[3] (.RDN (ireset), .CK (cp2), .D (dbus_in[3]),
       .E (n_162), .Q (TXENn));
  EDRNQHDV0 \UCSRnB_reg[4] (.RDN (ireset), .CK (cp2), .D (dbus_in[4]),
       .E (n_162), .Q (RXENn));
  EDRNQHDV0 \UCSRnB_reg[5] (.RDN (ireset), .CK (cp2), .D (dbus_in[5]),
       .E (n_162), .Q (UCSRnB[5]));
  EDRNQHDV0 \UCSRnB_reg[6] (.RDN (ireset), .CK (cp2), .D (dbus_in[6]),
       .E (n_162), .Q (UCSRnB[6]));
  EDRNQHDV0 \UCSRnB_reg[7] (.RDN (ireset), .CK (cp2), .D (dbus_in[7]),
       .E (n_162), .Q (UCSRnB[7]));
  EDRNQHDV0 \UCSRnC_reg[0] (.RDN (ireset), .CK (cp2), .D (dbus_in[0]),
       .E (n_581), .Q (UCSRnC[0]));
  DSNQHDV2 \UCSRnC_reg[1] (.SDN (ireset), .CK (cp2), .D (n_181), .Q
       (UCSRnC[1]));
  DSNQNHDV2 \UCSRnC_reg[2] (.SDN (ireset), .CK (cp2), .D (n_183), .QN
       (n_1));
  EDRNQHDV0 \UCSRnC_reg[3] (.RDN (ireset), .CK (cp2), .D (dbus_in[3]),
       .E (n_581), .Q (UCSRnC[3]));
  EDRNQHDV0 \UCSRnC_reg[4] (.RDN (ireset), .CK (cp2), .D (dbus_in[4]),
       .E (n_581), .Q (UCSRnC[4]));
  DRQNHDV2 \UCSRnC_reg[5] (.RD (n_0), .CK (cp2), .D (n_185), .QN
       (n_61));
  EDRNQHDV0 \UCSRnC_reg[6] (.RDN (ireset), .CK (cp2), .D (dbus_in[6]),
       .E (n_581), .Q (UMSEL));
  EDRNQNHDV4 \UCSRnC_reg[7] (.RDN (ireset), .CK (cp2), .D (dbus_in[7]),
       .E (n_581), .QN (n_42));
  DRQNHDV2 rc_done_reg(.RD (n_0), .CK (cp2), .D (n_245), .QN (rc_done));
  DRQNHDV2 \rc_state_reg[0] (.RD (n_0), .CK (cp2), .D (n_364), .QN
       (rc_state[0]));
  DRQNHDV2 \rc_state_reg[1] (.RD (n_0), .CK (cp2), .D (n_400), .QN
       (rc_state[1]));
  EDQHDV2 rst_status_reg(.CK (cp2), .D (n_132), .E (ireset), .Q
       (rst_status));
  DRQHDV2 \rx_baud_cnt_reg[0] (.RD (n_0), .CK (cp2), .D (n_179), .Q
       (rx_baud_cnt[0]));
  DRQNHDV2 \rx_baud_cnt_reg[1] (.RD (n_0), .CK (cp2), .D (n_276), .QN
       (rx_baud_cnt[1]));
  DRQNHDV2 \rx_baud_cnt_reg[2] (.RD (n_0), .CK (cp2), .D (n_317), .QN
       (rx_baud_cnt[2]));
  DRQNHDV2 \rx_baud_cnt_reg[3] (.RD (n_0), .CK (cp2), .D (n_366), .QN
       (rx_baud_cnt[3]));
  DQNHDV2 \rx_bitcnt_reg[0] (.CK (cp2), .D (n_426), .QN (rx_bitcnt[0]));
  DQNHDV2 \rx_bitcnt_reg[1] (.CK (cp2), .D (n_431), .QN (rx_bitcnt[1]));
  DQNHDV2 \rx_bitcnt_reg[2] (.CK (cp2), .D (n_439), .QN (rx_bitcnt[2]));
  DQNHDV2 \rx_bitcnt_reg[3] (.CK (cp2), .D (n_442), .QN (rx_bitcnt[3]));
  EDRNQHDV0 \rx_sh_reg_reg[0] (.RDN (ireset), .CK (cp2), .D
       (rx_sh_reg[1]), .E (n_410), .Q (rx_sh_reg[0]));
  EDRNQHDV0 \rx_sh_reg_reg[1] (.RDN (ireset), .CK (cp2), .D
       (rx_sh_reg[2]), .E (n_410), .Q (rx_sh_reg[1]));
  EDRNQHDV0 \rx_sh_reg_reg[2] (.RDN (ireset), .CK (cp2), .D (n_107), .E
       (n_410), .Q (rx_sh_reg[2]));
  EDRNQNHDV4 \rx_sh_reg_reg[3] (.RDN (ireset), .CK (cp2), .D (n_103),
       .E (n_410), .QN (rx_sh_reg[3]));
  EDRNQNHDV4 \rx_sh_reg_reg[4] (.RDN (ireset), .CK (cp2), .D (n_106),
       .E (n_410), .QN (rx_sh_reg[4]));
  EDRNQNHDV4 \rx_sh_reg_reg[5] (.RDN (ireset), .CK (cp2), .D (n_18), .E
       (n_410), .QN (rx_sh_reg[5]));
  EDRNQNHDV4 \rx_sh_reg_reg[6] (.RDN (ireset), .CK (cp2), .D
       (rx_sh_reg[7]), .E (n_410), .QN (rx_sh_reg[6]));
  EDRNQHDV0 \rx_sh_reg_reg[7] (.RDN (ireset), .CK (cp2), .D (n_17), .E
       (n_410), .Q (rx_sh_reg[7]));
  DRQNHDV2 \rx_sh_reg_reg[8] (.RD (n_0), .CK (cp2), .D (n_577), .QN
       (rx_sh_reg[8]));
  EDRNQNHDV4 \rx_sh_reg_reg[9] (.RDN (ireset), .CK (cp2), .D (n_108),
       .E (n_410), .QN (rx_sh_reg[9]));
  EDRNQNHDV4 \rx_sh_reg_reg[10] (.RDN (ireset), .CK (cp2), .D (n_244),
       .E (n_410), .QN (rx_sh_reg[10]));
  DSNQHDV2 \rx_sync_reg[0] (.SDN (ireset), .CK (cp2), .D (n_153), .Q
       (rx_sync[0]));
  DSNQHDV2 \rx_sync_reg[1] (.SDN (ireset), .CK (cp2), .D (n_149), .Q
       (rx_sync[1]));
  DRQNHDV2 tr_done_reg(.RD (n_0), .CK (cp2), .D (n_344), .QN (tr_done));
  DRQHDV2 tr_state_reg(.RD (n_0), .CK (cp2), .D (n_402), .Q (tr_state));
  DRQHDV2 \tx_baud_cnt_reg[0] (.RD (n_0), .CK (cp2), .D (n_184), .Q
       (tx_baud_cnt[0]));
  DRQHDV2 \tx_baud_cnt_reg[1] (.RD (n_0), .CK (cp2), .D (n_241), .Q
       (tx_baud_cnt[1]));
  DRQHDV2 \tx_baud_cnt_reg[2] (.RD (n_0), .CK (cp2), .D (n_257), .Q
       (tx_baud_cnt[2]));
  DRQHDV2 \tx_baud_cnt_reg[3] (.RD (n_0), .CK (cp2), .D (n_258), .Q
       (tx_baud_cnt[3]));
  DQNHDV2 \tx_bitcnt_reg[0] (.CK (cp2), .D (n_385), .QN (tx_bitcnt[0]));
  DQNHDV2 \tx_bitcnt_reg[1] (.CK (cp2), .D (n_401), .QN (tx_bitcnt[1]));
  DQNHDV2 \tx_bitcnt_reg[2] (.CK (cp2), .D (n_420), .QN (tx_bitcnt[2]));
  DQNHDV2 \tx_bitcnt_reg[3] (.CK (cp2), .D (n_421), .QN (tx_bitcnt[3]));
  DSNQHDV2 \tx_sh_reg_reg[0] (.SDN (ireset), .CK (cp2), .D (n_382), .Q
       (tx_sh_reg[0]));
  DSNQHDV2 \tx_sh_reg_reg[1] (.SDN (ireset), .CK (cp2), .D (n_396), .Q
       (tx_sh_reg[1]));
  DSNQHDV2 \tx_sh_reg_reg[2] (.SDN (ireset), .CK (cp2), .D (n_395), .Q
       (tx_sh_reg[2]));
  DSNQHDV2 \tx_sh_reg_reg[3] (.SDN (ireset), .CK (cp2), .D (n_394), .Q
       (tx_sh_reg[3]));
  DSNQHDV2 \tx_sh_reg_reg[4] (.SDN (ireset), .CK (cp2), .D (n_397), .Q
       (tx_sh_reg[4]));
  DSNQHDV2 \tx_sh_reg_reg[5] (.SDN (ireset), .CK (cp2), .D (n_392), .Q
       (tx_sh_reg[5]));
  DSNQHDV2 \tx_sh_reg_reg[6] (.SDN (ireset), .CK (cp2), .D (n_391), .Q
       (tx_sh_reg[6]));
  DSNQHDV2 \tx_sh_reg_reg[7] (.SDN (ireset), .CK (cp2), .D (n_390), .Q
       (tx_sh_reg[7]));
  DSNQHDV2 \tx_sh_reg_reg[8] (.SDN (ireset), .CK (cp2), .D (n_393), .Q
       (tx_sh_reg[8]));
  DSNQHDV2 \tx_sh_reg_reg[9] (.SDN (ireset), .CK (cp2), .D (n_378), .Q
       (tx_sh_reg[9]));
  DSNQHDV2 \tx_sh_reg_reg[10] (.SDN (ireset), .CK (cp2), .D (n_384), .Q
       (tx_sh_reg[10]));
  NAND3HDV2 g17511__1881(.A1 (n_449), .A2 (n_522), .A3 (n_233), .ZN
       (n_450));
  XNOR2CHDV2 g17513__5115(.A1 (n_448), .A2 (n_575), .ZN (n_449));
  NAND2HDV2 g17514__7482(.A1 (n_447), .A2 (n_522), .ZN (n_448));
  AOI211HDV2 g17515__4733(.A1 (UCSRnB[2]), .A2 (UCSRnB[0]), .B (n_170),
       .C (n_446), .ZN (n_447));
  IAO21HDV2 g17516__6161(.A1 (n_575), .A2 (n_61), .B (UCSRnB[2]), .ZN
       (n_446));
  INAND3HDV2 g17519__9945(.A1 (n_259), .B1 (n_443), .B2 (n_266), .ZN
       (n_444));
  AOI22HDV1 g17521__2883(.A1 (n_576), .A2 (n_198), .B1 (n_191), .B2
       (dbus_in[7]), .ZN (n_443));
  OAI22HDV0 g17523__2346(.A1 (n_438), .A2 (n_121), .B1 (n_260), .B2
       (n_120), .ZN (n_442));
  OAI21HDV2 g17527__7410(.A1 (n_436), .A2 (n_121), .B (n_238), .ZN
       (n_439));
  OA22HDV2 g17528__6417(.A1 (n_403), .A2 (n_192), .B1 (n_435), .B2
       (rx_bitcnt[3]), .Z (n_438));
  NAND2HDV2 g17531__5477(.A1 (n_434), .A2 (n_271), .ZN (n_437));
  ADH1HDV2C g17532__2398(.A (n_423), .B (rx_bitcnt[2]), .CO (n_435), .S
       (n_436));
  AOI22HDV1 g17533__5107(.A1 (n_428), .A2 (n_259), .B1 (n_522), .B2
       (n_260), .ZN (n_434));
  IOA22HDV0 g17535__6260(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [9]), .B1 (n_332), .B2 (n_430), .ZN (n_433));
  IOA22HDV0 g17536__4319(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [9]), .B1 (n_330), .B2 (n_430), .ZN (n_432));
  AOAI211HDV1 g17538__8428(.A1 (n_238), .A2 (n_182), .B (n_171), .C
       (n_427), .ZN (n_431));
  NAND3BBHDV2 g17539__5526(.A1 (n_424), .A2 (UCSRnC[7]), .B
       (UCSRnC[5]), .ZN (n_430));
  AOAI211HDV1 g17542__6783(.A1 (n_411), .A2 (n_115), .B (n_423), .C
       (n_120), .ZN (n_427));
  IOA22HDV0 g17543__3680(.A1 (n_425), .A2 (n_416), .B1 (n_425), .B2
       (n_416), .ZN (n_428));
  OAI211HDV2 g17544__1617(.A1 (n_232), .A2 (n_120), .B (n_422), .C
       (n_242), .ZN (n_426));
  OAI211HDV2 g17545__2802(.A1 (n_416), .A2 (n_239), .B (n_289), .C
       (n_273), .ZN (n_425));
  IOA22HDV0 g17546__1705(.A1 (n_419), .A2 (n_417), .B1 (n_419), .B2
       (n_417), .ZN (n_424));
  IOA21HDV1 g17554__5122(.A1 (n_411), .A2 (n_414), .B (n_120), .ZN
       (n_422));
  NOR2HDV2 g17556__8246(.A1 (n_411), .A2 (n_115), .ZN (n_423));
  OAI211HDV2 g17562__7098(.A1 (n_42), .A2 (tr_state), .B (n_415), .C
       (n_341), .ZN (n_421));
  OAI222HDV1 g17563__6131(.A1 (tx_bitcnt[2]), .A2 (n_325), .B1 (n_406),
       .B2 (n_226), .C1 (n_328), .C2 (n_240), .ZN (n_420));
  IOA22HDV0 g17565__5115(.A1 (n_413), .A2 (n_412), .B1 (n_413), .B2
       (n_412), .ZN (n_419));
  OA22HDV2 g17568__7482(.A1 (n_325), .A2 (tx_bitcnt[3]), .B1 (n_405),
       .B2 (n_226), .Z (n_415));
  IOA22HDV0 g17569__4733(.A1 (n_404), .A2 (n_388), .B1 (n_404), .B2
       (n_388), .ZN (n_417));
  XNOR2CHDV2 g17570__6161(.A1 (n_398), .A2 (UCSRnC[4]), .ZN (n_416));
  INAND2HDV2 g17571__9315(.A1 (rx_bitcnt[0]), .B1 (n_403), .ZN (n_414));
  IOA22HDV0 g17577__9945(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [3]), .B1 (n_332), .B2 (n_388), .ZN (n_408));
  IOA22HDV0 g17578__2883(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [3]), .B1 (n_330), .B2 (n_388), .ZN (n_407));
  XNOR2CHDV2 g17579__2346(.A1 (n_371), .A2 (n_342), .ZN (n_413));
  IOA22HDV0 g17580__1666(.A1 (n_389), .A2 (n_338), .B1 (n_389), .B2
       (n_338), .ZN (n_412));
  INAND2HDV2 g17581__7410(.A1 (n_403), .B1 (rx_bitcnt[0]), .ZN (n_411));
  NOR2HDV2 g17582__6417(.A1 (n_403), .A2 (n_121), .ZN (n_410));
  ADH1HDV2C g17583__5477(.A (n_311), .B (n_159), .CO (n_405), .S
       (n_406));
  IOA22HDV0 g17599__2398(.A1 (n_368), .A2 (n_83), .B1 (n_368), .B2
       (n_83), .ZN (n_402));
  OAI222HDV1 g17600__5107(.A1 (tx_bitcnt[1]), .A2 (n_325), .B1 (n_315),
       .B2 (n_226), .C1 (n_328), .C2 (n_160), .ZN (n_401));
  OAI21HDV2 g17601__6260(.A1 (n_177), .A2 (n_42), .B (n_387), .ZN
       (n_400));
  IOA22HDV0 g17602__4319(.A1 (n_369), .A2 (UCSRnA[6]), .B1 (n_369), .B2
       (UCSRnA[6]), .ZN (n_399));
  IOA22HDV0 g17609__8428(.A1 (n_370), .A2 (n_255), .B1 (n_370), .B2
       (n_255), .ZN (n_398));
  IOA22HDV0 g17610__5526(.A1 (n_358), .A2 (n_337), .B1 (n_358), .B2
       (n_337), .ZN (n_404));
  OAI211HDV2 g17612__6783(.A1 (n_335), .A2 (UCSRnC[7]), .B (n_297), .C
       (n_156), .ZN (n_403));
  CLKNAND2HDV2 g17614__3680(.A1 (n_363), .A2 (n_206), .ZN (n_397));
  CLKNAND2HDV2 g17615__1617(.A1 (n_360), .A2 (n_205), .ZN (n_396));
  CLKNAND2HDV2 g17616__2802(.A1 (n_359), .A2 (n_211), .ZN (n_395));
  CLKNAND2HDV2 g17617__1705(.A1 (n_361), .A2 (n_203), .ZN (n_394));
  CLKNAND2HDV2 g17618__5122(.A1 (n_355), .A2 (n_202), .ZN (n_393));
  CLKNAND2HDV2 g17619__8246(.A1 (n_367), .A2 (n_204), .ZN (n_392));
  CLKNAND2HDV2 g17620__7098(.A1 (n_352), .A2 (n_201), .ZN (n_391));
  CLKNAND2HDV2 g17621__6131(.A1 (n_356), .A2 (n_216), .ZN (n_390));
  AOI33HDV2 g17632__1881(.A1 (n_321), .A2 (n_190), .A3 (n_135), .B1
       (n_220), .B2 (n_192), .B3 (n_120), .ZN (n_387));
  IOA22HDV0 g17633__5115(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [4]), .B1 (n_332), .B2 (n_337), .ZN (n_386));
  OAI21HDV2 g17634__7482(.A1 (n_325), .A2 (tx_bitcnt[0]), .B (n_362),
       .ZN (n_385));
  OAI21HDV2 g17635__4733(.A1 (n_326), .A2 (n_138), .B (n_353), .ZN
       (n_384));
  AO32HDV2 g17636__6161(.A1 (n_329), .A2 (n_42), .A3 (rx_sh_reg[10]),
       .B1 (n_334), .B2 (\FIFO_rx_inst_fifo_mem[0] [10]), .Z (n_383));
  AO222HDV1 g17637__9315(.A1 (n_326), .A2 (tx_sh_reg[0]), .B1 (n_327),
       .B2 (tx_sh_reg[1]), .C1 (n_165), .C2
       (FIFO_tx_inst_dout_sync[0]), .Z (n_382));
  AO32HDV2 g17638__9945(.A1 (n_331), .A2 (n_42), .A3 (rx_sh_reg[10]),
       .B1 (n_584), .B2 (\FIFO_rx_inst_fifo_mem[1] [10]), .Z (n_381));
  IOA22HDV0 g17639__2883(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [2]), .B1 (n_332), .B2 (n_336), .ZN (n_380));
  IOA22HDV0 g17640__2346(.A1 (n_339), .A2 (UCSRnA[3]), .B1 (n_339), .B2
       (UCSRnA[3]), .ZN (n_379));
  CLKNAND2HDV2 g17641__1666(.A1 (n_354), .A2 (n_200), .ZN (n_378));
  IOA22HDV0 g17642__7410(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [1]), .B1 (n_332), .B2 (n_338), .ZN (n_377));
  IOA22HDV0 g17643__6417(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [0]), .B1 (n_330), .B2 (n_342), .ZN (n_376));
  IOA22HDV0 g17644__5477(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [1]), .B1 (n_330), .B2 (n_338), .ZN (n_375));
  IOA22HDV0 g17645__2398(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [2]), .B1 (n_330), .B2 (n_336), .ZN (n_374));
  IOA22HDV0 g17646__5107(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [4]), .B1 (n_330), .B2 (n_337), .ZN (n_373));
  IOA22HDV0 g17647__6260(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [0]), .B1 (n_332), .B2 (n_342), .ZN (n_372));
  IOA22HDV0 g17648__4319(.A1 (n_340), .A2 (n_274), .B1 (n_340), .B2
       (n_274), .ZN (n_371));
  IOA22HDV0 g17649__8428(.A1 (n_336), .A2 (UCSRnC[4]), .B1 (n_336), .B2
       (UCSRnC[4]), .ZN (n_389));
  AOI221HDVL g17650__5526(.A1 (n_221), .A2 (n_106), .B1 (n_233), .B2
       (n_107), .C (n_365), .ZN (n_388));
  AOI22HDV1 g17652__6783(.A1 (n_327), .A2 (tx_sh_reg[6]), .B1 (n_326),
       .B2 (tx_sh_reg[5]), .ZN (n_367));
  OAOI211HDV1 g17653__3680(.A1 (rx_clk_en), .A2 (rx_baud_cnt[3]), .B
       (n_324), .C (n_124), .ZN (n_366));
  OAI211HDV2 g17654__1617(.A1 (n_249), .A2 (rx_sh_reg[6]), .B (n_585),
       .C (n_290), .ZN (n_365));
  OAI32HDV0 g17655__2802(.A1 (n_161), .A2 (UCSRnC[7]), .A3
       (rx_sync[1]), .B1 (n_321), .B2 (n_136), .ZN (n_364));
  AOI22HDV1 g17656__1705(.A1 (n_327), .A2 (tx_sh_reg[5]), .B1 (n_326),
       .B2 (tx_sh_reg[4]), .ZN (n_363));
  AOI22HDV1 g17657__5122(.A1 (n_301), .A2 (n_225), .B1 (n_327), .B2
       (tx_bitcnt[0]), .ZN (n_362));
  AOI22HDV1 g17658__8246(.A1 (n_327), .A2 (tx_sh_reg[4]), .B1 (n_326),
       .B2 (tx_sh_reg[3]), .ZN (n_361));
  AOI22HDV1 g17659__7098(.A1 (n_327), .A2 (tx_sh_reg[2]), .B1 (n_326),
       .B2 (tx_sh_reg[1]), .ZN (n_360));
  AOI22HDV1 g17660__6131(.A1 (n_327), .A2 (tx_sh_reg[3]), .B1 (n_326),
       .B2 (tx_sh_reg[2]), .ZN (n_359));
  IOA22HDV0 g17661__1881(.A1 (n_322), .A2 (n_254), .B1 (n_322), .B2
       (n_254), .ZN (n_370));
  MUX2NHDV1 g17662__5115(.I0 (n_302), .I1 (n_209), .S (UCSRnA[6]), .ZN
       (n_369));
  INAND2HDV2 g17663__7482(.A1 (n_141), .B1 (n_343), .ZN (n_368));
  IOA22HDV0 g17664__4733(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [7]), .B1 (n_332), .B2 (n_309), .ZN (n_357));
  AOI22HDV1 g17665__6161(.A1 (n_327), .A2 (tx_sh_reg[8]), .B1 (n_326),
       .B2 (tx_sh_reg[7]), .ZN (n_356));
  AOI22HDV1 g17666__9315(.A1 (n_327), .A2 (tx_sh_reg[9]), .B1 (n_326),
       .B2 (tx_sh_reg[8]), .ZN (n_355));
  AOI22HDV1 g17667__9945(.A1 (n_327), .A2 (tx_sh_reg[10]), .B1 (n_326),
       .B2 (tx_sh_reg[9]), .ZN (n_354));
  AOI22HDV1 g17668__2883(.A1 (n_326), .A2 (tx_sh_reg[10]), .B1 (n_166),
       .B2 (FIFO_tx_inst_dout_sync[9]), .ZN (n_353));
  AOI22HDV1 g17669__2346(.A1 (n_327), .A2 (tx_sh_reg[7]), .B1 (n_326),
       .B2 (tx_sh_reg[6]), .ZN (n_352));
  AO22HDV0 g17670__1666(.A1 (n_331), .A2 (n_319), .B1 (n_584), .B2
       (\FIFO_rx_inst_fifo_mem[1] [5]), .Z (n_351));
  AO22HDV0 g17671__7410(.A1 (n_329), .A2 (n_319), .B1 (n_334), .B2
       (\FIFO_rx_inst_fifo_mem[0] [5]), .Z (n_350));
  IOA22HDV0 g17672__6417(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [8]), .B1 (n_332), .B2 (n_274), .ZN (n_349));
  IOA22HDV0 g17673__5477(.A1 (n_584), .A2 (\FIFO_rx_inst_fifo_mem[1]
       [6]), .B1 (n_332), .B2 (n_320), .ZN (n_348));
  IOA22HDV0 g17674__2398(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [6]), .B1 (n_330), .B2 (n_320), .ZN (n_347));
  IOA22HDV0 g17675__5107(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [7]), .B1 (n_330), .B2 (n_309), .ZN (n_346));
  IOA22HDV0 g17676__6260(.A1 (n_334), .A2 (\FIFO_rx_inst_fifo_mem[0]
       [8]), .B1 (n_330), .B2 (n_274), .ZN (n_345));
  IOA22HDV0 g17677__4319(.A1 (n_320), .A2 (n_319), .B1 (n_320), .B2
       (n_319), .ZN (n_358));
  INHDV0 g17678(.I (n_343), .ZN (n_344));
  AOAI211HDV1 g17679__8428(.A1 (n_234), .A2 (n_40), .B (n_302), .C
       (n_327), .ZN (n_341));
  NAND2HDV2 g17680__5526(.A1 (n_302), .A2 (tr_state), .ZN (n_343));
  AOI221HDVL g17681__6783(.A1 (n_248), .A2 (n_107), .B1 (n_122), .B2
       (n_108), .C (n_306), .ZN (n_342));
  IOA22HDV0 g17684__3680(.A1 (n_214), .A2 (UMSEL), .B1 (n_312), .B2
       (UMSEL), .ZN (n_335));
  IOA22HDV0 g17685__1617(.A1 (n_309), .A2 (rx_sh_reg[9]), .B1 (n_309),
       .B2 (rx_sh_reg[9]), .ZN (n_340));
  OAOI211HDV1 g17686__2802(.A1 (n_158), .A2 (n_132), .B (UCSRnA[3]), .C
       (n_323), .ZN (n_339));
  AOI21HDV2 g17687__1705(.A1 (n_221), .A2 (n_107), .B (n_314), .ZN
       (n_338));
  AOI221HDVL g17688__5122(.A1 (n_247), .A2 (n_106), .B1 (n_233), .B2
       (n_103), .C (n_304), .ZN (n_337));
  AOI221HDVL g17689__8246(.A1 (n_247), .A2 (n_107), .B1 (n_122), .B2
       (n_17), .C (n_307), .ZN (n_336));
  INHDV0 g17690(.I (n_332), .ZN (n_331));
  INHDV0 g17691(.I (n_330), .ZN (n_329));
  INHDV2 g17692(.I (n_328), .ZN (n_327));
  INHDV2 g17693(.I (n_326), .ZN (n_325));
  NAND2HDV2 g17694__7098(.A1 (rx_clk_en), .A2 (n_308), .ZN (n_324));
  NOR3BBHDV2 g17695__6131(.A1 (n_210), .A2 (n_190), .B (n_312), .ZN
       (n_323));
  INOR2HDV2 g17697__1881(.A1 (n_220), .B1 (n_283), .ZN (n_334));
  CLKNAND2HDV2 g17699__7482(.A1 (n_220), .A2 (n_282), .ZN (n_332));
  CLKNAND2HDV2 g17700__4733(.A1 (n_220), .A2 (n_283), .ZN (n_330));
  CLKNAND2HDV2 g17701__6161(.A1 (n_310), .A2 (tr_state), .ZN (n_328));
  NOR2HDV2 g17702__9315(.A1 (n_310), .A2 (n_83), .ZN (n_326));
  OAOI211HDV1 g17704__2883(.A1 (rx_clk_en), .A2 (rx_baud_cnt[2]), .B
       (n_300), .C (n_124), .ZN (n_317));
  OAOI211HDV1 g17705__2346(.A1 (n_250), .A2 (FIFO_rx_inst_w_pnt[0]), .B
       (n_279), .C (n_219), .ZN (n_316));
  XNOR2CHDV2 g17706__1666(.A1 (n_303), .A2 (n_194), .ZN (n_315));
  OAI211HDV2 g17707__7410(.A1 (n_123), .A2 (rx_sh_reg[9]), .B (n_298),
       .C (n_291), .ZN (n_314));
  IOA22HDV0 g17708__6417(.A1 (n_296), .A2 (n_252), .B1 (n_296), .B2
       (n_252), .ZN (n_322));
  OAI21HDV2 g17709__5477(.A1 (n_522), .A2 (UCSRnC[7]), .B (n_312), .ZN
       (n_321));
  OA211HDV2 g17710__2398(.A1 (n_232), .A2 (rx_sh_reg[6]), .B (n_288),
       .C (n_263), .Z (n_320));
  OAI211HDV2 g17711__5107(.A1 (n_172), .A2 (n_133), .B (n_292), .C
       (n_287), .ZN (n_319));
  CLKNAND2HDV2 g17717__6260(.A1 (n_303), .A2 (n_194), .ZN (n_311));
  OAI211HDV2 g17719__4319(.A1 (n_130), .A2 (rx_baud_cnt[0]), .B
       (n_272), .C (rx_clk_en), .ZN (n_312));
  IOA22HDV0 g17720__8428(.A1 (n_237), .A2 (rx_baud_cnt[3]), .B1
       (n_237), .B2 (rx_baud_cnt[3]), .ZN (n_308));
  OAI211HDV2 g17721__5526(.A1 (n_249), .A2 (rx_sh_reg[5]), .B (n_267),
       .C (n_268), .ZN (n_307));
  AO221HDV0 g17722__6783(.A1 (n_227), .A2 (n_103), .B1 (n_221), .B2
       (rx_sh_reg[2]), .C (n_295), .Z (n_306));
  OAOI211HDV1 g17723__3680(.A1 (n_250), .A2 (n_157), .B (n_275), .C
       (n_219), .ZN (n_305));
  OAI211HDV2 g17724__1617(.A1 (n_196), .A2 (rx_sh_reg[9]), .B (n_293),
       .C (n_261), .ZN (n_304));
  AOI211HDV2 g17725__2802(.A1 (n_150), .A2 (tx_samp_delay), .B (n_155),
       .C (n_299), .ZN (n_310));
  AOI221HDVL g17726__1705(.A1 (n_247), .A2 (n_17), .B1 (n_233), .B2
       (rx_sh_reg[7]), .C (n_264), .ZN (n_309));
  AD1HDV2C g17727__5122(.A (UCSRnC[3]), .B (UCSRnC[5]), .CI (n_169),
       .CO (n_303), .S (n_301));
  AO211HDV2 g17728__8246(.A1 (n_129), .A2 (rx_baud_cnt[2]), .B (n_237),
       .C (n_15), .Z (n_300));
  AOAI211HDV1 g17729__7098(.A1 (n_518), .A2 (tx_samp_delay), .B
       (tx_samp), .C (n_280), .ZN (n_299));
  AOI222HDV2 g17730__6131(.A1 (n_247), .A2 (rx_sh_reg[2]), .B1 (n_227),
       .B2 (n_106), .C1 (n_197), .C2 (n_18), .ZN (n_298));
  AOAI211HDV1 g17731__1881(.A1 (tx_samp), .A2 (tx_samp_delay), .B
       (n_256), .C (UCSRnC[7]), .ZN (n_297));
  NOR2HDV2 g17732__5115(.A1 (n_234), .A2 (n_40), .ZN (n_302));
  AO222HDV1 g17740__7482(.A1 (n_197), .A2 (n_106), .B1 (n_247), .B2
       (rx_sh_reg[1]), .C1 (n_233), .C2 (rx_sh_reg[0]), .Z (n_295));
  IOA22HDV0 g17741__4733(.A1 (n_218), .A2 (FIFO_tx_inst_fifo_buf[4]),
       .B1 (n_218), .B2 (n_255), .ZN (n_294));
  AOI22HDV1 g17742__6161(.A1 (n_248), .A2 (rx_sh_reg[7]), .B1 (n_227),
       .B2 (n_17), .ZN (n_293));
  AOI22HDV1 g17743__9315(.A1 (n_221), .A2 (rx_sh_reg[7]), .B1 (n_247),
       .B2 (n_18), .ZN (n_292));
  AOI22HDV1 g17744__9945(.A1 (n_248), .A2 (n_103), .B1 (n_233), .B2
       (rx_sh_reg[1]), .ZN (n_291));
  AOI22HDV1 g17745__2883(.A1 (n_247), .A2 (n_103), .B1 (n_197), .B2
       (n_17), .ZN (n_290));
  AOI32HDV2 g17746__2346(.A1 (n_259), .A2 (n_239), .A3 (n_199), .B1
       (n_164), .B2 (dbus_in[2]), .ZN (n_289));
  AOI22HDV1 g17747__1666(.A1 (n_221), .A2 (n_17), .B1 (n_247), .B2
       (rx_sh_reg[7]), .ZN (n_288));
  AOI22HDV1 g17748__7410(.A1 (n_248), .A2 (n_17), .B1 (n_243), .B2
       (n_106), .ZN (n_287));
  IOA22HDV0 g17749__6417(.A1 (n_218), .A2 (FIFO_tx_inst_fifo_buf[0]),
       .B1 (n_218), .B2 (n_251), .ZN (n_286));
  IOA22HDV0 g17750__5477(.A1 (n_218), .A2 (FIFO_tx_inst_fifo_buf[1]),
       .B1 (n_218), .B2 (n_253), .ZN (n_285));
  IOA22HDV0 g17751__2398(.A1 (n_218), .A2 (FIFO_tx_inst_fifo_buf[3]),
       .B1 (n_218), .B2 (n_254), .ZN (n_284));
  IOA22HDV0 g17752__5107(.A1 (n_251), .A2 (n_253), .B1 (n_253), .B2
       (n_251), .ZN (n_296));
  AOI211HDV2 g17753__6260(.A1 (n_42), .A2 (UCSRnB[2]), .B (n_197), .C
       (n_248), .ZN (n_281));
  OR2HDV2RD g17754__4319(.A1 (n_256), .A2 (n_42), .Z (n_280));
  NAND2HDV2 g17755__8428(.A1 (n_250), .A2 (FIFO_rx_inst_w_pnt[0]), .ZN
       (n_279));
  OAOI211HDV1 g17756__5526(.A1 (n_187), .A2 (FIFO_rx_inst_r_pnt[0]), .B
       (n_229), .C (n_219), .ZN (n_278));
  OAOI211HDV1 g17757__6783(.A1 (n_187), .A2 (n_143), .B (n_230), .C
       (n_219), .ZN (n_277));
  OAOI211HDV1 g17758__3680(.A1 (rx_clk_en), .A2 (rx_baud_cnt[1]), .B
       (n_215), .C (n_124), .ZN (n_276));
  NAND2HDV2 g17759__1617(.A1 (n_250), .A2 (FIFO_rx_inst_w_pnt[1]), .ZN
       (n_275));
  NOR2HDV2 g17760__2802(.A1 (n_250), .A2 (FIFO_rx_inst_w_pnt[0]), .ZN
       (n_283));
  INOR2HDV2 g17762__1705(.A1 (FIFO_rx_inst_w_pnt[0]), .B1 (n_250), .ZN
       (n_282));
  IOA21HDV1 g17766__5122(.A1 (n_235), .A2 (n_199), .B (dbus_in[5]), .ZN
       (n_273));
  OAI21HDV2 g17767__8246(.A1 (n_231), .A2 (n_518), .B (rx_baud_cnt[0]),
       .ZN (n_272));
  AOI22HDV1 g17768__7098(.A1 (n_236), .A2 (dbus_in[6]), .B1 (n_164),
       .B2 (dbus_in[1]), .ZN (n_271));
  IOA22HDV0 g17769__6131(.A1 (n_224), .A2 (FIFO_tx_inst_r_pnt[0]), .B1
       (n_224), .B2 (FIFO_tx_inst_r_pnt[0]), .ZN (n_270));
  IOA22HDV0 g17770__1881(.A1 (n_223), .A2 (n_29), .B1 (n_223), .B2
       (n_578), .ZN (n_269));
  AOI22HDV1 g17771__5115(.A1 (n_221), .A2 (n_103), .B1 (n_197), .B2
       (rx_sh_reg[7]), .ZN (n_268));
  AOI22HDV1 g17772__7482(.A1 (n_227), .A2 (n_18), .B1 (n_233), .B2
       (rx_sh_reg[2]), .ZN (n_267));
  OA32HDV2 g17773__4733(.A1 (n_164), .A2 (n_191), .A3 (n_198), .B1
       (n_163), .B2 (n_26), .Z (n_266));
  IOA22HDV0 g17774__6161(.A1 (n_217), .A2 (FIFO_tx_inst_w_pnt[0]), .B1
       (n_217), .B2 (FIFO_tx_inst_w_pnt[0]), .ZN (n_265));
  OAI22HDV0 g17775__9315(.A1 (n_213), .A2 (n_1), .B1 (n_123), .B2
       (rx_sh_reg[3]), .ZN (n_264));
  AOI22HDV1 g17776__9945(.A1 (n_228), .A2 (n_105), .B1 (n_122), .B2
       (n_103), .ZN (n_263));
  OAI22HDV0 g17777__2883(.A1 (n_218), .A2 (n_579), .B1 (n_217), .B2
       (FIFO_tx_inst_w_pnt[1]), .ZN (n_262));
  OAI21HDV2 g17778__2346(.A1 (n_221), .A2 (n_122), .B (n_18), .ZN
       (n_261));
  IAO22HDV2 g17779__1666(.A1 (n_193), .A2 (n_133), .B1 (n_233), .B2
       (n_17), .ZN (n_274));
  NOR2HDV2 g17780__7410(.A1 (n_207), .A2 (n_83), .ZN (n_258));
  NOR2HDV2 g17781__6417(.A1 (n_208), .A2 (n_83), .ZN (n_257));
  NOR3HDV2 g17783__5477(.A1 (n_186), .A2 (n_126), .A3 (UCSRnC[7]), .ZN
       (n_260));
  NOR2HDV2 g17791__2398(.A1 (n_236), .A2 (n_164), .ZN (n_259));
  INHDV2 g17795(.I (n_249), .ZN (n_248));
  OAI21HDV2 g17797__5107(.A1 (n_192), .A2 (n_121), .B (n_175), .ZN
       (n_245));
  IOA22HDV0 g17798__6260(.A1 (n_518), .A2 (rx_sync[2]), .B1 (n_190),
       .B2 (n_518), .ZN (n_244));
  OAOI211HDV1 g17799__4319(.A1 (n_170), .A2 (n_61), .B (n_123), .C
       (n_126), .ZN (n_243));
  OAI211HDV2 g17800__8428(.A1 (UCSRnC[5]), .A2 (UCSRnC[1]), .B (n_195),
       .C (n_96), .ZN (n_242));
  OAOI211HDV1 g17801__5526(.A1 (n_104), .A2 (n_146), .B (n_117), .C
       (n_83), .ZN (n_241));
  OA21HDV2 g17802__6783(.A1 (n_134), .A2 (tx_bitcnt[2]), .B (n_234), .Z
       (n_240));
  IOA22HDV0 g17803__3680(.A1 (n_174), .A2 (UCSRnC[1]), .B1 (n_174), .B2
       (UCSRnC[1]), .ZN (n_256));
  AOI221HDVL g17804__1617(.A1 (n_163), .A2 (dbus_in[4]), .B1 (n_164),
       .B2 (dbus_in[3]), .C (n_222), .ZN (n_255));
  AOI221HDVL g17805__2802(.A1 (n_163), .A2 (dbus_in[3]), .B1 (n_164),
       .B2 (dbus_in[4]), .C (n_222), .ZN (n_254));
  AOI221HDVL g17806__1705(.A1 (n_163), .A2 (dbus_in[1]), .B1 (n_164),
       .B2 (dbus_in[6]), .C (n_222), .ZN (n_253));
  AO221HDV0 g17807__5122(.A1 (n_163), .A2 (dbus_in[2]), .B1 (n_164),
       .B2 (dbus_in[5]), .C (n_222), .Z (n_252));
  AOI221HDVL g17808__8246(.A1 (n_163), .A2 (dbus_in[0]), .B1 (n_164),
       .B2 (dbus_in[7]), .C (n_222), .ZN (n_251));
  INAND3HDV2 g17809__7098(.A1 (rc_done), .B1 (n_178), .B2 (n_137), .ZN
       (n_250));
  IAO21HDV2 g17810__6131(.A1 (n_172), .A2 (n_61), .B (n_228), .ZN
       (n_249));
  OAI32HDV0 g17811__1881(.A1 (n_169), .A2 (n_61), .A3 (n_1), .B1
       (n_193), .B2 (UCSRnC[5]), .ZN (n_247));
  CLKINHDV2 g17812(.I (n_235), .ZN (n_236));
  INHDV1 g17813(.I (n_233), .ZN (n_232));
  INAND3HDV2 g17814__5115(.A1 (n_118), .B1 (n_145), .B2
       (rx_baud_cnt[1]), .ZN (n_231));
  NAND2HDV2 g17815__7482(.A1 (n_187), .A2 (FIFO_rx_inst_r_pnt[1]), .ZN
       (n_230));
  NAND2HDV2 g17816__4733(.A1 (n_187), .A2 (FIFO_rx_inst_r_pnt[0]), .ZN
       (n_229));
  NAND2HDV2 g17818__6161(.A1 (n_198), .A2 (n_128), .ZN (n_239));
  NAND2HDV2 g17821__9315(.A1 (n_195), .A2 (n_128), .ZN (n_238));
  NOR2HDV2 g17822__9945(.A1 (n_129), .A2 (rx_baud_cnt[2]), .ZN (n_237));
  NOR2HDV2 g17823__2883(.A1 (n_191), .A2 (n_126), .ZN (n_235));
  NAND2HDV2 g17825__2346(.A1 (n_134), .A2 (tx_bitcnt[2]), .ZN (n_234));
  NOR2HDV2 g17833__1666(.A1 (n_193), .A2 (n_61), .ZN (n_233));
  INHDV1 g17838(.I (n_225), .ZN (n_226));
  INHDV0 g17839(.I (n_224), .ZN (n_223));
  INHDV1 g17840(.I (n_220), .ZN (n_219));
  INHDV2 g17841(.I (n_218), .ZN (n_217));
  AOI22HDV1 g17842__7410(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[6]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[7]), .ZN (n_216));
  OAI211HDV2 g17843__6417(.A1 (rx_baud_cnt[0]), .A2 (n_36), .B
       (rx_clk_en), .C (n_129), .ZN (n_215));
  OAI21HDV2 g17844__5477(.A1 (tx_samp), .A2 (UCSRnC[0]), .B (n_142),
       .ZN (n_214));
  OA22HDV2 g17845__2398(.A1 (n_169), .A2 (n_133), .B1 (n_42), .B2
       (rx_sh_reg[10]), .Z (n_213));
  IOA22HDV0 g17846__5107(.A1 (n_162), .A2 (dbus_in[2]), .B1 (n_162),
       .B2 (n_96), .ZN (n_212));
  AOI22HDV1 g17847__6260(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[1]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[2]), .ZN (n_211));
  NOR3HDV2 g17848__4319(.A1 (n_175), .A2 (n_136), .A3 (UCSRnA[3]), .ZN
       (n_210));
  IOA21HDV1 g17849__8428(.A1 (n_132), .A2 (dbus_in[6]), .B (n_180), .ZN
       (n_209));
  AOI22HDV1 g17850__5526(.A1 (tx_clk_en), .A2 (n_151), .B1 (n_104), .B2
       (tx_baud_cnt[2]), .ZN (n_208));
  AOI22HDV1 g17851__6783(.A1 (tx_clk_en), .A2 (n_152), .B1 (n_104), .B2
       (tx_baud_cnt[3]), .ZN (n_207));
  AOI22HDV1 g17852__3680(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[3]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[4]), .ZN (n_206));
  AOI22HDV1 g17853__1617(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[0]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[1]), .ZN (n_205));
  AOI22HDV1 g17854__2802(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[4]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[5]), .ZN (n_204));
  AOI22HDV1 g17855__1705(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[2]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[3]), .ZN (n_203));
  AOI22HDV1 g17856__5122(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[7]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[8]), .ZN (n_202));
  AOI22HDV1 g17857__8246(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[5]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[6]), .ZN (n_201));
  AOI22HDV1 g17858__7098(.A1 (n_166), .A2 (FIFO_tx_inst_dout_sync[8]),
       .B1 (n_165), .B2 (FIFO_tx_inst_dout_sync[9]), .ZN (n_200));
  IOA22HDV0 g17859__6131(.A1 (n_171), .A2 (n_16), .B1 (n_42), .B2
       (n_1), .ZN (n_228));
  OAI22HDV0 g17860__1881(.A1 (n_176), .A2 (n_61), .B1 (n_172), .B2
       (UCSRnC[5]), .ZN (n_227));
  IOA22HDV0 g17861__5115(.A1 (n_138), .A2 (n_96), .B1 (n_170), .B2
       (tr_state), .ZN (n_225));
  AOI21HDV2 g17862__7482(.A1 (n_512), .A2 (tr_done), .B (n_189), .ZN
       (n_224));
  AND4HDV0 g17863__4733(.A1 (n_522), .A2 (n_140), .A3 (UCSRnB[2]), .A4
       (n_42), .Z (n_222));
  AO32HDV2 g17864__6161(.A1 (n_126), .A2 (n_127), .A3 (UCSRnC[5]), .B1
       (n_171), .B2 (n_125), .Z (n_221));
  INAND3HDV2 g17865__9315(.A1 (dbus_in[4]), .B1 (n_162), .B2 (RXENn),
       .ZN (n_220));
  INAND4HDV2 g17866__9945(.A1 (n_519), .B1 (ramwe), .B2 (n_189), .B3
       (TXENn), .ZN (n_218));
  CLKINHDV1 g17867(.I (n_197), .ZN (n_196));
  NAND2HDV2 g17868__2883(.A1 (n_522), .A2 (n_168), .ZN (n_199));
  NOR2HDV2 g17881__2346(.A1 (n_173), .A2 (n_61), .ZN (n_198));
  NOR2HDV2 g17884__1666(.A1 (n_176), .A2 (UCSRnC[5]), .ZN (n_197));
  INHDV2 g17885(.I (n_188), .ZN (n_189));
  OAI21HDV2 g17886__7410(.A1 (n_139), .A2 (UCSRnB[2]), .B (n_140), .ZN
       (n_186));
  IOA22HDV0 g17887__6417(.A1 (n_581), .A2 (dbus_in[5]), .B1 (n_581),
       .B2 (n_61), .ZN (n_185));
  OAOI211HDV1 g17888__5477(.A1 (n_104), .A2 (tx_baud_cnt[0]), .B
       (n_119), .C (n_83), .ZN (n_184));
  IOA22HDV0 g17889__2398(.A1 (n_581), .A2 (dbus_in[2]), .B1 (n_581),
       .B2 (n_1), .ZN (n_183));
  OR2HDV2RD g17890__5107(.A1 (n_170), .A2 (n_120), .Z (n_182));
  IOA22HDV0 g17891__6260(.A1 (n_581), .A2 (dbus_in[1]), .B1 (n_581),
       .B2 (n_16), .ZN (n_181));
  INAND4HDV2 g17892__4319(.A1 (irqack_addr[5]), .B1 (n_154), .B2
       (irqack_addr[4]), .B3 (irqack), .ZN (n_180));
  OAOI211HDV1 g17893__8428(.A1 (n_15), .A2 (rx_baud_cnt[0]), .B
       (n_116), .C (n_124), .ZN (n_179));
  OAI211HDV2 g17894__5526(.A1 (n_61), .A2 (rx_sh_reg[8]), .B (n_133),
       .C (UCSRnA[0]), .ZN (n_178));
  NAND3HDV2 g17895__6783(.A1 (n_137), .A2 (n_124), .A3 (UMSEL), .ZN
       (n_177));
  AND3HDV2 g17896__3680(.A1 (n_121), .A2 (n_42), .A3 (n_139), .Z
       (n_195));
  AOI22HDV1 g17897__1617(.A1 (n_127), .A2 (UCSRnC[2]), .B1 (n_125), .B2
       (n_1), .ZN (n_194));
  OR2HDV2RD g17898__2802(.A1 (n_170), .A2 (n_96), .Z (n_193));
  NAND4HDV2 g17899__1705(.A1 (rx_bitcnt[0]), .A2 (rx_bitcnt[2]), .A3
       (rx_bitcnt[3]), .A4 (rx_bitcnt[1]), .ZN (n_192));
  AND2HDV2RD g17900__5122(.A1 (n_173), .A2 (UCSRnC[2]), .Z (n_191));
  MAOI222HDV2 g17901__8246(.A (rx_sync[0]), .B (rx_sync[2]), .C
       (rx_sync[1]), .ZN (n_190));
  OAI221HDV1 g17902__7098(.A1 (FIFO_tx_inst_r_pnt[1]), .A2 (n_28), .B1
       (FIFO_tx_inst_w_pnt[1]), .B2 (n_29), .C (n_148), .ZN (n_188));
  NAND2HDV2 g17903__6131(.A1 (n_158), .A2 (n_517), .ZN (n_187));
  INHDV0 g17904(.I (n_169), .ZN (n_168));
  INHDV2 g17905(.I (n_164), .ZN (n_163));
  NAND2HDV1 g17906__1881(.A1 (n_124), .A2 (rx_sync[0]), .ZN (n_161));
  IAO21HDV2 g17907__5115(.A1 (tx_bitcnt[1]), .A2 (tx_bitcnt[0]), .B
       (n_134), .ZN (n_160));
  CLKNAND2HDV2 g17908__7482(.A1 (n_128), .A2 (n_127), .ZN (n_176));
  OR2HDV2RD g17909__4733(.A1 (n_137), .A2 (rc_done), .Z (n_175));
  AND2HDV2RD g17910__6161(.A1 (n_127), .A2 (n_1), .Z (n_159));
  AOI21BHDV0 g17911__9315(.A (n_142), .B1 (n_22), .B2 (tx_samp_delay),
       .ZN (n_174));
  CLKNAND2HDV2 g17912__9945(.A1 (n_522), .A2 (n_127), .ZN (n_173));
  CLKNAND2HDV2 g17913__2883(.A1 (n_128), .A2 (n_125), .ZN (n_172));
  AND2HDV2RD g17914__2346(.A1 (n_126), .A2 (n_61), .Z (n_171));
  CLKNAND2HDV2 g17915__1666(.A1 (n_125), .A2 (UCSRnC[2]), .ZN (n_170));
  CLKNAND2HDV2 g17916__7410(.A1 (n_125), .A2 (n_96), .ZN (n_169));
  NOR3BBHDV2 g17917__6417(.A1 (ram_Addr[0]), .A2 (ram_Addr[2]), .B
       (n_521), .ZN (n_167));
  INOR2HDV2 g17918__5477(.A1 (n_138), .B1 (tx_fifo_empty), .ZN (n_166));
  AND2HDV2RD g17919__2398(.A1 (n_141), .A2 (UCSRnC[7]), .Z (n_165));
  OAI21HDV2 g17920__5107(.A1 (n_522), .A2 (UCSRnC[2]), .B (n_123), .ZN
       (n_164));
  INOR3HDV1 g17921__6260(.A1 (ram_Addr[0]), .B1 (n_521), .B2
       (ram_Addr[2]), .ZN (n_162));
  XNOR2CHDV2 g17922__4319(.A1 (FIFO_rx_inst_w_pnt[0]), .A2
       (FIFO_rx_inst_w_pnt[1]), .ZN (n_157));
  NAND3BBHDV2 g17923__8428(.A1 (tx_samp), .A2 (tx_samp_delay), .B
       (n_518), .ZN (n_156));
  NOR3BBHDV2 g17924__5526(.A1 (tx_samp), .A2 (UCSRnC[0]), .B (n_515),
       .ZN (n_155));
  INOR4HDV2 g17925__6783(.A1 (irqack_addr[2]), .B1 (irqack_addr[3]),
       .B2 (irqack_addr[0]), .B3 (irqack_addr[1]), .ZN (n_154));
  AO22HDV0 g17926__3680(.A1 (n_15), .A2 (rx_sync[0]), .B1 (rx_clk_en),
       .B2 (rx_sync[1]), .Z (n_153));
  IOA22HDV0 g17927__1617(.A1 (n_513), .A2 (tx_baud_cnt[3]), .B1
       (n_513), .B2 (tx_baud_cnt[3]), .ZN (n_152));
  IOA22HDV0 g17928__2802(.A1 (n_516), .A2 (tx_baud_cnt[2]), .B1
       (n_516), .B2 (tx_baud_cnt[2]), .ZN (n_151));
  IOA22HDV0 g17929__1705(.A1 (tx_samp), .A2 (UCSRnC[7]), .B1 (n_515),
       .B2 (UCSRnC[0]), .ZN (n_150));
  AO22HDV0 g17930__5122(.A1 (n_15), .A2 (rx_sync[1]), .B1 (rx_clk_en),
       .B2 (rx_sync[2]), .Z (n_149));
  XNOR2CHDV2 g17931__8246(.A1 (FIFO_tx_inst_r_pnt[0]), .A2
       (FIFO_tx_inst_w_pnt[0]), .ZN (n_148));
  XNOR2CHDV2 g17933__6131(.A1 (tx_baud_cnt[0]), .A2 (tx_baud_cnt[1]),
       .ZN (n_146));
  IAO22HDV2 g17934__1881(.A1 (rx_baud_cnt[2]), .A2 (UCSRnA[1]), .B1
       (rx_baud_cnt[2]), .B2 (UCSRnA[1]), .ZN (n_145));
  XNOR2CHDV2 g17936__7482(.A1 (FIFO_rx_inst_r_pnt[0]), .A2
       (FIFO_rx_inst_r_pnt[1]), .ZN (n_143));
  NOR3BBHDV2 g17937__4733(.A1 (ramre), .A2 (RXENn), .B (n_519), .ZN
       (n_158));
  INHDV0 g17938(.I (n_136), .ZN (n_135));
  INOR2HDV2 g17939__6161(.A1 (DDR_XCKn), .B1 (n_515), .ZN (n_130));
  INAND2HDV2 g17940__9315(.A1 (tx_samp_delay), .B1 (UCSRnC[0]), .ZN
       (n_142));
  NOR2HDV2 g17941__9945(.A1 (tx_fifo_empty), .A2 (tr_state), .ZN
       (n_141));
  NAND2HDV2 g17942__2883(.A1 (UCSRnC[2]), .A2 (UCSRnC[1]), .ZN (n_140));
  NAND2HDV2 g17943__2346(.A1 (UCSRnC[5]), .A2 (UCSRnC[1]), .ZN (n_139));
  NOR2HDV2 g17944__1666(.A1 (UCSRnC[7]), .A2 (tr_state), .ZN (n_138));
  INAND2HDV2 g17945__7410(.A1 (FIFO_rx_inst_n_194), .B1 (n_520), .ZN
       (n_137));
  INAND2HDV2 g17946__6417(.A1 (rc_state[0]), .B1 (rc_state[1]), .ZN
       (n_136));
  AND2HDV2RD g17947__5477(.A1 (tx_bitcnt[1]), .A2 (tx_bitcnt[0]), .Z
       (n_134));
  CLKNAND2HDV2 g17948__2398(.A1 (n_61), .A2 (n_105), .ZN (n_133));
  NOR2HDV2 g17949__5107(.A1 (n_521), .A2 (n_514), .ZN (n_132));
  INHDV1 g17951(.I (n_123), .ZN (n_122));
  INHDV2 g17952(.I (n_121), .ZN (n_120));
  NAND2HDV2 g17953__4319(.A1 (n_104), .A2 (tx_baud_cnt[0]), .ZN
       (n_119));
  AND2HDV2RD g17954__8428(.A1 (rx_baud_cnt[2]), .A2 (rx_baud_cnt[3]),
       .Z (n_118));
  NAND2HDV2 g17955__5526(.A1 (n_104), .A2 (tx_baud_cnt[1]), .ZN
       (n_117));
  NAND2HDV2 g17956__6783(.A1 (n_15), .A2 (rx_baud_cnt[0]), .ZN (n_116));
  NAND2HDV2 g17957__3680(.A1 (rx_baud_cnt[0]), .A2 (n_36), .ZN (n_129));
  NOR2HDV2 g17958__1617(.A1 (UCSRnB[2]), .A2 (UCSRnC[2]), .ZN (n_128));
  NOR2HDV2 g17959__2802(.A1 (UCSRnC[7]), .A2 (UCSRnC[1]), .ZN (n_127));
  NOR2HDV2 g17960__1705(.A1 (n_1), .A2 (UCSRnB[2]), .ZN (n_126));
  NOR2HDV2 g17961__5122(.A1 (UCSRnC[7]), .A2 (n_16), .ZN (n_125));
  AND2HDV2RD g17962__8246(.A1 (rc_state[1]), .A2 (rc_state[0]), .Z
       (n_124));
  NAND2HDV2 g17963__7098(.A1 (UCSRnC[7]), .A2 (n_1), .ZN (n_123));
  INAND2HDV2 g17964__6131(.A1 (rc_state[1]), .B1 (rc_state[0]), .ZN
       (n_121));
  CLKINHDV2 g17965(.I (rx_bitcnt[1]), .ZN (n_115));
  INHDV0 g17972(.I (rx_sh_reg[10]), .ZN (n_108));
  INHDV1 g17973(.I (rx_sh_reg[3]), .ZN (n_107));
  INHDV2 g17974(.I (rx_sh_reg[5]), .ZN (n_106));
  INHDV1 g17975(.I (rx_sh_reg[9]), .ZN (n_105));
  INHDV2 g17976(.I (tx_clk_en), .ZN (n_104));
  INHDV2 g17977(.I (rx_sh_reg[4]), .ZN (n_103));
  INHDV1 g17978(.I (UCSRnB[2]), .ZN (n_96));
  INHDV0 g17995(.I (tr_state), .ZN (n_83));
  INHDV0 g18018(.I (n_61), .ZN (UCSRnC[5]));
  INHDV0 g18038(.I (n_42), .ZN (UCSRnC[7]));
  INHDV2 g18042(.I (tx_bitcnt[3]), .ZN (n_40));
  INHDV1 g18046(.I (rx_baud_cnt[1]), .ZN (n_36));
  INHDV2 g18053(.I (FIFO_tx_inst_r_pnt[1]), .ZN (n_29));
  INHDV2 g18054(.I (FIFO_tx_inst_w_pnt[1]), .ZN (n_28));
  CLKINHDV1 g18056(.I (dbus_in[0]), .ZN (n_26));
  INHDV0 g18060(.I (UCSRnC[0]), .ZN (n_22));
  INHDV2 g18064(.I (rx_sh_reg[6]), .ZN (n_18));
  INHDV2 g18065(.I (rx_sh_reg[8]), .ZN (n_17));
  INHDV1 g18066(.I (UCSRnC[1]), .ZN (n_16));
  INHDV2 g18067(.I (rx_clk_en), .ZN (n_15));
  INHDV1 g18079(.I (n_1), .ZN (UCSRnC[2]));
  XOR2CHDV2 g2(.A1 (n_444), .A2 (n_576), .Z (n_575));
  XOR2CHDV2 g18084(.A1 (n_437), .A2 (n_428), .Z (n_576));
  MUX2NHDV1 g18085(.I0 (rx_sh_reg[8]), .I1 (rx_sh_reg[9]), .S (n_410),
       .ZN (n_577));
  MUX2NHDV1 g18086(.I0 (FIFO_tx_inst_r_pnt[1]), .I1 (n_29), .S
       (FIFO_tx_inst_r_pnt[0]), .ZN (n_578));
  MUX2NHDV1 g18087(.I0 (FIFO_tx_inst_w_pnt[1]), .I1 (n_28), .S
       (FIFO_tx_inst_w_pnt[0]), .ZN (n_579));
  INOR4HDVL g18088(.A1 (n_479), .B1 (n_475), .B2 (rst_status), .B3
       (n_0), .ZN (n_580));
  AND2HDV2RD g18089(.A1 (ramwe), .A2 (n_477), .Z (n_581));
  INOR3HDV1 g18090(.A1 (n_471), .B1 (n_519), .B2 (n_0), .ZN (n_582));
  INOR3HDV1 g18091(.A1 (ram_Addr[0]), .B1 (n_473), .B2 (ram_Addr[2]),
       .ZN (n_583));
  INOR2HDV2 g18092(.A1 (n_220), .B1 (n_282), .ZN (n_584));
  I2NAND4HDV2 g18093(.A1 (n_247), .A2 (n_221), .B1 (n_281), .B2
       (rx_sh_reg[7]), .ZN (n_585));
endmodule

