
//input ports
add mapped point ireset ireset -type PI PI
add mapped point cp2 cp2 -type PI PI
add mapped point ram_Addr[11] ram_Addr[11] -type PI PI
add mapped point ram_Addr[10] ram_Addr[10] -type PI PI
add mapped point ram_Addr[9] ram_Addr[9] -type PI PI
add mapped point ram_Addr[8] ram_Addr[8] -type PI PI
add mapped point ram_Addr[7] ram_Addr[7] -type PI PI
add mapped point ram_Addr[6] ram_Addr[6] -type PI PI
add mapped point ram_Addr[5] ram_Addr[5] -type PI PI
add mapped point ram_Addr[4] ram_Addr[4] -type PI PI
add mapped point ram_Addr[3] ram_Addr[3] -type PI PI
add mapped point ram_Addr[2] ram_Addr[2] -type PI PI
add mapped point ram_Addr[1] ram_Addr[1] -type PI PI
add mapped point ram_Addr[0] ram_Addr[0] -type PI PI
add mapped point ramre ramre -type PI PI
add mapped point ramwe ramwe -type PI PI
add mapped point dbus_in[7] dbus_in[7] -type PI PI
add mapped point dbus_in[6] dbus_in[6] -type PI PI
add mapped point dbus_in[5] dbus_in[5] -type PI PI
add mapped point dbus_in[4] dbus_in[4] -type PI PI
add mapped point dbus_in[3] dbus_in[3] -type PI PI
add mapped point dbus_in[2] dbus_in[2] -type PI PI
add mapped point dbus_in[1] dbus_in[1] -type PI PI
add mapped point dbus_in[0] dbus_in[0] -type PI PI
add mapped point DDR_XCKn DDR_XCKn -type PI PI
add mapped point XCKn_i XCKn_i -type PI PI
add mapped point RxDn_i RxDn_i -type PI PI
add mapped point irqack_addr[5] irqack_addr[5] -type PI PI
add mapped point irqack_addr[4] irqack_addr[4] -type PI PI
add mapped point irqack_addr[3] irqack_addr[3] -type PI PI
add mapped point irqack_addr[2] irqack_addr[2] -type PI PI
add mapped point irqack_addr[1] irqack_addr[1] -type PI PI
add mapped point irqack_addr[0] irqack_addr[0] -type PI PI
add mapped point irqack irqack -type PI PI

//output ports
add mapped point out_en out_en -type PO PO
add mapped point dbus_out[7] dbus_out[7] -type PO PO
add mapped point dbus_out[6] dbus_out[6] -type PO PO
add mapped point dbus_out[5] dbus_out[5] -type PO PO
add mapped point dbus_out[4] dbus_out[4] -type PO PO
add mapped point dbus_out[3] dbus_out[3] -type PO PO
add mapped point dbus_out[2] dbus_out[2] -type PO PO
add mapped point dbus_out[1] dbus_out[1] -type PO PO
add mapped point dbus_out[0] dbus_out[0] -type PO PO
add mapped point UMSEL UMSEL -type PO PO
add mapped point XCKn_o XCKn_o -type PO PO
add mapped point TxDn_o TxDn_o -type PO PO
add mapped point RXENn RXENn -type PO PO
add mapped point TXENn TXENn -type PO PO
add mapped point TxcIRQ TxcIRQ -type PO PO
add mapped point RxcIRQ RxcIRQ -type PO PO
add mapped point UdreIRQ UdreIRQ -type PO PO
add mapped point UStBIRQ UStBIRQ -type PO PO

//inout ports




//Sequential Pins
add mapped point USART_Clk_inst/rx_prsc_cnt[0]/q USART_Clk_inst/rx_prsc_cnt_reg[0]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[1]/q USART_Clk_inst/rx_prsc_cnt_reg[1]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[2]/q USART_Clk_inst/rx_prsc_cnt_reg[2]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[3]/q USART_Clk_inst/rx_prsc_cnt_reg[3]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[4]/q USART_Clk_inst/rx_prsc_cnt_reg[4]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[5]/q USART_Clk_inst/rx_prsc_cnt_reg[5]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[6]/q USART_Clk_inst/rx_prsc_cnt_reg[6]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[7]/q USART_Clk_inst/rx_prsc_cnt_reg[7]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[8]/q USART_Clk_inst/rx_prsc_cnt_reg[8]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[9]/q USART_Clk_inst/rx_prsc_cnt_reg[9]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[10]/q USART_Clk_inst/rx_prsc_cnt_reg[10]/Q -type DFF DFF
add mapped point USART_Clk_inst/rx_prsc_cnt[11]/q USART_Clk_inst/rx_prsc_cnt_reg[11]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[0]/q USART_Clk_inst/tx_prsc_cnt_reg[0]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[1]/q USART_Clk_inst/tx_prsc_cnt_reg[1]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[2]/q USART_Clk_inst/tx_prsc_cnt_reg[2]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[3]/q USART_Clk_inst/tx_prsc_cnt_reg[3]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[4]/q USART_Clk_inst/tx_prsc_cnt_reg[4]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[5]/q USART_Clk_inst/tx_prsc_cnt_reg[5]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[6]/q USART_Clk_inst/tx_prsc_cnt_reg[6]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[7]/q USART_Clk_inst/tx_prsc_cnt_reg[7]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[8]/q USART_Clk_inst/tx_prsc_cnt_reg[8]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[9]/q USART_Clk_inst/tx_prsc_cnt_reg[9]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[10]/q USART_Clk_inst/tx_prsc_cnt_reg[10]/Q -type DFF DFF
add mapped point USART_Clk_inst/tx_prsc_cnt[11]/q USART_Clk_inst/tx_prsc_cnt_reg[11]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[0]/q FIFO_tx_inst_dout_sync_reg[0]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[1]/q FIFO_tx_inst_dout_sync_reg[1]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[2]/q FIFO_tx_inst_dout_sync_reg[2]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[3]/q FIFO_tx_inst_dout_sync_reg[3]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[4]/q FIFO_tx_inst_dout_sync_reg[4]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[5]/q FIFO_tx_inst_dout_sync_reg[5]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[6]/q FIFO_tx_inst_dout_sync_reg[6]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[7]/q FIFO_tx_inst_dout_sync_reg[7]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[8]/q FIFO_tx_inst_dout_sync_reg[8]/Q -type DFF DFF
add mapped point FIFO_tx_inst/dout_sync[9]/q FIFO_tx_inst_dout_sync_reg[9]/Q -type DFF DFF
add mapped point XCK_int/q XCK_int_reg/QN -type DFF DFF
add mapped point rx_sync[2]/q rx_sync_reg[2]/Q -type DFF DFF
add mapped point tx_samp_delay/q tx_samp_delay_reg/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][0]/q FIFO_rx_inst_fifo_mem_reg[0][0]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][1]/q FIFO_rx_inst_fifo_mem_reg[0][1]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][2]/q FIFO_rx_inst_fifo_mem_reg[0][2]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][3]/q FIFO_rx_inst_fifo_mem_reg[0][3]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][4]/q FIFO_rx_inst_fifo_mem_reg[0][4]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][5]/q FIFO_rx_inst_fifo_mem_reg[0][5]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][6]/q FIFO_rx_inst_fifo_mem_reg[0][6]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][7]/q FIFO_rx_inst_fifo_mem_reg[0][7]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][8]/q FIFO_rx_inst_fifo_mem_reg[0][8]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][9]/q FIFO_rx_inst_fifo_mem_reg[0][9]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[0][10]/q FIFO_rx_inst_fifo_mem_reg[0][10]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][0]/q FIFO_rx_inst_fifo_mem_reg[1][0]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][1]/q FIFO_rx_inst_fifo_mem_reg[1][1]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][2]/q FIFO_rx_inst_fifo_mem_reg[1][2]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][3]/q FIFO_rx_inst_fifo_mem_reg[1][3]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][4]/q FIFO_rx_inst_fifo_mem_reg[1][4]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][5]/q FIFO_rx_inst_fifo_mem_reg[1][5]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][6]/q FIFO_rx_inst_fifo_mem_reg[1][6]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][7]/q FIFO_rx_inst_fifo_mem_reg[1][7]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][8]/q FIFO_rx_inst_fifo_mem_reg[1][8]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][9]/q FIFO_rx_inst_fifo_mem_reg[1][9]/Q -type DFF DFF
add mapped point FIFO_rx_inst/fifo_mem[1][10]/q FIFO_rx_inst_fifo_mem_reg[1][10]/Q -type DFF DFF
add mapped point FIFO_rx_inst/r_pnt[0]/q FIFO_rx_inst_r_pnt_reg[0]/Q -type DFF DFF
add mapped point FIFO_rx_inst/r_pnt[1]/q FIFO_rx_inst_r_pnt_reg[1]/Q -type DFF DFF
add mapped point FIFO_rx_inst/w_pnt[0]/q FIFO_rx_inst_w_pnt_reg[0]/Q -type DFF DFF
add mapped point FIFO_rx_inst/w_pnt[1]/q FIFO_rx_inst_w_pnt_reg[1]/Q -type DFF DFF
add mapped point FIFO_tx_inst/empty_int_sync/q FIFO_tx_inst_empty_int_sync_reg/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[0]/q FIFO_tx_inst_fifo_buf_reg[0]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[1]/q FIFO_tx_inst_fifo_buf_reg[1]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[2]/q FIFO_tx_inst_fifo_buf_reg[2]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[3]/q FIFO_tx_inst_fifo_buf_reg[3]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[4]/q FIFO_tx_inst_fifo_buf_reg[4]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[5]/q FIFO_tx_inst_fifo_buf_reg[5]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[6]/q FIFO_tx_inst_fifo_buf_reg[6]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[7]/q FIFO_tx_inst_fifo_buf_reg[7]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[8]/q FIFO_tx_inst_fifo_buf_reg[8]/Q -type DFF DFF
add mapped point FIFO_tx_inst/fifo_buf[9]/q FIFO_tx_inst_fifo_buf_reg[9]/Q -type DFF DFF
add mapped point FIFO_tx_inst/full_int_sync/q FIFO_tx_inst_full_int_sync_reg/Q -type DFF DFF
add mapped point FIFO_tx_inst/r_pnt[0]/q FIFO_tx_inst_r_pnt_reg[0]/QN -type DFF DFF
add mapped point FIFO_tx_inst/r_pnt[1]/q FIFO_tx_inst_r_pnt_reg[1]/QN -type DFF DFF
add mapped point FIFO_tx_inst/w_pnt[0]/q FIFO_tx_inst_w_pnt_reg[0]/QN -type DFF DFF
add mapped point FIFO_tx_inst/w_pnt[1]/q FIFO_tx_inst_w_pnt_reg[1]/QN -type DFF DFF
add mapped point Temp[0]/q Temp_reg[0]/Q -type DFF DFF
add mapped point Temp[1]/q Temp_reg[1]/Q -type DFF DFF
add mapped point Temp[2]/q Temp_reg[2]/Q -type DFF DFF
add mapped point Temp[3]/q Temp_reg[3]/Q -type DFF DFF
add mapped point UBRRn[0]/q UBRRn_reg[0]/Q -type DFF DFF
add mapped point UBRRn[1]/q UBRRn_reg[1]/Q -type DFF DFF
add mapped point UBRRn[2]/q UBRRn_reg[2]/Q -type DFF DFF
add mapped point UBRRn[3]/q UBRRn_reg[3]/Q -type DFF DFF
add mapped point UBRRn[4]/q UBRRn_reg[4]/Q -type DFF DFF
add mapped point UBRRn[5]/q UBRRn_reg[5]/Q -type DFF DFF
add mapped point UBRRn[6]/q UBRRn_reg[6]/Q -type DFF DFF
add mapped point UBRRn[7]/q UBRRn_reg[7]/Q -type DFF DFF
add mapped point UBRRn[8]/q UBRRn_reg[8]/Q -type DFF DFF
add mapped point UBRRn[9]/q UBRRn_reg[9]/Q -type DFF DFF
add mapped point UBRRn[10]/q UBRRn_reg[10]/Q -type DFF DFF
add mapped point UBRRn[11]/q UBRRn_reg[11]/Q -type DFF DFF
add mapped point UCSRnA[0]/q UCSRnA_reg[0]/Q -type DFF DFF
add mapped point UCSRnA[1]/q UCSRnA_reg[1]/Q -type DFF DFF
add mapped point UCSRnA[3]/q UCSRnA_reg[3]/Q -type DFF DFF
add mapped point UCSRnA[6]/q UCSRnA_reg[6]/Q -type DFF DFF
add mapped point UCSRnB[0]/q UCSRnB_reg[0]/Q -type DFF DFF
add mapped point UCSRnB[2]/q UCSRnB_reg[2]/Q -type DFF DFF
add mapped point UCSRnB[3]/q UCSRnB_reg[3]/Q -type DFF DFF
add mapped point UCSRnB[4]/q UCSRnB_reg[4]/Q -type DFF DFF
add mapped point UCSRnB[5]/q UCSRnB_reg[5]/Q -type DFF DFF
add mapped point UCSRnB[6]/q UCSRnB_reg[6]/Q -type DFF DFF
add mapped point UCSRnB[7]/q UCSRnB_reg[7]/Q -type DFF DFF
add mapped point UCSRnC[0]/q UCSRnC_reg[0]/Q -type DFF DFF
add mapped point UCSRnC[1]/q UCSRnC_reg[1]/Q -type DFF DFF
add mapped point UCSRnC[2]/q UCSRnC_reg[2]/QN -type DFF DFF
add mapped point UCSRnC[3]/q UCSRnC_reg[3]/Q -type DFF DFF
add mapped point UCSRnC[4]/q UCSRnC_reg[4]/Q -type DFF DFF
add mapped point UCSRnC[5]/q UCSRnC_reg[5]/QN -type DFF DFF
add mapped point UCSRnC[6]/q UCSRnC_reg[6]/Q -type DFF DFF
add mapped point UCSRnC[7]/q UCSRnC_reg[7]/QN -type DFF DFF
add mapped point rc_done/q rc_done_reg/QN -type DFF DFF
add mapped point rc_state[0]/q rc_state_reg[0]/QN -type DFF DFF
add mapped point rc_state[1]/q rc_state_reg[1]/QN -type DFF DFF
add mapped point rst_status/q rst_status_reg/Q -type DFF DFF
add mapped point rx_baud_cnt[0]/q rx_baud_cnt_reg[0]/Q -type DFF DFF
add mapped point rx_baud_cnt[1]/q rx_baud_cnt_reg[1]/QN -type DFF DFF
add mapped point rx_baud_cnt[2]/q rx_baud_cnt_reg[2]/QN -type DFF DFF
add mapped point rx_baud_cnt[3]/q rx_baud_cnt_reg[3]/QN -type DFF DFF
add mapped point rx_bitcnt[0]/q rx_bitcnt_reg[0]/QN -type DFF DFF
add mapped point rx_bitcnt[1]/q rx_bitcnt_reg[1]/QN -type DFF DFF
add mapped point rx_bitcnt[2]/q rx_bitcnt_reg[2]/QN -type DFF DFF
add mapped point rx_bitcnt[3]/q rx_bitcnt_reg[3]/QN -type DFF DFF
add mapped point rx_sh_reg[0]/q rx_sh_reg_reg[0]/Q -type DFF DFF
add mapped point rx_sh_reg[1]/q rx_sh_reg_reg[1]/Q -type DFF DFF
add mapped point rx_sh_reg[2]/q rx_sh_reg_reg[2]/Q -type DFF DFF
add mapped point rx_sh_reg[3]/q rx_sh_reg_reg[3]/QN -type DFF DFF
add mapped point rx_sh_reg[4]/q rx_sh_reg_reg[4]/QN -type DFF DFF
add mapped point rx_sh_reg[5]/q rx_sh_reg_reg[5]/QN -type DFF DFF
add mapped point rx_sh_reg[6]/q rx_sh_reg_reg[6]/QN -type DFF DFF
add mapped point rx_sh_reg[7]/q rx_sh_reg_reg[7]/Q -type DFF DFF
add mapped point rx_sh_reg[8]/q rx_sh_reg_reg[8]/QN -type DFF DFF
add mapped point rx_sh_reg[9]/q rx_sh_reg_reg[9]/QN -type DFF DFF
add mapped point rx_sh_reg[10]/q rx_sh_reg_reg[10]/QN -type DFF DFF
add mapped point rx_sync[0]/q rx_sync_reg[0]/Q -type DFF DFF
add mapped point rx_sync[1]/q rx_sync_reg[1]/Q -type DFF DFF
add mapped point tr_done/q tr_done_reg/QN -type DFF DFF
add mapped point tr_state/q tr_state_reg/Q -type DFF DFF
add mapped point tx_baud_cnt[0]/q tx_baud_cnt_reg[0]/Q -type DFF DFF
add mapped point tx_baud_cnt[1]/q tx_baud_cnt_reg[1]/Q -type DFF DFF
add mapped point tx_baud_cnt[2]/q tx_baud_cnt_reg[2]/Q -type DFF DFF
add mapped point tx_baud_cnt[3]/q tx_baud_cnt_reg[3]/Q -type DFF DFF
add mapped point tx_bitcnt[0]/q tx_bitcnt_reg[0]/QN -type DFF DFF
add mapped point tx_bitcnt[1]/q tx_bitcnt_reg[1]/QN -type DFF DFF
add mapped point tx_bitcnt[2]/q tx_bitcnt_reg[2]/QN -type DFF DFF
add mapped point tx_bitcnt[3]/q tx_bitcnt_reg[3]/QN -type DFF DFF
add mapped point tx_sh_reg[0]/q tx_sh_reg_reg[0]/Q -type DFF DFF
add mapped point tx_sh_reg[1]/q tx_sh_reg_reg[1]/Q -type DFF DFF
add mapped point tx_sh_reg[2]/q tx_sh_reg_reg[2]/Q -type DFF DFF
add mapped point tx_sh_reg[3]/q tx_sh_reg_reg[3]/Q -type DFF DFF
add mapped point tx_sh_reg[4]/q tx_sh_reg_reg[4]/Q -type DFF DFF
add mapped point tx_sh_reg[5]/q tx_sh_reg_reg[5]/Q -type DFF DFF
add mapped point tx_sh_reg[6]/q tx_sh_reg_reg[6]/Q -type DFF DFF
add mapped point tx_sh_reg[7]/q tx_sh_reg_reg[7]/Q -type DFF DFF
add mapped point tx_sh_reg[8]/q tx_sh_reg_reg[8]/Q -type DFF DFF
add mapped point tx_sh_reg[9]/q tx_sh_reg_reg[9]/Q -type DFF DFF
add mapped point tx_sh_reg[10]/q tx_sh_reg_reg[10]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
