
// Generated by Cadence Genus(TM) Synthesis Solution 22.10-p001_1
// Generated on: Mar 12 2025 23:47:47 +07 (Mar 12 2025 16:47:47 UTC)

// Verification Directory fv/Port_E 

module rg_md_p_width4_p_init_val0_p_impl_mask15_1(clk, nrst, wdata,
     wbe, rdata, tog);
  input clk, nrst, wbe, tog;
  input [7:0] wdata;
  output [7:0] rdata;
  wire clk, nrst, wbe, tog;
  wire [7:0] wdata;
  wire [7:0] rdata;
  EDRNQHDV0 \rg_current_reg[0] (.RDN (nrst), .CK (clk), .D (wdata[0]),
       .E (wbe), .Q (rdata[0]));
  EDRNQHDV0 \rg_current_reg[1] (.RDN (nrst), .CK (clk), .D (wdata[1]),
       .E (wbe), .Q (rdata[1]));
  EDRNQHDV0 \rg_current_reg[2] (.RDN (nrst), .CK (clk), .D (wdata[2]),
       .E (wbe), .Q (rdata[2]));
  EDRNQHDV0 \rg_current_reg[3] (.RDN (nrst), .CK (clk), .D (wdata[3]),
       .E (wbe), .Q (rdata[3]));
endmodule

module rg_md_p_width4_p_init_val0_p_impl_mask15(clk, nrst, wdata, wbe,
     rdata, tog);
  input clk, nrst, wbe, tog;
  input [7:0] wdata;
  output [7:0] rdata;
  wire clk, nrst, wbe, tog;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  DRNQHDV4 \rg_current_reg[0] (.RDN (nrst), .CK (clk), .D (n_13), .Q
       (rdata[0]));
  DRNQHDV4 \rg_current_reg[2] (.RDN (nrst), .CK (clk), .D (n_12), .Q
       (rdata[2]));
  DRNQHDV4 \rg_current_reg[3] (.RDN (nrst), .CK (clk), .D (n_11), .Q
       (rdata[3]));
  IOA22HDV0 g529__2398(.A1 (n_9), .A2 (wdata[0]), .B1 (wbe), .B2 (n_1),
       .ZN (n_13));
  DRNQHDV4 \rg_current_reg[1] (.RDN (nrst), .CK (clk), .D (n_10), .Q
       (rdata[1]));
  IOA22HDV0 g531__5107(.A1 (n_8), .A2 (wdata[2]), .B1 (wbe), .B2 (n_4),
       .ZN (n_12));
  IOA22HDV0 g532__6260(.A1 (n_7), .A2 (wdata[3]), .B1 (wbe), .B2 (n_3),
       .ZN (n_11));
  AO22HDV0 g533__4319(.A1 (n_6), .A2 (rdata[1]), .B1 (n_5), .B2
       (wdata[1]), .Z (n_10));
  IOA22HDV0 g534__8428(.A1 (n_0), .A2 (rdata[0]), .B1 (n_2), .B2
       (rdata[0]), .ZN (n_9));
  IOA22HDV0 g535__5526(.A1 (n_0), .A2 (rdata[2]), .B1 (n_2), .B2
       (rdata[2]), .ZN (n_8));
  IOA22HDV0 g536__6783(.A1 (n_0), .A2 (rdata[3]), .B1 (n_2), .B2
       (rdata[3]), .ZN (n_7));
  OAI21BHDV2 g537__3680(.A (n_2), .B1 (wbe), .B2 (wdata[1]), .ZN (n_6));
  IOA22HDV0 g538__1617(.A1 (n_0), .A2 (wbe), .B1 (n_0), .B2 (rdata[1]),
       .ZN (n_5));
  INAND2HDV2 g539__2802(.A1 (wdata[2]), .B1 (rdata[2]), .ZN (n_4));
  INAND2HDV2 g540__1705(.A1 (wdata[3]), .B1 (rdata[3]), .ZN (n_3));
  INAND2HDV2 g541__5122(.A1 (wdata[0]), .B1 (rdata[0]), .ZN (n_1));
  NOR2HDV2 g542__8246(.A1 (tog), .A2 (wbe), .ZN (n_2));
  INHDV2 g543(.I (tog), .ZN (n_0));
endmodule

module synchronizer_p_width4(clk, d_sync, d_in);
  input clk;
  input [3:0] d_in;
  output [3:0] d_sync;
  wire clk;
  wire [3:0] d_in;
  wire [3:0] d_sync;
  wire [3:0] d_latch;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2;
  DQHDV2 \d_sync_int_reg[3] (.CK (clk), .D (d_latch[3]), .Q
       (d_sync[3]));
  DQHDV2 \d_sync_int_reg[2] (.CK (clk), .D (d_latch[2]), .Q
       (d_sync[2]));
  DQHDV2 \d_sync_int_reg[0] (.CK (clk), .D (d_latch[0]), .Q
       (d_sync[0]));
  DQHDV2 \d_sync_int_reg[1] (.CK (clk), .D (d_latch[1]), .Q
       (d_sync[1]));
  LAHHDV0 \d_latch_reg[2] (.E (clk), .D (d_in[2]), .Q (d_latch[2]), .QN
       (UNCONNECTED));
  LAHHDV0 \d_latch_reg[0] (.E (clk), .D (d_in[0]), .Q (d_latch[0]), .QN
       (UNCONNECTED0));
  LAHHDV0 \d_latch_reg[1] (.E (clk), .D (d_in[1]), .Q (d_latch[1]), .QN
       (UNCONNECTED1));
  LAHHDV0 \d_latch_reg[3] (.E (clk), .D (d_in[3]), .Q (d_latch[3]), .QN
       (UNCONNECTED2));
endmodule

module
     IO_Port_PINx_Address12_DDRx_Address13_PORTx_Address14_port_width4(ireset,
     cp2, IO_Addr, dbus_in, dbus_out, iore, iowe, out_en, portx, ddrx,
     pinx);
  input ireset, cp2, iore, iowe;
  input [5:0] IO_Addr;
  input [7:0] dbus_in;
  input [3:0] pinx;
  output [7:0] dbus_out;
  output out_en;
  output [3:0] portx, ddrx;
  wire ireset, cp2, iore, iowe;
  wire [5:0] IO_Addr;
  wire [7:0] dbus_in;
  wire [3:0] pinx;
  wire [7:0] dbus_out;
  wire out_en;
  wire [3:0] portx, ddrx;
  wire [7:0] pinx_reg;
  wire UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6,
       UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6;
  wire UNCONNECTED_HIER_Z7, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire we_ddrx, we_pinx, we_portx;
  rg_md_p_width4_p_init_val0_p_impl_mask15_1 rg_md_ddrx_inst(.clk
       (cp2), .nrst (ireset), .wdata ({UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z,
       dbus_in[3:0]}), .wbe (we_ddrx), .rdata ({UNCONNECTED6,
       UNCONNECTED5, UNCONNECTED4, UNCONNECTED3, ddrx}), .tog
       (UNCONNECTED_HIER_Z3));
  rg_md_p_width4_p_init_val0_p_impl_mask15 rg_md_portx_inst(.clk (cp2),
       .nrst (ireset), .wdata ({UNCONNECTED_HIER_Z7,
       UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z4,
       dbus_in[3:0]}), .wbe (we_portx), .rdata ({UNCONNECTED10,
       UNCONNECTED9, UNCONNECTED8, UNCONNECTED7, portx}), .tog
       (we_pinx));
  synchronizer_p_width4 synchronizer_pinx_inst(.clk (cp2), .d_sync
       (pinx_reg[3:0]), .d_in (pinx));
  AO222HDV1 g518__7098(.A1 (n_5), .A2 (ddrx[3]), .B1 (n_6), .B2
       (pinx_reg[3]), .C1 (n_4), .C2 (portx[3]), .Z (dbus_out[3]));
  AO222HDV1 g519__6131(.A1 (n_5), .A2 (ddrx[2]), .B1 (n_6), .B2
       (pinx_reg[2]), .C1 (n_4), .C2 (portx[2]), .Z (dbus_out[2]));
  AO222HDV1 g520__1881(.A1 (n_5), .A2 (ddrx[0]), .B1 (n_6), .B2
       (pinx_reg[0]), .C1 (n_4), .C2 (portx[0]), .Z (dbus_out[0]));
  AO222HDV1 g521__5115(.A1 (n_5), .A2 (ddrx[1]), .B1 (n_6), .B2
       (pinx_reg[1]), .C1 (n_4), .C2 (portx[1]), .Z (dbus_out[1]));
  AND2HDV2RD g522__7482(.A1 (n_4), .A2 (iowe), .Z (we_portx));
  AND2HDV2RD g523__4733(.A1 (n_6), .A2 (iowe), .Z (we_pinx));
  AND2HDV2RD g524__6161(.A1 (n_5), .A2 (iowe), .Z (we_ddrx));
  INOR2HDV2 g525__9315(.A1 (n_3), .B1 (IO_Addr[0]), .ZN (n_6));
  AND2HDV2RD g526__9945(.A1 (n_3), .A2 (IO_Addr[0]), .Z (n_5));
  NOR3BBHDV2 g527__2883(.A1 (n_2), .A2 (IO_Addr[1]), .B (IO_Addr[0]),
       .ZN (n_4));
  INOR2HDV2 g528__2346(.A1 (n_2), .B1 (IO_Addr[1]), .ZN (n_3));
  AND3HDV2 g529__1666(.A1 (n_2), .A2 (n_0), .A3 (iore), .Z (out_en));
  NOR3HDV2 g530__7410(.A1 (n_1), .A2 (IO_Addr[4]), .A3 (IO_Addr[5]),
       .ZN (n_2));
  CLKNAND2HDV2 g531__6417(.A1 (IO_Addr[3]), .A2 (IO_Addr[2]), .ZN
       (n_1));
  NAND2HDV2 g532__5477(.A1 (IO_Addr[0]), .A2 (IO_Addr[1]), .ZN (n_0));
endmodule

module Port_E(cp2, ireset, IO_Addr, iore, iowe, out_en, dbus_in,
     dbus_out, pinE_i, DIE_o, pu_E, dd_E, pv_E, die_E, PUD, SLEEP,
     RSTDISBL, TWEN1, SPE1, MSTR, SCK1_OUT, SPI1_MT_OUT, SCL1_OUT,
     SDA1_OUT, ADCxD, PCINT, PCIE3, aco_oe, acompout);
  input cp2, ireset, iore, iowe, PUD, SLEEP, RSTDISBL, TWEN1, SPE1,
       MSTR, SCK1_OUT, SPI1_MT_OUT, SCL1_OUT, SDA1_OUT, PCIE3, aco_oe,
       acompout;
  input [5:0] IO_Addr;
  input [7:0] dbus_in;
  input [3:0] pinE_i, PCINT;
  input [1:0] ADCxD;
  output out_en;
  output [7:0] dbus_out;
  output [3:0] DIE_o, pu_E, dd_E, pv_E, die_E;
  wire cp2, ireset, iore, iowe, PUD, SLEEP, RSTDISBL, TWEN1, SPE1,
       MSTR, SCK1_OUT, SPI1_MT_OUT, SCL1_OUT, SDA1_OUT, PCIE3, aco_oe,
       acompout;
  wire [5:0] IO_Addr;
  wire [7:0] dbus_in;
  wire [3:0] pinE_i, PCINT;
  wire [1:0] ADCxD;
  wire out_en;
  wire [7:0] dbus_out;
  wire [3:0] DIE_o, pu_E, dd_E, pv_E, die_E;
  wire [3:0] portE;
  wire [3:0] ddrE;
  wire UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10,
       UNCONNECTED_HIER_Z11;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_68;
  assign DIE_o[0] = pinE_i[0];
  assign DIE_o[1] = pinE_i[1];
  assign DIE_o[2] = pinE_i[2];
  assign DIE_o[3] = pinE_i[3];
  assign dbus_out[4] = 1'b0;
  assign dbus_out[5] = 1'b0;
  assign dbus_out[6] = 1'b0;
  assign dbus_out[7] = 1'b0;
  IO_Port_PINx_Address12_DDRx_Address13_PORTx_Address14_port_width4
       IO_Port_E_inst(.ireset (ireset), .cp2 (cp2), .IO_Addr (IO_Addr),
       .dbus_in ({UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z10,
       UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z8, dbus_in[3:0]}),
       .dbus_out ({UNCONNECTED14, UNCONNECTED13, UNCONNECTED12,
       UNCONNECTED11, dbus_out[3:0]}), .iore (iore), .iowe (iowe),
       .out_en (out_en), .portx ({portE[3:1], n_68}), .ddrx (ddrE),
       .pinx (pinE_i));
  TBUFHDV0 g39__2398(.I (n_9), .OE (dd_E[3]), .Z (pv_E[3]));
  TBUFHDV0 g42__5107(.I (n_10), .OE (dd_E[0]), .Z (pv_E[0]));
  NAND3BBHDV2 g699__6260(.A1 (dd_E[2]), .A2 (PUD), .B (portE[2]), .ZN
       (pu_E[2]));
  NAND3BBHDV2 g700__4319(.A1 (dd_E[0]), .A2 (PUD), .B (n_68), .ZN
       (pu_E[0]));
  NAND3BBHDV2 g701__8428(.A1 (dd_E[3]), .A2 (PUD), .B (portE[3]), .ZN
       (pu_E[3]));
  TBUFHDV1 g40__5526(.I (portE[2]), .OE (dd_E[2]), .Z (pv_E[2]));
  TBUFHDV0 g41__6783(.I (n_8), .OE (dd_E[1]), .Z (pv_E[1]));
  IOA22HDV0 g702__3680(.A1 (n_5), .A2 (n_68), .B1 (n_5), .B2 (n_4), .ZN
       (n_10));
  NAND3BBHDV2 g703__1617(.A1 (dd_E[1]), .A2 (PUD), .B (portE[1]), .ZN
       (pu_E[1]));
  MUX2HDV2 g704__2802(.I0 (SPI1_MT_OUT), .I1 (portE[3]), .S (n_7), .Z
       (n_9));
  AND2HDV2RD g705__1705(.A1 (n_6), .A2 (ddrE[3]), .Z (dd_E[3]));
  AND2HDV2RD g706__5122(.A1 (n_6), .A2 (ddrE[2]), .Z (dd_E[2]));
  CLKMUX2HDV0 g707__8246(.I0 (portE[1]), .I1 (SCL1_OUT), .S (TWEN1), .Z
       (n_8));
  AND2HDV2RD g708__7098(.A1 (n_5), .A2 (ddrE[0]), .Z (dd_E[0]));
  CLKNAND2HDV2 g709__6131(.A1 (SPE1), .A2 (MSTR), .ZN (n_7));
  INOR2HDV2 g710__1881(.A1 (ddrE[1]), .B1 (TWEN1), .ZN (dd_E[1]));
  NOR2HDV2 g711__5115(.A1 (SDA1_OUT), .A2 (acompout), .ZN (n_4));
  INAND2HDV2 g712__7482(.A1 (MSTR), .B1 (SPE1), .ZN (n_6));
  NOR2HDV2 g713__4733(.A1 (TWEN1), .A2 (aco_oe), .ZN (n_5));
  AOI21BHDV0 g547__6161(.A (SLEEP), .B1 (PCIE3), .B2 (PCINT[1]), .ZN
       (die_E[1]));
  AOI21BHDV0 g548__9315(.A (SLEEP), .B1 (PCIE3), .B2 (PCINT[0]), .ZN
       (die_E[0]));
  IAO22HDV2 g2__9945(.A1 (ADCxD[1]), .A2 (SLEEP), .B1 (PCIE3), .B2
       (PCINT[3]), .ZN (die_E[3]));
  IAO22HDV2 g714__2883(.A1 (ADCxD[0]), .A2 (SLEEP), .B1 (PCIE3), .B2
       (PCINT[2]), .ZN (die_E[2]));
endmodule

