
// Generated by Cadence Genus(TM) Synthesis Solution 22.10-p001_1
// Generated on: Mar 12 2025 23:47:10 +07 (Mar 12 2025 16:47:10 UTC)

// Verification Directory fv/Port_C 

module rg_md_p_width7_p_init_val0_p_impl_mask127_1(clk, nrst, wdata,
     wbe, rdata, tog);
  input clk, nrst, wbe, tog;
  input [7:0] wdata;
  output [7:0] rdata;
  wire clk, nrst, wbe, tog;
  wire [7:0] wdata;
  wire [7:0] rdata;
  EDRNQHDV0 \rg_current_reg[0] (.RDN (nrst), .CK (clk), .D (wdata[0]),
       .E (wbe), .Q (rdata[0]));
  EDRNQHDV0 \rg_current_reg[3] (.RDN (nrst), .CK (clk), .D (wdata[3]),
       .E (wbe), .Q (rdata[3]));
  EDRNQHDV0 \rg_current_reg[4] (.RDN (nrst), .CK (clk), .D (wdata[4]),
       .E (wbe), .Q (rdata[4]));
  EDRNQHDV0 \rg_current_reg[1] (.RDN (nrst), .CK (clk), .D (wdata[1]),
       .E (wbe), .Q (rdata[1]));
  EDRNQHDV0 \rg_current_reg[6] (.RDN (nrst), .CK (clk), .D (wdata[6]),
       .E (wbe), .Q (rdata[6]));
  EDRNQHDV0 \rg_current_reg[5] (.RDN (nrst), .CK (clk), .D (wdata[5]),
       .E (wbe), .Q (rdata[5]));
  EDRNQHDV0 \rg_current_reg[2] (.RDN (nrst), .CK (clk), .D (wdata[2]),
       .E (wbe), .Q (rdata[2]));
endmodule

module rg_md_p_width7_p_init_val0_p_impl_mask127(clk, nrst, wdata, wbe,
     rdata, tog);
  input clk, nrst, wbe, tog;
  input [7:0] wdata;
  output [7:0] rdata;
  wire clk, nrst, wbe, tog;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7, n_8;
  wire n_9, n_10, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_36;
  DRQHDV2 \rg_current_reg[0] (.RD (n_1), .CK (clk), .D (n_20), .Q
       (rdata[0]));
  DRQHDV2 \rg_current_reg[1] (.RD (n_1), .CK (clk), .D (n_22), .Q
       (rdata[1]));
  DRQHDV2 \rg_current_reg[5] (.RD (n_1), .CK (clk), .D (n_19), .Q
       (rdata[5]));
  DRQHDV2 \rg_current_reg[6] (.RD (n_1), .CK (clk), .D (n_23), .Q
       (rdata[6]));
  DRQHDV2 \rg_current_reg[2] (.RD (n_1), .CK (clk), .D (n_24), .Q
       (rdata[2]));
  DRQHDV2 \rg_current_reg[4] (.RD (n_1), .CK (clk), .D (n_21), .Q
       (rdata[4]));
  IOA22HDV0 g880__2398(.A1 (n_13), .A2 (wdata[2]), .B1 (wbe), .B2
       (n_3), .ZN (n_24));
  IOA22HDV0 g881__5107(.A1 (n_15), .A2 (wdata[6]), .B1 (wbe), .B2
       (n_9), .ZN (n_23));
  DRQHDV2 \rg_current_reg[3] (.RD (n_1), .CK (clk), .D (n_18), .Q
       (rdata[3]));
  IOA22HDV0 g883__6260(.A1 (n_17), .A2 (wdata[1]), .B1 (wbe), .B2
       (n_7), .ZN (n_22));
  IOA22HDV0 g884__4319(.A1 (n_12), .A2 (wdata[4]), .B1 (wbe), .B2
       (n_2), .ZN (n_21));
  IOA22HDV0 g885__8428(.A1 (n_14), .A2 (wdata[0]), .B1 (wbe), .B2
       (n_4), .ZN (n_20));
  IOA22HDV0 g886__5526(.A1 (n_16), .A2 (wdata[5]), .B1 (wbe), .B2
       (n_8), .ZN (n_19));
  AO22HDV0 g887__6783(.A1 (n_36), .A2 (rdata[3]), .B1 (n_10), .B2
       (wdata[3]), .Z (n_18));
  IOA22HDV0 g888__3680(.A1 (n_0), .A2 (rdata[1]), .B1 (n_6), .B2
       (rdata[1]), .ZN (n_17));
  IOA22HDV0 g889__1617(.A1 (n_0), .A2 (rdata[5]), .B1 (n_6), .B2
       (rdata[5]), .ZN (n_16));
  IOA22HDV0 g890__2802(.A1 (n_0), .A2 (rdata[6]), .B1 (n_6), .B2
       (rdata[6]), .ZN (n_15));
  IOA22HDV0 g891__1705(.A1 (n_0), .A2 (rdata[0]), .B1 (n_6), .B2
       (rdata[0]), .ZN (n_14));
  IOA22HDV0 g892__5122(.A1 (n_0), .A2 (rdata[2]), .B1 (n_6), .B2
       (rdata[2]), .ZN (n_13));
  IOA22HDV0 g893__8246(.A1 (n_0), .A2 (rdata[4]), .B1 (n_6), .B2
       (rdata[4]), .ZN (n_12));
  IOA22HDV0 g895__6131(.A1 (wbe), .A2 (n_0), .B1 (n_0), .B2 (rdata[3]),
       .ZN (n_10));
  INAND2HDV2 g896__1881(.A1 (wdata[6]), .B1 (rdata[6]), .ZN (n_9));
  INAND2HDV2 g897__5115(.A1 (wdata[5]), .B1 (rdata[5]), .ZN (n_8));
  INAND2HDV2 g898__7482(.A1 (wdata[1]), .B1 (rdata[1]), .ZN (n_7));
  INAND2HDV2 g900__4733(.A1 (wdata[0]), .B1 (rdata[0]), .ZN (n_4));
  INAND2HDV2 g901__6161(.A1 (wdata[2]), .B1 (rdata[2]), .ZN (n_3));
  INAND2HDV2 g902__9315(.A1 (wdata[4]), .B1 (rdata[4]), .ZN (n_2));
  NOR2HDV2 g903__9945(.A1 (wbe), .A2 (tog), .ZN (n_6));
  INHDV1 g904(.I (nrst), .ZN (n_1));
  INHDV1 g905(.I (tog), .ZN (n_0));
  OAI21BHDV2 g2(.A (n_6), .B1 (wbe), .B2 (wdata[3]), .ZN (n_36));
endmodule

module synchronizer_p_width7(clk, d_sync, d_in);
  input clk;
  input [6:0] d_in;
  output [6:0] d_sync;
  wire clk;
  wire [6:0] d_in;
  wire [6:0] d_sync;
  wire [6:0] d_latch;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5;
  DQHDV2 \d_sync_int_reg[6] (.CK (clk), .D (d_latch[6]), .Q
       (d_sync[6]));
  DQHDV2 \d_sync_int_reg[5] (.CK (clk), .D (d_latch[5]), .Q
       (d_sync[5]));
  DQHDV2 \d_sync_int_reg[3] (.CK (clk), .D (d_latch[3]), .Q
       (d_sync[3]));
  DQHDV2 \d_sync_int_reg[1] (.CK (clk), .D (d_latch[1]), .Q
       (d_sync[1]));
  DQHDV2 \d_sync_int_reg[4] (.CK (clk), .D (d_latch[4]), .Q
       (d_sync[4]));
  DQHDV2 \d_sync_int_reg[2] (.CK (clk), .D (d_latch[2]), .Q
       (d_sync[2]));
  DQHDV2 \d_sync_int_reg[0] (.CK (clk), .D (d_latch[0]), .Q
       (d_sync[0]));
  LAHHDV0 \d_latch_reg[6] (.E (clk), .D (d_in[6]), .Q (d_latch[6]), .QN
       (UNCONNECTED));
  LAHHDV0 \d_latch_reg[0] (.E (clk), .D (d_in[0]), .Q (d_latch[0]), .QN
       (UNCONNECTED0));
  LAHHDV0 \d_latch_reg[1] (.E (clk), .D (d_in[1]), .Q (d_latch[1]), .QN
       (UNCONNECTED1));
  LAHHDV0 \d_latch_reg[5] (.E (clk), .D (d_in[5]), .Q (d_latch[5]), .QN
       (UNCONNECTED2));
  LAHHDV0 \d_latch_reg[4] (.E (clk), .D (d_in[4]), .Q (d_latch[4]), .QN
       (UNCONNECTED3));
  LAHHDV0 \d_latch_reg[3] (.E (clk), .D (d_in[3]), .Q (d_latch[3]), .QN
       (UNCONNECTED4));
  LAHHDV0 \d_latch_reg[2] (.E (clk), .D (d_in[2]), .Q (d_latch[2]), .QN
       (UNCONNECTED5));
endmodule

module
     IO_Port_PINx_Address6_DDRx_Address7_PORTx_Address8_port_width7(ireset,
     cp2, IO_Addr, dbus_in, dbus_out, iore, iowe, out_en, portx, ddrx,
     pinx);
  input ireset, cp2, iore, iowe;
  input [5:0] IO_Addr;
  input [7:0] dbus_in;
  input [6:0] pinx;
  output [7:0] dbus_out;
  output out_en;
  output [6:0] portx, ddrx;
  wire ireset, cp2, iore, iowe;
  wire [5:0] IO_Addr;
  wire [7:0] dbus_in;
  wire [6:0] pinx;
  wire [7:0] dbus_out;
  wire out_en;
  wire [6:0] portx, ddrx;
  wire [7:0] pinx_reg;
  wire UNCONNECTED6, UNCONNECTED7, UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, we_ddrx, we_pinx;
  wire we_portx;
  rg_md_p_width7_p_init_val0_p_impl_mask127_1 rg_md_ddrx_inst(.clk
       (cp2), .nrst (ireset), .wdata ({UNCONNECTED_HIER_Z,
       dbus_in[6:0]}), .wbe (we_ddrx), .rdata ({UNCONNECTED6, ddrx}),
       .tog (UNCONNECTED_HIER_Z0));
  rg_md_p_width7_p_init_val0_p_impl_mask127 rg_md_portx_inst(.clk
       (cp2), .nrst (ireset), .wdata ({UNCONNECTED_HIER_Z1,
       dbus_in[6:0]}), .wbe (we_portx), .rdata ({UNCONNECTED7, portx}),
       .tog (we_pinx));
  synchronizer_p_width7 synchronizer_pinx_inst(.clk (cp2), .d_sync
       (pinx_reg[6:0]), .d_in (pinx));
  AO222HDV1 g665__2883(.A1 (n_6), .A2 (ddrx[6]), .B1 (n_8), .B2
       (portx[6]), .C1 (n_3), .C2 (pinx_reg[6]), .Z (dbus_out[6]));
  AO222HDV1 g666__2346(.A1 (n_6), .A2 (ddrx[4]), .B1 (n_8), .B2
       (portx[4]), .C1 (n_3), .C2 (pinx_reg[4]), .Z (dbus_out[4]));
  AO222HDV1 g667__1666(.A1 (n_6), .A2 (ddrx[0]), .B1 (n_8), .B2
       (portx[0]), .C1 (n_3), .C2 (pinx_reg[0]), .Z (dbus_out[0]));
  AO222HDV1 g668__7410(.A1 (n_6), .A2 (ddrx[2]), .B1 (n_8), .B2
       (portx[2]), .C1 (n_3), .C2 (pinx_reg[2]), .Z (dbus_out[2]));
  AO222HDV1 g669__6417(.A1 (n_6), .A2 (ddrx[5]), .B1 (n_8), .B2
       (portx[5]), .C1 (n_3), .C2 (pinx_reg[5]), .Z (dbus_out[5]));
  AO222HDV1 g670__5477(.A1 (n_6), .A2 (ddrx[3]), .B1 (n_8), .B2
       (portx[3]), .C1 (n_3), .C2 (pinx_reg[3]), .Z (dbus_out[3]));
  AO222HDV1 g671__2398(.A1 (n_6), .A2 (ddrx[1]), .B1 (n_8), .B2
       (portx[1]), .C1 (n_3), .C2 (pinx_reg[1]), .Z (dbus_out[1]));
  AOI21BHDV0 g672__5107(.A (iore), .B1 (n_7), .B2 (n_4), .ZN (out_en));
  AND2HDV2RD g673__6260(.A1 (n_8), .A2 (iowe), .Z (we_portx));
  AND2HDV2RD g674__4319(.A1 (n_6), .A2 (iowe), .Z (we_ddrx));
  INHDV0 g675(.I (n_8), .ZN (n_7));
  NOR3HDV2 g676__8428(.A1 (n_5), .A2 (IO_Addr[1]), .A3 (IO_Addr[2]),
       .ZN (n_8));
  INOR2HDV2 g677__5526(.A1 (IO_Addr[0]), .B1 (n_4), .ZN (n_6));
  AND2HDV2RD g678__6783(.A1 (n_3), .A2 (iowe), .Z (we_pinx));
  NAND2HDV2 g679__3680(.A1 (n_2), .A2 (IO_Addr[3]), .ZN (n_5));
  CLKNAND2HDV2 g680__1617(.A1 (n_1), .A2 (n_0), .ZN (n_4));
  AND2HDV2RD g681__2802(.A1 (n_2), .A2 (n_1), .Z (n_3));
  INOR2HDV2 g682__1705(.A1 (n_0), .B1 (IO_Addr[0]), .ZN (n_2));
  NOR3BBHDV2 g683__5122(.A1 (IO_Addr[2]), .A2 (IO_Addr[1]), .B
       (IO_Addr[3]), .ZN (n_1));
  NOR2HDV2 g684__8246(.A1 (IO_Addr[5]), .A2 (IO_Addr[4]), .ZN (n_0));
endmodule

module Port_C(cp2, ireset, IO_Addr, iore, iowe, out_en, dbus_in,
     dbus_out, pinC_i, DIC_o, pu_C, dd_C, pv_C, die_C, PUD, SLEEP,
     RSTDISBL, TWEN0, SPE1, MSTR, SCK1_OUT, SPI1_SL_OUT, SCL0_OUT,
     SDA0_OUT, ADCxD, PCINT, PCIE1);
  input cp2, ireset, iore, iowe, PUD, SLEEP, RSTDISBL, TWEN0, SPE1,
       MSTR, SCK1_OUT, SPI1_SL_OUT, SCL0_OUT, SDA0_OUT, PCIE1;
  input [5:0] IO_Addr, ADCxD;
  input [7:0] dbus_in;
  input [6:0] pinC_i, PCINT;
  output out_en;
  output [7:0] dbus_out;
  output [6:0] DIC_o, pu_C, dd_C, pv_C, die_C;
  wire cp2, ireset, iore, iowe, PUD, SLEEP, RSTDISBL, TWEN0, SPE1,
       MSTR, SCK1_OUT, SPI1_SL_OUT, SCL0_OUT, SDA0_OUT, PCIE1;
  wire [5:0] IO_Addr, ADCxD;
  wire [7:0] dbus_in;
  wire [6:0] pinC_i, PCINT;
  wire out_en;
  wire [7:0] dbus_out;
  wire [6:0] DIC_o, pu_C, dd_C, pv_C, die_C;
  wire [6:0] portC;
  wire [6:0] ddrC;
  wire UNCONNECTED8, UNCONNECTED_HIER_Z2, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  assign DIC_o[0] = pinC_i[0];
  assign DIC_o[1] = pinC_i[1];
  assign DIC_o[2] = pinC_i[2];
  assign DIC_o[3] = pinC_i[3];
  assign DIC_o[4] = pinC_i[4];
  assign DIC_o[5] = pinC_i[5];
  assign DIC_o[6] = pinC_i[6];
  assign dbus_out[7] = 1'b0;
  IO_Port_PINx_Address6_DDRx_Address7_PORTx_Address8_port_width7
       IO_Port_C_inst(.ireset (ireset), .cp2 (cp2), .IO_Addr (IO_Addr),
       .dbus_in ({UNCONNECTED_HIER_Z2, dbus_in[6:0]}), .dbus_out
       ({UNCONNECTED8, dbus_out[6:0]}), .iore (iore), .iowe (iowe),
       .out_en (out_en), .portx (portC), .ddrx ({ddrC[6:4], dd_C[3:2],
       ddrC[1:0]}), .pinx (pinC_i));
  OAI221HDV1 g1228__7098(.A1 (n_12), .A2 (PCINT[5]), .B1 (n_4), .B2
       (PCIE1), .C (n_13), .ZN (die_C[5]));
  TBUFHDV0 g61__6131(.I (n_21), .OE (dd_C[0]), .Z (pv_C[0]));
  TBUFHDV0 g60__1881(.I (n_20), .OE (dd_C[1]), .Z (pv_C[1]));
  OAI221HDV1 g1229__5115(.A1 (n_10), .A2 (PCINT[4]), .B1 (n_1), .B2
       (PCIE1), .C (n_13), .ZN (die_C[4]));
  OAI221HDV1 g1230__7482(.A1 (n_8), .A2 (PCINT[3]), .B1 (n_3), .B2
       (PCIE1), .C (n_13), .ZN (die_C[3]));
  OAI221HDV1 g1231__4733(.A1 (n_11), .A2 (PCINT[0]), .B1 (n_5), .B2
       (PCIE1), .C (n_13), .ZN (die_C[0]));
  OAI221HDV1 g1232__6161(.A1 (n_9), .A2 (PCINT[1]), .B1 (n_2), .B2
       (PCIE1), .C (n_13), .ZN (die_C[1]));
  OAI221HDV1 g1233__9315(.A1 (n_7), .A2 (PCINT[2]), .B1 (n_6), .B2
       (PCIE1), .C (n_13), .ZN (die_C[2]));
  NAND3BBHDV2 g1234__9945(.A1 (dd_C[0]), .A2 (PUD), .B (portC[0]), .ZN
       (pu_C[0]));
  NAND3BBHDV2 g1235__2883(.A1 (dd_C[1]), .A2 (PUD), .B (portC[1]), .ZN
       (pu_C[1]));
  NOR2HDV2 g1236__2346(.A1 (n_18), .A2 (RSTDISBL), .ZN (pu_C[6]));
  TBUFHDV0 g57__1666(.I (n_16), .OE (dd_C[4]), .Z (pv_C[4]));
  TBUFHDV0 g56__7410(.I (n_17), .OE (dd_C[5]), .Z (pv_C[5]));
  NOR2HDV2 g1237__6417(.A1 (n_19), .A2 (RSTDISBL), .ZN (die_C[6]));
  MUX2HDV2 g1238__5477(.I0 (SPI1_SL_OUT), .I1 (portC[0]), .S (n_14), .Z
       (n_21));
  NAND3BBHDV2 g1239__2398(.A1 (dd_C[4]), .A2 (PUD), .B (portC[4]), .ZN
       (pu_C[4]));
  NAND3BBHDV2 g1240__5107(.A1 (dd_C[5]), .A2 (PUD), .B (portC[5]), .ZN
       (pu_C[5]));
  MUX2HDV2 g1241__6260(.I0 (SCK1_OUT), .I1 (portC[1]), .S (n_15), .Z
       (n_20));
  TBUFHDV1 g55__4319(.I (portC[6]), .OE (dd_C[6]), .Z (pv_C[6]));
  AOI21HDV2 g1242__8428(.A1 (PCIE1), .A2 (PCINT[6]), .B (SLEEP), .ZN
       (n_19));
  AND2HDV2RD g1243__5526(.A1 (n_14), .A2 (ddrC[1]), .Z (dd_C[1]));
  AND2HDV2RD g1244__6783(.A1 (n_15), .A2 (ddrC[0]), .Z (dd_C[0]));
  INOR3HDV1 g1245__3680(.A1 (portC[6]), .B1 (PUD), .B2 (ddrC[6]), .ZN
       (n_18));
  NAND3BBHDV2 g1246__1617(.A1 (PUD), .A2 (dd_C[2]), .B (portC[2]), .ZN
       (pu_C[2]));
  NAND3BBHDV2 g1247__2802(.A1 (PUD), .A2 (dd_C[3]), .B (portC[3]), .ZN
       (pu_C[3]));
  AO22HDV0 g1248__1705(.A1 (n_0), .A2 (portC[5]), .B1 (TWEN0), .B2
       (SCL0_OUT), .Z (n_17));
  AO22HDV0 g1249__5122(.A1 (n_0), .A2 (portC[4]), .B1 (TWEN0), .B2
       (SDA0_OUT), .Z (n_16));
  TBUFHDV0 g58__8246(.I (portC[3]), .OE (dd_C[3]), .Z (pv_C[3]));
  TBUFHDV0 g59__7098(.I (portC[2]), .OE (dd_C[2]), .Z (pv_C[2]));
  NOR2HDV2 g1250__6131(.A1 (SLEEP), .A2 (ADCxD[5]), .ZN (n_12));
  AND2HDV2RD g1251__1881(.A1 (n_0), .A2 (ddrC[4]), .Z (dd_C[4]));
  CLKNAND2HDV2 g1252__5115(.A1 (SPE1), .A2 (MSTR), .ZN (n_15));
  INAND2HDV2 g1253__7482(.A1 (MSTR), .B1 (SPE1), .ZN (n_14));
  INAND2HDV2 g1254__4733(.A1 (PCIE1), .B1 (SLEEP), .ZN (n_13));
  NOR2HDV2 g1255__6161(.A1 (SLEEP), .A2 (ADCxD[0]), .ZN (n_11));
  NOR2HDV2 g1256__9315(.A1 (SLEEP), .A2 (ADCxD[4]), .ZN (n_10));
  NOR2HDV2 g1257__9945(.A1 (SLEEP), .A2 (ADCxD[1]), .ZN (n_9));
  NOR2HDV2 g1258__2883(.A1 (SLEEP), .A2 (ADCxD[3]), .ZN (n_8));
  NOR2HDV2 g1259__2346(.A1 (SLEEP), .A2 (ADCxD[2]), .ZN (n_7));
  INOR2HDV2 g1260__1666(.A1 (ddrC[6]), .B1 (RSTDISBL), .ZN (dd_C[6]));
  AND2HDV2RD g1261__7410(.A1 (n_0), .A2 (ddrC[5]), .Z (dd_C[5]));
  INHDV0 g1262(.I (ADCxD[2]), .ZN (n_6));
  INHDV0 g1263(.I (ADCxD[0]), .ZN (n_5));
  INHDV0 g1264(.I (ADCxD[5]), .ZN (n_4));
  INHDV0 g1265(.I (ADCxD[3]), .ZN (n_3));
  INHDV0 g1266(.I (ADCxD[1]), .ZN (n_2));
  INHDV0 g1267(.I (ADCxD[4]), .ZN (n_1));
  INHDV1 g1268(.I (TWEN0), .ZN (n_0));
endmodule

