
// Generated by Cadence Genus(TM) Synthesis Solution 22.10-p001_1
// Generated on: Mar 12 2025 23:45:48 +07 (Mar 12 2025 16:45:48 UTC)

// Verification Directory fv/Port_B 

module rg_md_p_width8_p_init_val0_p_impl_mask255_1(clk, nrst, wdata,
     wbe, rdata, tog);
  input clk, nrst, wbe, tog;
  input [7:0] wdata;
  output [7:0] rdata;
  wire clk, nrst, wbe, tog;
  wire [7:0] wdata;
  wire [7:0] rdata;
  EDRNQHDV0 \rg_current_reg[3] (.RDN (nrst), .CK (clk), .D (wdata[3]),
       .E (wbe), .Q (rdata[3]));
  EDRNQHDV0 \rg_current_reg[2] (.RDN (nrst), .CK (clk), .D (wdata[2]),
       .E (wbe), .Q (rdata[2]));
  EDRNQHDV0 \rg_current_reg[0] (.RDN (nrst), .CK (clk), .D (wdata[0]),
       .E (wbe), .Q (rdata[0]));
  EDRNQHDV0 \rg_current_reg[4] (.RDN (nrst), .CK (clk), .D (wdata[4]),
       .E (wbe), .Q (rdata[4]));
  EDRNQHDV0 \rg_current_reg[6] (.RDN (nrst), .CK (clk), .D (wdata[6]),
       .E (wbe), .Q (rdata[6]));
  EDRNQHDV0 \rg_current_reg[1] (.RDN (nrst), .CK (clk), .D (wdata[1]),
       .E (wbe), .Q (rdata[1]));
  EDRNQHDV0 \rg_current_reg[5] (.RDN (nrst), .CK (clk), .D (wdata[5]),
       .E (wbe), .Q (rdata[5]));
  EDRNQHDV0 \rg_current_reg[7] (.RDN (nrst), .CK (clk), .D (wdata[7]),
       .E (wbe), .Q (rdata[7]));
endmodule

module rg_md_p_width8_p_init_val0_p_impl_mask255(clk, nrst, wdata, wbe,
     rdata, tog);
  input clk, nrst, wbe, tog;
  input [7:0] wdata;
  output [7:0] rdata;
  wire clk, nrst, wbe, tog;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_41;
  DRQHDV2 \rg_current_reg[0] (.RD (n_1), .CK (clk), .D (n_23), .Q
       (rdata[0]));
  DRQHDV2 \rg_current_reg[1] (.RD (n_1), .CK (clk), .D (n_22), .Q
       (rdata[1]));
  DRQHDV2 \rg_current_reg[5] (.RD (n_1), .CK (clk), .D (n_27), .Q
       (rdata[5]));
  DRQHDV2 \rg_current_reg[3] (.RD (n_1), .CK (clk), .D (n_24), .Q
       (rdata[3]));
  DRQHDV2 \rg_current_reg[7] (.RD (n_1), .CK (clk), .D (n_26), .Q
       (rdata[7]));
  DRQHDV2 \rg_current_reg[6] (.RD (n_1), .CK (clk), .D (n_28), .Q
       (rdata[6]));
  DRQHDV2 \rg_current_reg[4] (.RD (n_1), .CK (clk), .D (n_25), .Q
       (rdata[4]));
  IOA22HDV0 g1026__2398(.A1 (n_19), .A2 (wdata[6]), .B1 (wbe), .B2
       (n_3), .ZN (n_28));
  IOA22HDV0 g1027__5107(.A1 (n_20), .A2 (wdata[5]), .B1 (wbe), .B2
       (n_4), .ZN (n_27));
  IOA22HDV0 g1028__6260(.A1 (n_15), .A2 (wdata[7]), .B1 (wbe), .B2
       (n_11), .ZN (n_26));
  DRQHDV2 \rg_current_reg[2] (.RD (n_1), .CK (clk), .D (n_21), .Q
       (rdata[2]));
  IOA22HDV0 g1030__4319(.A1 (n_14), .A2 (wdata[4]), .B1 (wbe), .B2
       (n_5), .ZN (n_25));
  IOA22HDV0 g1031__8428(.A1 (n_17), .A2 (wdata[3]), .B1 (wbe), .B2
       (n_8), .ZN (n_24));
  IOA22HDV0 g1032__5526(.A1 (n_16), .A2 (wdata[0]), .B1 (wbe), .B2
       (n_10), .ZN (n_23));
  IOA22HDV0 g1033__6783(.A1 (n_18), .A2 (wdata[1]), .B1 (wbe), .B2
       (n_9), .ZN (n_22));
  AO22HDV0 g1034__3680(.A1 (n_41), .A2 (rdata[2]), .B1 (n_12), .B2
       (wdata[2]), .Z (n_21));
  IOA22HDV0 g1035__1617(.A1 (n_0), .A2 (rdata[5]), .B1 (n_7), .B2
       (rdata[5]), .ZN (n_20));
  IOA22HDV0 g1036__2802(.A1 (n_0), .A2 (rdata[6]), .B1 (n_7), .B2
       (rdata[6]), .ZN (n_19));
  IOA22HDV0 g1037__1705(.A1 (n_0), .A2 (rdata[1]), .B1 (n_7), .B2
       (rdata[1]), .ZN (n_18));
  IOA22HDV0 g1038__5122(.A1 (n_0), .A2 (rdata[3]), .B1 (n_7), .B2
       (rdata[3]), .ZN (n_17));
  IOA22HDV0 g1039__8246(.A1 (n_0), .A2 (rdata[0]), .B1 (n_7), .B2
       (rdata[0]), .ZN (n_16));
  IOA22HDV0 g1040__7098(.A1 (n_0), .A2 (rdata[7]), .B1 (n_7), .B2
       (rdata[7]), .ZN (n_15));
  IOA22HDV0 g1041__6131(.A1 (n_0), .A2 (rdata[4]), .B1 (n_7), .B2
       (rdata[4]), .ZN (n_14));
  OAI22HDV0 g1043__5115(.A1 (n_2), .A2 (tog), .B1 (n_0), .B2
       (rdata[2]), .ZN (n_12));
  INAND2HDV2 g1044__7482(.A1 (wdata[7]), .B1 (rdata[7]), .ZN (n_11));
  INAND2HDV2 g1045__4733(.A1 (wdata[0]), .B1 (rdata[0]), .ZN (n_10));
  INAND2HDV2 g1046__6161(.A1 (wdata[1]), .B1 (rdata[1]), .ZN (n_9));
  INAND2HDV2 g1047__9315(.A1 (wdata[3]), .B1 (rdata[3]), .ZN (n_8));
  INAND2HDV2 g1049__9945(.A1 (wdata[4]), .B1 (rdata[4]), .ZN (n_5));
  INAND2HDV2 g1050__2883(.A1 (wdata[5]), .B1 (rdata[5]), .ZN (n_4));
  INAND2HDV2 g1051__2346(.A1 (wdata[6]), .B1 (rdata[6]), .ZN (n_3));
  NOR2HDV2 g1052__1666(.A1 (wbe), .A2 (tog), .ZN (n_7));
  INHDV0 g1053(.I (wbe), .ZN (n_2));
  INHDV1 g1054(.I (nrst), .ZN (n_1));
  INHDV1 g1055(.I (tog), .ZN (n_0));
  OAI21BHDV2 g2(.A (n_7), .B1 (wbe), .B2 (wdata[2]), .ZN (n_41));
endmodule

module synchronizer_p_width8(clk, d_sync, d_in);
  input clk;
  input [7:0] d_in;
  output [7:0] d_sync;
  wire clk;
  wire [7:0] d_in;
  wire [7:0] d_sync;
  wire [7:0] d_latch;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  DQHDV2 \d_sync_int_reg[4] (.CK (clk), .D (d_latch[4]), .Q
       (d_sync[4]));
  DQHDV2 \d_sync_int_reg[6] (.CK (clk), .D (d_latch[6]), .Q
       (d_sync[6]));
  DQHDV2 \d_sync_int_reg[7] (.CK (clk), .D (d_latch[7]), .Q
       (d_sync[7]));
  DQHDV2 \d_sync_int_reg[0] (.CK (clk), .D (d_latch[0]), .Q
       (d_sync[0]));
  DQHDV2 \d_sync_int_reg[2] (.CK (clk), .D (d_latch[2]), .Q
       (d_sync[2]));
  DQHDV2 \d_sync_int_reg[5] (.CK (clk), .D (d_latch[5]), .Q
       (d_sync[5]));
  DQHDV2 \d_sync_int_reg[3] (.CK (clk), .D (d_latch[3]), .Q
       (d_sync[3]));
  DQHDV2 \d_sync_int_reg[1] (.CK (clk), .D (d_latch[1]), .Q
       (d_sync[1]));
  LAHHDV0 \d_latch_reg[0] (.E (clk), .D (d_in[0]), .Q (d_latch[0]), .QN
       (UNCONNECTED));
  LAHHDV0 \d_latch_reg[6] (.E (clk), .D (d_in[6]), .Q (d_latch[6]), .QN
       (UNCONNECTED0));
  LAHHDV0 \d_latch_reg[4] (.E (clk), .D (d_in[4]), .Q (d_latch[4]), .QN
       (UNCONNECTED1));
  LAHHDV0 \d_latch_reg[1] (.E (clk), .D (d_in[1]), .Q (d_latch[1]), .QN
       (UNCONNECTED2));
  LAHHDV0 \d_latch_reg[5] (.E (clk), .D (d_in[5]), .Q (d_latch[5]), .QN
       (UNCONNECTED3));
  LAHHDV0 \d_latch_reg[3] (.E (clk), .D (d_in[3]), .Q (d_latch[3]), .QN
       (UNCONNECTED4));
  LAHHDV0 \d_latch_reg[2] (.E (clk), .D (d_in[2]), .Q (d_latch[2]), .QN
       (UNCONNECTED5));
  LAHHDV0 \d_latch_reg[7] (.E (clk), .D (d_in[7]), .Q (d_latch[7]), .QN
       (UNCONNECTED6));
endmodule

module
     IO_Port_PINx_Address3_DDRx_Address4_PORTx_Address5_port_width8(ireset,
     cp2, IO_Addr, dbus_in, dbus_out, iore, iowe, out_en, portx, ddrx,
     pinx);
  input ireset, cp2, iore, iowe;
  input [5:0] IO_Addr;
  input [7:0] dbus_in, pinx;
  output [7:0] dbus_out, portx, ddrx;
  output out_en;
  wire ireset, cp2, iore, iowe;
  wire [5:0] IO_Addr;
  wire [7:0] dbus_in, pinx;
  wire [7:0] dbus_out, portx, ddrx;
  wire out_en;
  wire [7:0] pinx_reg;
  wire UNCONNECTED_HIER_Z, n_0, n_1, n_2, n_3, n_4, n_5, we_ddrx;
  wire we_pinx, we_portx;
  rg_md_p_width8_p_init_val0_p_impl_mask255_1 rg_md_ddrx_inst(.clk
       (cp2), .nrst (ireset), .wdata (dbus_in), .wbe (we_ddrx), .rdata
       (ddrx), .tog (UNCONNECTED_HIER_Z));
  rg_md_p_width8_p_init_val0_p_impl_mask255 rg_md_portx_inst(.clk
       (cp2), .nrst (ireset), .wdata (dbus_in), .wbe (we_portx), .rdata
       (portx), .tog (we_pinx));
  synchronizer_p_width8 synchronizer_pinx_inst(.clk (cp2), .d_sync
       (pinx_reg), .d_in (pinx));
  AO222HDV1 g649__7410(.A1 (n_3), .A2 (pinx_reg[1]), .B1 (n_4), .B2
       (ddrx[1]), .C1 (n_5), .C2 (portx[1]), .Z (dbus_out[1]));
  AO222HDV1 g650__6417(.A1 (n_5), .A2 (portx[5]), .B1 (n_4), .B2
       (ddrx[5]), .C1 (n_3), .C2 (pinx_reg[5]), .Z (dbus_out[5]));
  AO222HDV1 g651__5477(.A1 (n_5), .A2 (portx[7]), .B1 (n_4), .B2
       (ddrx[7]), .C1 (n_3), .C2 (pinx_reg[7]), .Z (dbus_out[7]));
  AO222HDV1 g652__2398(.A1 (n_5), .A2 (portx[0]), .B1 (n_4), .B2
       (ddrx[0]), .C1 (n_3), .C2 (pinx_reg[0]), .Z (dbus_out[0]));
  AO222HDV1 g653__5107(.A1 (n_3), .A2 (pinx_reg[3]), .B1 (n_4), .B2
       (ddrx[3]), .C1 (n_5), .C2 (portx[3]), .Z (dbus_out[3]));
  AO222HDV1 g654__6260(.A1 (n_5), .A2 (portx[6]), .B1 (n_4), .B2
       (ddrx[6]), .C1 (n_3), .C2 (pinx_reg[6]), .Z (dbus_out[6]));
  AO222HDV1 g655__4319(.A1 (n_3), .A2 (pinx_reg[4]), .B1 (n_4), .B2
       (ddrx[4]), .C1 (n_5), .C2 (portx[4]), .Z (dbus_out[4]));
  AO222HDV1 g656__8428(.A1 (n_3), .A2 (pinx_reg[2]), .B1 (n_4), .B2
       (ddrx[2]), .C1 (n_5), .C2 (portx[2]), .Z (dbus_out[2]));
  AOI21BHDV0 g657__5526(.A (iore), .B1 (n_2), .B2 (n_1), .ZN (out_en));
  AND2HDV2RD g658__6783(.A1 (n_5), .A2 (iowe), .Z (we_portx));
  AND2HDV2RD g659__3680(.A1 (n_4), .A2 (iowe), .Z (we_ddrx));
  AND2HDV2RD g660__1617(.A1 (n_3), .A2 (iowe), .Z (we_pinx));
  INOR2HDV2 g661__2802(.A1 (IO_Addr[0]), .B1 (n_1), .ZN (n_5));
  INHDV2 g662(.I (n_2), .ZN (n_3));
  NOR2HDV2 g663__1705(.A1 (n_1), .A2 (IO_Addr[0]), .ZN (n_4));
  INAND4HDV2 g664__5122(.A1 (IO_Addr[2]), .B1 (n_0), .B2 (IO_Addr[0]),
       .B3 (IO_Addr[1]), .ZN (n_2));
  INAND3HDV2 g665__8246(.A1 (IO_Addr[1]), .B1 (n_0), .B2 (IO_Addr[2]),
       .ZN (n_1));
  NOR3HDV2 g666__7098(.A1 (IO_Addr[3]), .A2 (IO_Addr[4]), .A3
       (IO_Addr[5]), .ZN (n_0));
endmodule

module Port_B(cp2, ireset, IO_Addr, iore, iowe, out_en, dbus_in,
     dbus_out, pinB_i, DIB_o, DDR_XCK1, pu_B, dd_B, pv_B, die_B, PUD,
     SLEEP, INTRC, EXTCK, AS2, SPE0, MSTR, RXEN1, TXEN1, OC2A_EN,
     OC1B_EN, OC1A_EN, SCK0_OUT, XCK1_OUT, SPI0_SL_OUT, OC2A, OC1B,
     OC1A, SPI0_MT_OUT, UMSEL, TXD1, PCINT, PCIE0);
  input cp2, ireset, iore, iowe, PUD, SLEEP, INTRC, EXTCK, AS2, SPE0,
       MSTR, RXEN1, TXEN1, OC2A_EN, OC1B_EN, OC1A_EN, SCK0_OUT,
       XCK1_OUT, SPI0_SL_OUT, OC2A, OC1B, OC1A, SPI0_MT_OUT, UMSEL,
       TXD1, PCIE0;
  input [5:0] IO_Addr;
  input [7:0] dbus_in, pinB_i, PCINT;
  output out_en, DDR_XCK1;
  output [7:0] dbus_out, DIB_o, pu_B, dd_B, pv_B, die_B;
  wire cp2, ireset, iore, iowe, PUD, SLEEP, INTRC, EXTCK, AS2, SPE0,
       MSTR, RXEN1, TXEN1, OC2A_EN, OC1B_EN, OC1A_EN, SCK0_OUT,
       XCK1_OUT, SPI0_SL_OUT, OC2A, OC1B, OC1A, SPI0_MT_OUT, UMSEL,
       TXD1, PCIE0;
  wire [5:0] IO_Addr;
  wire [7:0] dbus_in, pinB_i, PCINT;
  wire out_en, DDR_XCK1;
  wire [7:0] dbus_out, DIB_o, pu_B, dd_B, pv_B, die_B;
  wire [7:0] portB;
  wire [7:0] ddrB;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17;
  assign DIB_o[0] = pinB_i[0];
  assign DIB_o[1] = pinB_i[1];
  assign DIB_o[2] = pinB_i[2];
  assign DIB_o[3] = pinB_i[3];
  assign DIB_o[4] = pinB_i[4];
  assign DIB_o[5] = pinB_i[5];
  assign DIB_o[6] = pinB_i[6];
  assign DIB_o[7] = pinB_i[7];
  IO_Port_PINx_Address3_DDRx_Address4_PORTx_Address5_port_width8
       IO_Port_B_inst(.ireset (ireset), .cp2 (cp2), .IO_Addr (IO_Addr),
       .dbus_in (dbus_in), .dbus_out (dbus_out), .iore (iore), .iowe
       (iowe), .out_en (out_en), .portx (portB), .ddrx ({ddrB[7:6],
       DDR_XCK1, ddrB[4:2], dd_B[1:0]}), .pinx (pinB_i));
  TBUFHDV0 g82__6131(.I (n_17), .OE (dd_B[5]), .Z (pv_B[5]));
  TBUFHDV0 g84__1881(.I (n_16), .OE (dd_B[3]), .Z (pv_B[3]));
  OAI211HDV2 g1532__5115(.A1 (n_12), .A2 (TXEN1), .B (n_0), .C
       (portB[3]), .ZN (pu_B[3]));
  NAND2HDV2 g1533__7482(.A1 (n_15), .A2 (n_0), .ZN (pu_B[6]));
  TBUFHDV1 g80__4733(.I (portB[7]), .OE (dd_B[7]), .Z (pv_B[7]));
  TBUFHDV0 g83__6161(.I (n_14), .OE (dd_B[4]), .Z (pv_B[4]));
  INAND3HDV2 g1534__9315(.A1 (AS2), .B1 (n_8), .B2 (INTRC), .ZN
       (die_B[6]));
  INAND4HDV2 g1535__9945(.A1 (ddrB[7]), .B1 (n_10), .B2 (n_0), .B3
       (portB[7]), .ZN (pu_B[7]));
  INAND3HDV2 g1536__2883(.A1 (dd_B[4]), .B1 (n_0), .B2 (portB[4]), .ZN
       (pu_B[4]));
  INAND3HDV2 g1537__2346(.A1 (dd_B[2]), .B1 (n_0), .B2 (portB[2]), .ZN
       (pu_B[2]));
  INAND3HDV2 g1538__1666(.A1 (dd_B[5]), .B1 (n_0), .B2 (portB[5]), .ZN
       (pu_B[5]));
  IOA22HDV0 g1539__7410(.A1 (n_13), .A2 (portB[5]), .B1 (n_13), .B2
       (n_5), .ZN (n_17));
  IOA22HDV0 g1540__6417(.A1 (n_11), .A2 (portB[3]), .B1 (n_11), .B2
       (n_9), .ZN (n_16));
  TBUFHDV1 g81__5477(.I (portB[6]), .OE (dd_B[6]), .Z (pv_B[6]));
  TBUFHDV0 g86__2398(.I (n_7), .OE (dd_B[1]), .Z (pv_B[1]));
  TBUFHDV1 g85__5107(.I (n_6), .OE (dd_B[2]), .Z (pv_B[2]));
  AND2HDV2RD g1541__6260(.A1 (n_10), .A2 (ddrB[7]), .Z (dd_B[7]));
  AOAI211HDV1 g1542__4319(.A1 (PCIE0), .A2 (PCINT[7]), .B (n_1), .C
       (n_10), .ZN (die_B[7]));
  INOR4HDV2 g1543__8428(.A1 (portB[6]), .B1 (INTRC), .B2 (AS2), .B3
       (ddrB[6]), .ZN (n_15));
  MUX2HDV2 g1544__5526(.I0 (SPI0_SL_OUT), .I1 (portB[4]), .S (n_3), .Z
       (n_14));
  INAND2HDV2 g1545__6783(.A1 (TXEN1), .B1 (n_12), .ZN (dd_B[3]));
  OAI21HDV2 g1546__3680(.A1 (n_1), .A2 (PCINT[2]), .B (n_2), .ZN
       (die_B[2]));
  OAI21HDV2 g1547__1617(.A1 (n_1), .A2 (PCINT[4]), .B (n_2), .ZN
       (die_B[4]));
  OAI21HDV2 g1548__2802(.A1 (n_1), .A2 (PCINT[3]), .B (n_2), .ZN
       (die_B[3]));
  OAI21HDV2 g1549__1705(.A1 (n_1), .A2 (PCINT[5]), .B (n_2), .ZN
       (die_B[5]));
  INOR2HDV2 g1550__5122(.A1 (n_4), .B1 (UMSEL), .ZN (n_13));
  NAND2HDV2 g1551__8246(.A1 (n_3), .A2 (ddrB[3]), .ZN (n_12));
  INOR2HDV2 g1552__7098(.A1 (n_4), .B1 (OC2A_EN), .ZN (n_11));
  AND2HDV2RD g1553__6131(.A1 (n_3), .A2 (ddrB[2]), .Z (dd_B[2]));
  IAO21HDV2 g1554__1881(.A1 (INTRC), .A2 (EXTCK), .B (AS2), .ZN (n_10));
  AND2HDV2RD g1555__5115(.A1 (n_3), .A2 (DDR_XCK1), .Z (dd_B[5]));
  OAI21HDV2 g1556__7482(.A1 (n_1), .A2 (PCINT[1]), .B (n_2), .ZN
       (die_B[1]));
  OAI21HDV2 g1557__4733(.A1 (n_1), .A2 (PCINT[0]), .B (n_2), .ZN
       (die_B[0]));
  NOR3HDV2 g1558__6161(.A1 (SPI0_MT_OUT), .A2 (TXD1), .A3 (OC2A), .ZN
       (n_9));
  IOA21HDV1 g1559__9315(.A1 (PCIE0), .A2 (PCINT[6]), .B (SLEEP), .ZN
       (n_8));
  INAND3HDV2 g1560__9945(.A1 (dd_B[1]), .B1 (n_0), .B2 (portB[1]), .ZN
       (pu_B[1]));
  INAND3HDV2 g1561__2883(.A1 (dd_B[0]), .B1 (n_0), .B2 (portB[0]), .ZN
       (pu_B[0]));
  CLKMUX2HDV0 g1562__2346(.I0 (portB[1]), .I1 (OC1A), .S (OC1A_EN), .Z
       (n_7));
  CLKMUX2HDV0 g1563__1666(.I0 (portB[2]), .I1 (OC1B), .S (OC1B_EN), .Z
       (n_6));
  INOR3HDV1 g1564__7410(.A1 (ddrB[6]), .B1 (INTRC), .B2 (AS2), .ZN
       (dd_B[6]));
  NOR3BBHDV2 g1565__6417(.A1 (n_4), .A2 (ddrB[4]), .B (RXEN1), .ZN
       (dd_B[4]));
  TBUFHDV0 g87__5477(.I (portB[0]), .OE (dd_B[0]), .Z (pv_B[0]));
  NOR2HDV2 g1566__2398(.A1 (SCK0_OUT), .A2 (XCK1_OUT), .ZN (n_5));
  NAND2HDV2 g1567__5107(.A1 (MSTR), .A2 (SPE0), .ZN (n_4));
  INAND2HDV2 g1568__6260(.A1 (MSTR), .B1 (SPE0), .ZN (n_3));
  OR2HDV2RD g1569__4319(.A1 (n_1), .A2 (PCIE0), .Z (n_2));
  INHDV2 g1570(.I (SLEEP), .ZN (n_1));
  INHDV2 g1571(.I (PUD), .ZN (n_0));
endmodule

