
// Generated by Cadence Genus(TM) Synthesis Solution 22.10-p001_1
// Generated on: Mar 12 2025 23:46:45 +07 (Mar 12 2025 16:46:45 UTC)

// Verification Directory fv/Port_D 

module rg_md_p_width8_p_init_val0_p_impl_mask255_1(clk, nrst, wdata,
     wbe, rdata, tog);
  input clk, nrst, wbe, tog;
  input [7:0] wdata;
  output [7:0] rdata;
  wire clk, nrst, wbe, tog;
  wire [7:0] wdata;
  wire [7:0] rdata;
  EDRNQHDV0 \rg_current_reg[3] (.RDN (nrst), .CK (clk), .D (wdata[3]),
       .E (wbe), .Q (rdata[3]));
  EDRNQHDV0 \rg_current_reg[2] (.RDN (nrst), .CK (clk), .D (wdata[2]),
       .E (wbe), .Q (rdata[2]));
  EDRNQHDV0 \rg_current_reg[0] (.RDN (nrst), .CK (clk), .D (wdata[0]),
       .E (wbe), .Q (rdata[0]));
  EDRNQHDV0 \rg_current_reg[4] (.RDN (nrst), .CK (clk), .D (wdata[4]),
       .E (wbe), .Q (rdata[4]));
  EDRNQHDV0 \rg_current_reg[6] (.RDN (nrst), .CK (clk), .D (wdata[6]),
       .E (wbe), .Q (rdata[6]));
  EDRNQHDV0 \rg_current_reg[1] (.RDN (nrst), .CK (clk), .D (wdata[1]),
       .E (wbe), .Q (rdata[1]));
  EDRNQHDV0 \rg_current_reg[5] (.RDN (nrst), .CK (clk), .D (wdata[5]),
       .E (wbe), .Q (rdata[5]));
  EDRNQHDV0 \rg_current_reg[7] (.RDN (nrst), .CK (clk), .D (wdata[7]),
       .E (wbe), .Q (rdata[7]));
endmodule

module rg_md_p_width8_p_init_val0_p_impl_mask255(clk, nrst, wdata, wbe,
     rdata, tog);
  input clk, nrst, wbe, tog;
  input [7:0] wdata;
  output [7:0] rdata;
  wire clk, nrst, wbe, tog;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_41;
  DRQHDV2 \rg_current_reg[0] (.RD (n_1), .CK (clk), .D (n_23), .Q
       (rdata[0]));
  DRQHDV2 \rg_current_reg[1] (.RD (n_1), .CK (clk), .D (n_22), .Q
       (rdata[1]));
  DRQHDV2 \rg_current_reg[5] (.RD (n_1), .CK (clk), .D (n_27), .Q
       (rdata[5]));
  DRQHDV2 \rg_current_reg[3] (.RD (n_1), .CK (clk), .D (n_24), .Q
       (rdata[3]));
  DRQHDV2 \rg_current_reg[7] (.RD (n_1), .CK (clk), .D (n_26), .Q
       (rdata[7]));
  DRQHDV2 \rg_current_reg[6] (.RD (n_1), .CK (clk), .D (n_28), .Q
       (rdata[6]));
  DRQHDV2 \rg_current_reg[4] (.RD (n_1), .CK (clk), .D (n_25), .Q
       (rdata[4]));
  IOA22HDV0 g1026__2398(.A1 (n_19), .A2 (wdata[6]), .B1 (wbe), .B2
       (n_3), .ZN (n_28));
  IOA22HDV0 g1027__5107(.A1 (n_20), .A2 (wdata[5]), .B1 (wbe), .B2
       (n_4), .ZN (n_27));
  IOA22HDV0 g1028__6260(.A1 (n_15), .A2 (wdata[7]), .B1 (wbe), .B2
       (n_11), .ZN (n_26));
  DRQHDV2 \rg_current_reg[2] (.RD (n_1), .CK (clk), .D (n_21), .Q
       (rdata[2]));
  IOA22HDV0 g1030__4319(.A1 (n_14), .A2 (wdata[4]), .B1 (wbe), .B2
       (n_5), .ZN (n_25));
  IOA22HDV0 g1031__8428(.A1 (n_17), .A2 (wdata[3]), .B1 (wbe), .B2
       (n_8), .ZN (n_24));
  IOA22HDV0 g1032__5526(.A1 (n_16), .A2 (wdata[0]), .B1 (wbe), .B2
       (n_10), .ZN (n_23));
  IOA22HDV0 g1033__6783(.A1 (n_18), .A2 (wdata[1]), .B1 (wbe), .B2
       (n_9), .ZN (n_22));
  AO22HDV0 g1034__3680(.A1 (n_41), .A2 (rdata[2]), .B1 (n_12), .B2
       (wdata[2]), .Z (n_21));
  IOA22HDV0 g1035__1617(.A1 (n_0), .A2 (rdata[5]), .B1 (n_7), .B2
       (rdata[5]), .ZN (n_20));
  IOA22HDV0 g1036__2802(.A1 (n_0), .A2 (rdata[6]), .B1 (n_7), .B2
       (rdata[6]), .ZN (n_19));
  IOA22HDV0 g1037__1705(.A1 (n_0), .A2 (rdata[1]), .B1 (n_7), .B2
       (rdata[1]), .ZN (n_18));
  IOA22HDV0 g1038__5122(.A1 (n_0), .A2 (rdata[3]), .B1 (n_7), .B2
       (rdata[3]), .ZN (n_17));
  IOA22HDV0 g1039__8246(.A1 (n_0), .A2 (rdata[0]), .B1 (n_7), .B2
       (rdata[0]), .ZN (n_16));
  IOA22HDV0 g1040__7098(.A1 (n_0), .A2 (rdata[7]), .B1 (n_7), .B2
       (rdata[7]), .ZN (n_15));
  IOA22HDV0 g1041__6131(.A1 (n_0), .A2 (rdata[4]), .B1 (n_7), .B2
       (rdata[4]), .ZN (n_14));
  OAI22HDV0 g1043__5115(.A1 (n_2), .A2 (tog), .B1 (n_0), .B2
       (rdata[2]), .ZN (n_12));
  INAND2HDV2 g1044__7482(.A1 (wdata[7]), .B1 (rdata[7]), .ZN (n_11));
  INAND2HDV2 g1045__4733(.A1 (wdata[0]), .B1 (rdata[0]), .ZN (n_10));
  INAND2HDV2 g1046__6161(.A1 (wdata[1]), .B1 (rdata[1]), .ZN (n_9));
  INAND2HDV2 g1047__9315(.A1 (wdata[3]), .B1 (rdata[3]), .ZN (n_8));
  INAND2HDV2 g1049__9945(.A1 (wdata[4]), .B1 (rdata[4]), .ZN (n_5));
  INAND2HDV2 g1050__2883(.A1 (wdata[5]), .B1 (rdata[5]), .ZN (n_4));
  INAND2HDV2 g1051__2346(.A1 (wdata[6]), .B1 (rdata[6]), .ZN (n_3));
  NOR2HDV2 g1052__1666(.A1 (wbe), .A2 (tog), .ZN (n_7));
  INHDV0 g1053(.I (wbe), .ZN (n_2));
  INHDV1 g1054(.I (nrst), .ZN (n_1));
  INHDV1 g1055(.I (tog), .ZN (n_0));
  OAI21BHDV2 g2(.A (n_7), .B1 (wbe), .B2 (wdata[2]), .ZN (n_41));
endmodule

module synchronizer_p_width8(clk, d_sync, d_in);
  input clk;
  input [7:0] d_in;
  output [7:0] d_sync;
  wire clk;
  wire [7:0] d_in;
  wire [7:0] d_sync;
  wire [7:0] d_latch;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  DQHDV2 \d_sync_int_reg[4] (.CK (clk), .D (d_latch[4]), .Q
       (d_sync[4]));
  DQHDV2 \d_sync_int_reg[6] (.CK (clk), .D (d_latch[6]), .Q
       (d_sync[6]));
  DQHDV2 \d_sync_int_reg[7] (.CK (clk), .D (d_latch[7]), .Q
       (d_sync[7]));
  DQHDV2 \d_sync_int_reg[0] (.CK (clk), .D (d_latch[0]), .Q
       (d_sync[0]));
  DQHDV2 \d_sync_int_reg[2] (.CK (clk), .D (d_latch[2]), .Q
       (d_sync[2]));
  DQHDV2 \d_sync_int_reg[5] (.CK (clk), .D (d_latch[5]), .Q
       (d_sync[5]));
  DQHDV2 \d_sync_int_reg[3] (.CK (clk), .D (d_latch[3]), .Q
       (d_sync[3]));
  DQHDV2 \d_sync_int_reg[1] (.CK (clk), .D (d_latch[1]), .Q
       (d_sync[1]));
  LAHHDV0 \d_latch_reg[0] (.E (clk), .D (d_in[0]), .Q (d_latch[0]), .QN
       (UNCONNECTED));
  LAHHDV0 \d_latch_reg[6] (.E (clk), .D (d_in[6]), .Q (d_latch[6]), .QN
       (UNCONNECTED0));
  LAHHDV0 \d_latch_reg[4] (.E (clk), .D (d_in[4]), .Q (d_latch[4]), .QN
       (UNCONNECTED1));
  LAHHDV0 \d_latch_reg[1] (.E (clk), .D (d_in[1]), .Q (d_latch[1]), .QN
       (UNCONNECTED2));
  LAHHDV0 \d_latch_reg[5] (.E (clk), .D (d_in[5]), .Q (d_latch[5]), .QN
       (UNCONNECTED3));
  LAHHDV0 \d_latch_reg[3] (.E (clk), .D (d_in[3]), .Q (d_latch[3]), .QN
       (UNCONNECTED4));
  LAHHDV0 \d_latch_reg[2] (.E (clk), .D (d_in[2]), .Q (d_latch[2]), .QN
       (UNCONNECTED5));
  LAHHDV0 \d_latch_reg[7] (.E (clk), .D (d_in[7]), .Q (d_latch[7]), .QN
       (UNCONNECTED6));
endmodule

module
     IO_Port_PINx_Address9_DDRx_Address10_PORTx_Address11_port_width8(ireset,
     cp2, IO_Addr, dbus_in, dbus_out, iore, iowe, out_en, portx, ddrx,
     pinx);
  input ireset, cp2, iore, iowe;
  input [5:0] IO_Addr;
  input [7:0] dbus_in, pinx;
  output [7:0] dbus_out, portx, ddrx;
  output out_en;
  wire ireset, cp2, iore, iowe;
  wire [5:0] IO_Addr;
  wire [7:0] dbus_in, pinx;
  wire [7:0] dbus_out, portx, ddrx;
  wire out_en;
  wire [7:0] pinx_reg;
  wire UNCONNECTED_HIER_Z, n_0, n_1, n_2, n_3, n_4, we_ddrx, we_pinx;
  wire we_portx;
  rg_md_p_width8_p_init_val0_p_impl_mask255_1 rg_md_ddrx_inst(.clk
       (cp2), .nrst (ireset), .wdata (dbus_in), .wbe (we_ddrx), .rdata
       (ddrx), .tog (UNCONNECTED_HIER_Z));
  rg_md_p_width8_p_init_val0_p_impl_mask255 rg_md_portx_inst(.clk
       (cp2), .nrst (ireset), .wdata (dbus_in), .wbe (we_portx), .rdata
       (portx), .tog (we_pinx));
  synchronizer_p_width8 synchronizer_pinx_inst(.clk (cp2), .d_sync
       (pinx_reg), .d_in (pinx));
  AO222HDV1 g708__7410(.A1 (n_2), .A2 (pinx_reg[4]), .B1 (n_3), .B2
       (portx[4]), .C1 (n_4), .C2 (ddrx[4]), .Z (dbus_out[4]));
  AO222HDV1 g709__6417(.A1 (n_2), .A2 (pinx_reg[6]), .B1 (n_3), .B2
       (portx[6]), .C1 (n_4), .C2 (ddrx[6]), .Z (dbus_out[6]));
  AO222HDV1 g710__5477(.A1 (n_4), .A2 (ddrx[7]), .B1 (n_2), .B2
       (pinx_reg[7]), .C1 (n_3), .C2 (portx[7]), .Z (dbus_out[7]));
  AO222HDV1 g711__2398(.A1 (n_2), .A2 (pinx_reg[0]), .B1 (n_3), .B2
       (portx[0]), .C1 (n_4), .C2 (ddrx[0]), .Z (dbus_out[0]));
  AO222HDV1 g712__5107(.A1 (n_4), .A2 (ddrx[2]), .B1 (n_2), .B2
       (pinx_reg[2]), .C1 (n_3), .C2 (portx[2]), .Z (dbus_out[2]));
  AO222HDV1 g713__6260(.A1 (n_4), .A2 (ddrx[5]), .B1 (n_2), .B2
       (pinx_reg[5]), .C1 (n_3), .C2 (portx[5]), .Z (dbus_out[5]));
  AO222HDV1 g714__4319(.A1 (n_4), .A2 (ddrx[3]), .B1 (n_2), .B2
       (pinx_reg[3]), .C1 (n_3), .C2 (portx[3]), .Z (dbus_out[3]));
  AO222HDV1 g715__8428(.A1 (n_4), .A2 (ddrx[1]), .B1 (n_2), .B2
       (pinx_reg[1]), .C1 (n_3), .C2 (portx[1]), .Z (dbus_out[1]));
  AND2HDV2RD g716__5526(.A1 (n_2), .A2 (iowe), .Z (we_pinx));
  AND2HDV2RD g717__6783(.A1 (n_4), .A2 (iowe), .Z (we_ddrx));
  AND2HDV2RD g718__3680(.A1 (n_3), .A2 (iowe), .Z (we_portx));
  NOR2HDV2 g719__1617(.A1 (n_1), .A2 (IO_Addr[0]), .ZN (n_4));
  INOR2HDV2 g720__2802(.A1 (IO_Addr[0]), .B1 (n_1), .ZN (n_3));
  NOR3BBHDV2 g721__1705(.A1 (n_0), .A2 (IO_Addr[0]), .B (IO_Addr[1]),
       .ZN (n_2));
  CLKNAND2HDV2 g722__5122(.A1 (n_0), .A2 (IO_Addr[1]), .ZN (n_1));
  OA211HDV2 g723__8246(.A1 (IO_Addr[1]), .A2 (IO_Addr[0]), .B (n_0), .C
       (iore), .Z (out_en));
  INOR4HDV2 g724__7098(.A1 (IO_Addr[3]), .B1 (IO_Addr[2]), .B2
       (IO_Addr[4]), .B3 (IO_Addr[5]), .ZN (n_0));
endmodule

module Port_D(cp2, ireset, IO_Addr, iore, iowe, out_en, dbus_in,
     dbus_out, pinD_i, DID_o, DDR_XCK0, pu_D, dd_D, pv_D, die_D, PUD,
     SLEEP, RXEN0, TXEN0, OC0A_EN, OC0B_EN, OC2B_EN, OC3B_EN, OC4B_EN,
     OC4A_EN, OC3A_EN, XCK0_OUT, OC0A, OC0B, OC2B, OC3B, OC4B, OC4A,
     OC3A, UMSEL, TXD0, PCINT, INT1_EN, INT0_EN, PCIE2, AINxD);
  input cp2, ireset, iore, iowe, PUD, SLEEP, RXEN0, TXEN0, OC0A_EN,
       OC0B_EN, OC2B_EN, OC3B_EN, OC4B_EN, OC4A_EN, OC3A_EN, XCK0_OUT,
       OC0A, OC0B, OC2B, OC3B, OC4B, OC4A, OC3A, UMSEL, TXD0, INT1_EN,
       INT0_EN, PCIE2;
  input [5:0] IO_Addr;
  input [7:0] dbus_in, pinD_i, PCINT;
  input [1:0] AINxD;
  output out_en, DDR_XCK0;
  output [7:0] dbus_out, DID_o, pu_D, dd_D, pv_D, die_D;
  wire cp2, ireset, iore, iowe, PUD, SLEEP, RXEN0, TXEN0, OC0A_EN,
       OC0B_EN, OC2B_EN, OC3B_EN, OC4B_EN, OC4A_EN, OC3A_EN, XCK0_OUT,
       OC0A, OC0B, OC2B, OC3B, OC4B, OC4A, OC3A, UMSEL, TXD0, INT1_EN,
       INT0_EN, PCIE2;
  wire [5:0] IO_Addr;
  wire [7:0] dbus_in, pinD_i, PCINT;
  wire [1:0] AINxD;
  wire out_en, DDR_XCK0;
  wire [7:0] dbus_out, DID_o, pu_D, dd_D, pv_D, die_D;
  wire [7:0] portD;
  wire [7:0] ddrD;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  assign dd_D[4] = DDR_XCK0;
  assign DID_o[0] = pinD_i[0];
  assign DID_o[1] = pinD_i[1];
  assign DID_o[2] = pinD_i[2];
  assign DID_o[3] = pinD_i[3];
  assign DID_o[4] = pinD_i[4];
  assign DID_o[5] = pinD_i[5];
  assign DID_o[6] = pinD_i[6];
  assign DID_o[7] = pinD_i[7];
  IO_Port_PINx_Address9_DDRx_Address10_PORTx_Address11_port_width8
       IO_Port_D_inst(.ireset (ireset), .cp2 (cp2), .IO_Addr (IO_Addr),
       .dbus_in (dbus_in), .dbus_out (dbus_out), .iore (iore), .iowe
       (iowe), .out_en (out_en), .portx (portD), .ddrx ({dd_D[7:5],
       DDR_XCK0, dd_D[3:2], ddrD[1:0]}), .pinx (pinD_i));
  TBUFHDV0 g52__6131(.I (n_13), .OE (dd_D[2]), .Z (pv_D[2]));
  AO31HDVL g960__1881(.A1 (n_4), .A2 (OC3B), .A3 (OC4B), .B (n_12), .Z
       (n_13));
  TBUFHDV0 g53__5115(.I (n_11), .OE (dd_D[1]), .Z (pv_D[1]));
  OA31HDV1 g961__7482(.A1 (n_3), .A2 (OC4B), .A3 (OC3B), .B (portD[2]),
       .Z (n_12));
  TBUFHDV0 g48__4733(.I (n_10), .OE (dd_D[6]), .Z (pv_D[6]));
  TBUFHDV0 g54__6161(.I (n_9), .OE (dd_D[0]), .Z (pv_D[0]));
  TBUFHDV0 g49__9315(.I (n_8), .OE (dd_D[5]), .Z (pv_D[5]));
  TBUFHDV0 g50__9945(.I (n_7), .OE (DDR_XCK0), .Z (pv_D[4]));
  IOA22HDV0 g962__2883(.A1 (n_2), .A2 (portD[1]), .B1 (n_2), .B2 (n_5),
       .ZN (n_11));
  NAND3BBHDV2 g963__2346(.A1 (dd_D[0]), .A2 (PUD), .B (portD[0]), .ZN
       (pu_D[0]));
  TBUFHDV0 g51__1666(.I (n_6), .OE (dd_D[3]), .Z (pv_D[3]));
  NAND3BBHDV2 g964__7410(.A1 (dd_D[1]), .A2 (PUD), .B (portD[1]), .ZN
       (pu_D[1]));
  NAND3BBHDV2 g965__6417(.A1 (PUD), .A2 (dd_D[2]), .B (portD[2]), .ZN
       (pu_D[2]));
  NAND3BBHDV2 g966__5477(.A1 (PUD), .A2 (dd_D[3]), .B (portD[3]), .ZN
       (pu_D[3]));
  NAND3BBHDV2 g967__2398(.A1 (PUD), .A2 (dd_D[5]), .B (portD[5]), .ZN
       (pu_D[5]));
  NAND3BBHDV2 g968__5107(.A1 (PUD), .A2 (dd_D[7]), .B (portD[7]), .ZN
       (pu_D[7]));
  NAND3BBHDV2 g969__6260(.A1 (PUD), .A2 (dd_D[6]), .B (portD[6]), .ZN
       (pu_D[6]));
  NAND3BBHDV2 g970__4319(.A1 (PUD), .A2 (DDR_XCK0), .B (portD[4]), .ZN
       (pu_D[4]));
  CLKMUX2HDV0 g971__8428(.I0 (portD[6]), .I1 (OC0A), .S (OC0A_EN), .Z
       (n_10));
  CLKMUX2HDV0 g972__5526(.I0 (portD[0]), .I1 (OC3A), .S (OC3A_EN), .Z
       (n_9));
  CLKMUX2HDV0 g973__6783(.I0 (portD[5]), .I1 (OC0B), .S (OC0B_EN), .Z
       (n_8));
  CLKMUX2HDV0 g974__3680(.I0 (portD[4]), .I1 (XCK0_OUT), .S (UMSEL), .Z
       (n_7));
  CLKMUX2HDV0 g975__1617(.I0 (portD[3]), .I1 (OC2B), .S (OC2B_EN), .Z
       (n_6));
  TBUFHDV0 g47__2802(.I (portD[7]), .OE (dd_D[7]), .Z (pv_D[7]));
  NOR2HDV2 g976__1705(.A1 (OC4A), .A2 (TXD0), .ZN (n_5));
  INOR2HDV2 g977__5122(.A1 (ddrD[0]), .B1 (RXEN0), .ZN (dd_D[0]));
  INHDV0 g978(.I (n_3), .ZN (n_4));
  NOR2HDV2 g979__8246(.A1 (OC3B_EN), .A2 (OC4B_EN), .ZN (n_3));
  NOR2HDV2 g980__7098(.A1 (TXEN0), .A2 (OC4A_EN), .ZN (n_2));
  OR2HDV2RD g981__6131(.A1 (TXEN0), .A2 (ddrD[1]), .Z (dd_D[1]));
  OAOI211HDV1 g823__1881(.A1 (n_0), .A2 (PCINT[3]), .B (n_1), .C
       (INT1_EN), .ZN (die_D[3]));
  OAOI211HDV1 g824__5115(.A1 (n_0), .A2 (PCINT[2]), .B (n_1), .C
       (INT0_EN), .ZN (die_D[2]));
  OAI21HDV2 g825__7482(.A1 (n_0), .A2 (PCINT[5]), .B (n_1), .ZN
       (die_D[5]));
  OAI21HDV2 g826__4733(.A1 (n_0), .A2 (PCINT[0]), .B (n_1), .ZN
       (die_D[0]));
  OAI21HDV2 g827__6161(.A1 (n_0), .A2 (PCINT[4]), .B (n_1), .ZN
       (die_D[4]));
  OAI21HDV2 g828__9315(.A1 (n_0), .A2 (PCINT[1]), .B (n_1), .ZN
       (die_D[1]));
  IAO22HDV2 g829__9945(.A1 (SLEEP), .A2 (AINxD[0]), .B1 (PCIE2), .B2
       (PCINT[6]), .ZN (die_D[6]));
  IAO22HDV2 g830__2883(.A1 (SLEEP), .A2 (AINxD[1]), .B1 (PCIE2), .B2
       (PCINT[7]), .ZN (die_D[7]));
  OR2HDV2RD g831__2346(.A1 (n_0), .A2 (PCIE2), .Z (n_1));
  INHDV2 g832(.I (SLEEP), .ZN (n_0));
endmodule

